### ISSUE TITLE
SQL Server 2005 as Database Writer Error-> "Could not retrieve database metadata. Please ensure that your driver, URL, username and password are correct."

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1088]
Hi Gurus,

I have created a channel with Source as HL7 message and Destination as Database Writer.
I am trying to connect to the SQL server as a destination 'Database Writer' and given following URL:

Driver->  SQL server/Sybase

URL-> jdbc:jtds:sqlserver://machine name/TestDB

(I have also tried by replacing IP address instead of machine name and also tried by providing port number 1433)

However it is giving me error as "Could not retrieve database metadata. Please ensure that your driver, URL, username and password are correct."

I have tried all the solutions given by gurus here in MIRTH community, but not able to resolve the error.

Please help. Its urgent

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1084
Reporter: yogesh_puranik
Created: 2009-05-08T03:37:53.000-0700

**Comment by rbeckman-nextgen** [comment]
Chris, please test and verify this is an issue.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-05-15T13:20:12.000-0700

**Comment by rbeckman-nextgen** [comment]
This is not an issue with Mirth.  It is a configuration issue with your SQL Server or your channel.  According to Christopher Ro, you probably need to make the user authentication mode to 'mixed mode'.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-05-15T13:44:53.000-0700

**Comment by rbeckman-nextgen** [comment]
This is not a bug.  Please ensure that you have the correct DB URL String, and the SQL User Authentication mode is set to "Mixed Mode" in SqlServer configuration.




Imported Comment. Original Details:
Author: chrisr
Created: 2009-05-15T13:46:09.000-0700

**Comment by bhatb** [comment]
I am facing the same issue.
My SQL User Authentication mode is set to "Mixed Mode" in SqlServer configuration and 
url is according to the template url provided, also the user has dbowner rights but I am still facing same issue.

**Comment by pacmano1** [comment]
They need connect rights also.  Can you connect from the command line of the mirth server with the MySQL client?
