### ISSUE TITLE
Despite a fix, a comment on the last line of a Javascript destination will still cause Mirth 1.8 deployment to fail

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1142]
If the last line in a Javascript destination is a comment, deployment will fail.

This was addressed in MIRTH-838, but I don't know if that fix applied to all Javascript, or perhaps just the post-processor/pre-processor.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1139
Reporter: colinsj
Created: 2009-07-09T10:00:35.000-0700

**Comment by rbeckman-nextgen** [comment]
I am attaching a channel that demonstrates the issue in Mirth Version 1.8.0.4126.

Imported Comment. Original Details:
Author: colinsj
Created: 2009-07-09T10:00:52.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed an issue where the last line of a JavaScript connector could not be a comment.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-07-13T15:04:07.000-0700

**Comment by SSpeer** [comment]
UNSUBSCRIBE
