### ISSUE TITLE
Template functions to handle HL7 escape characters

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1262]
HL7 strings use escape characters in the body of HL7 messages to transmit characters used as delimiters and for some other special purposes (e.g. highlighting, etc ...)

Following is an incomplete list of escape sequences which can be handled by special transformation functions.

Character	Description Conversion
\E\	Escape character converted to escape character (e.g., '\')
\F\	Field separator converted to field separator character (e.g., '|')
\R\	Repetition separator converted to repetition separator character (e.g., '~')
\S\	Component separator converted to component separator character (e.g., '^')
\T\	Subcomponent separator converted to subcomponent separator character (e.g., '&')

Following are suggested constraints of the proposed functions:
 * Work only with recommended delimiters (^~\&|)
 * Do not handle \Xdd...\, \Cxxyy\ or \Mxxyyzz\ escape sequences
 * Do not handle \H\ , \N\, or \Zdd...\ escape sequences

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1262
Reporter: aoganesi
Created: 2009-12-01T16:35:28.000-0800

**Comment by rbeckman-nextgen** [comment]
Suggested Implementation:

function parseHL7String(hl7String)
{
	var parsedString = hl7String.replace(/\\F\\/g, '|');	
	parsedString = parsedString.replace(/\\S\\/g, '^');	
	parsedString = parsedString.replace(/\\R\\/g, '~');	
	parsedString = parsedString.replace(/\\T\\/g, '&');	
        parsedString = parsedString.replace(/\\E\\/g, '\\');
	return parsedString;
}

function formatHL7String(str)
{
	var hl7String = str.replace(/\\/g, '\\E\\');
	hl7String = hl7String.replace(/\|/g, '\\F\\');	
	hl7String = hl7String.replace(/\^/g, '\\S\\');	
	hl7String = hl7String.replace(/~/g, '\\R\\');	
	hl7String = hl7String.replace(/&/g, '\\T\\');	
	return hl7String;
}

Imported Comment. Original Details:
Author: aoganesi
Created: 2009-12-01T16:37:57.000-0800

**Comment by rbeckman-nextgen** [comment]
This should be implemented as part of a code template library, as discussed in MIRTH-1276.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-12-22T15:51:55.000-0800

**Comment by rbeckman-nextgen** [comment]
We should also look into handling this natively in the HL7 parser.

Imported Comment. Original Details:
Author: geraldb
Created: 2010-06-30T10:32:29.000-0700

**Comment by ppazos** [comment]
Working with Mirth 4.x and this doesn't seem to be implemented as part of the Mirth functions accessible from the transformer. Feels something basic for any HL7 v2.x message that contains a text field like in NTE.

I'm wondering why is this "closed as completed"? @pladesma

**Comment by lcestola** [comment]
> Working with Mirth 4.x and this doesn't seem to be implemented as part of the Mirth functions accessible from the transformed. Feels something basic for any HL7 v2.x message that contains a text field like in NTE.

This is why we have to deal with malformed error messages every day. The absence of such a basic function is a strange fact.
