### ISSUE TITLE
Add locking mechanism to Global Variable Store

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1277]
The globalMap used in the Global Variable Store needs to have some way of locking specific keys.  For more information on the reason for this requirement, see the following thread: http://www.mirthcorp.com/community/forums/showthread.php?t=3240

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1277
Reporter: jacobb
Created: 2009-12-22T16:27:34.000-0800

**Comment by rbeckman-nextgen** [comment]
Added Sync methods to all of the current globalMap and globalChannelMap methods.  The syncMap is a different map entirely, and has lock, unlock, containsKey, remove, get, put, putAll, and clear methods (all with the Sync suffix).

Imported Comment. Original Details:
Author: jacobb
Created: 2010-02-17T15:30:18.000-0800

**Comment by tonygermano** [comment]
updated forum link https://forums.mirthproject.io/forum/mirth-connect/support/3298-is-globalmap-the-best-way-to-access-values-across-channels
