### ISSUE TITLE
Remove dependence on CachedRowSetImpl

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1810]
CachedRowSetImpl is a proprietary class that may eventually be removed. We should find an alternative to use. The use of this class also results in build warnings.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1826
Reporter: geraldb
Created: 2011-04-28T10:16:48.000-0700

**Comment by rbeckman-nextgen** [comment]
Since we already extend CachedRowSetImpl with MirthCachedRowSet, we could potential just copy the code from CachedRowSetImpl and remove the dependency on it altogether.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-04-17T11:00:50.000-0700

**Comment by tonygermano** [comment]
Duplicate of #4602
