### ISSUE TITLE
Add timeout option for administrator

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2074]
For security reasons, it would be useful to have a timeout setting that will disconnect the client after some period of time.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2117
Reporter: geraldb
Created: 2012-03-16T08:03:41.000-0700

**Comment by rbeckman-nextgen** [comment]
Comment from GH: This may need to be configurable per user account not just system wide since some users like to leave the dashboard open all day.

Imported Comment. Original Details:
Author: geraldb
Created: 2012-03-16T08:08:32.000-0700

**Comment by rbeckman-nextgen** [comment]
It would be nice to actually know when and why timeouts happen.  Is there already a built in timeout value?  What is it?

Imported Comment. Original Details:
Author: stickybandit
Created: 2015-06-15T12:50:38.000-0700

**Comment by rbeckman-nextgen** [comment]
Would really like this feature!

Imported Comment. Original Details:
Author: justinsk
Created: 2017-07-07T12:46:42.000-0700

**Comment by tabdo** [comment]
My security team is requesting this feature for HiTrust.
