### ISSUE TITLE
Add debugging to JavaScript channel code

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2100]
Add debugging to JavaScript channel code.  One example of this is shown here:

http://www.mirthcorp.com/community/forums/showthread.php?t=7018

This is using the Rhino JavaScript debugger.  The main issue is that it needs to be run on the server in the server's JVM, rather than on the client.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2148
Reporter: jacobb
Created: 2012-05-08T11:27:31.000-0700

**Comment by tonygermano** [comment]
See discussion at https://github.com/nextgenhealthcare/connect/discussions/4650
