### ISSUE TITLE
Provide a listing of in-use ports

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2115]
This is a feature request. I'm working with a low-medium use MC installation. Approximately 20 channels. As I bring new channels online I have to find an open port for those channels to listen on.

It would be handy if MC had a feature that could either list in-use ports or indicate in the source connector step if the entered port is available. 

Initially this could be as simple as showing listening ports (a la netstat). Ideally it would go so far as to cover in-use ports from other applications as well as trolling through the source ports on other channels. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2165
Reporter: jbartels
Created: 2012-06-04T07:44:07.000-0700

**Comment by rbeckman-nextgen** [comment]
In general, a "server overview" page would be helpful to see a quick list of all currently listening sockets used by MC (with source IPs if connected), as well as all established sockets (with destination IPs), etc. There are many possibilities with a page like this... for example, you could let the user choose to include settings from currently undeployed channels (or as Jon mentioned, other processes on the same machine), highlight potential conflicts, etc. There might even be a customizable list of open ports to -not- include in the view (e.g. 135/445 on Windows), and some filtering/view options. 

Imported Comment. Original Details:
Author: narupley
Created: 2012-06-04T07:57:32.000-0700

**Comment by rbeckman-nextgen** [comment]
Would be nice if a optional column on the administrator could be "source port"?

Imported Comment. Original Details:
Author: yorkie
Created: 2017-11-16T07:59:22.000-0800

**Comment by amaster507** [comment]
This would also be useful for our environment.

**Comment by tonygermano** [comment]
Reopening due to previous comment and relevant discussion today in slack channel.

**Comment by pladesma** [comment]
Which of these options is more useful? Assume you can click a button on the Source Connector to bring up the option.

1. See a list of ports in use
2. See a list of ports available
3. See if the port you have chosen is available

**Comment by pacmano1** [comment]
IMHO, 
item 1 is the best, but it must enumerate actual ports in use at the OS level and ports specified on undeployed listener channels
Item 2 shows way to many ports
Item 3 nice to have assuming with same caveat as item 1

**Comment by MichaelLeeHobbs** [comment]
Would love to see item 1!

**Comment by jonbartels** [comment]
I did some work on this at https://github.com/jonbartels/mirth-connect-dashboard-count a few months ago
