### ISSUE TITLE
Message template tree doesn't show node descriptions for HL7 versions 2.5.1 and 2.6

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2195]
This is just because the relevant XML files aren't yet included in generator/reference/.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2253
Reporter: narupley
Created: 2012-10-29T14:50:17.000-0700

**Comment by rbeckman-nextgen** [comment]
FYI, this shouldn't affect anyone using the strict parser, because that's handled in HAPI.

Imported Comment. Original Details:
Author: narupley
Created: 2012-10-29T14:58:23.000-0700

**Comment by rbeckman-nextgen** [comment]
Message template tree doesn't show node descriptions for HL7 version 2.7 either.

Imported Comment. Original Details:
Author: dbe
Created: 2012-10-30T01:39:50.000-0700

**Comment by rbeckman-nextgen** [comment]
Hi, 
I am facing this issue on latest version of Mirth (Mirth Connect Server 2.2.2.6388). Any idea on approximate date to fix & release this issue ? 
It will be helpful, if you can guide me with some work around also. I need to generate database mapping from HL7 v2.5.1 message. And without Description in the 'Message Tree' its difficult.

Thanks in advance!

Imported Comment. Original Details:
Author: abhed
Created: 2013-07-08T05:35:21.000-0700

**Comment by rbeckman-nextgen** [comment]
In the meantime, you can just use version 2.5 instead of 2.5.1 in the message template. I'm not sure off the top of my head what differences there are between the two versions, but the message structure (and field descriptions) are probably very similar if not identical for many message types. If you're using an outbound template, make sure to change the version back to 2.5.1 before you deploy the channel.

Also make sure to have the HL7 specifications (and the client specifications, if applicable) handy so you can make sure you're building the message correctly. Though, that should be done _all_ _the_ _time_, not just when building a message whose descriptions don't show up in the tree.

Imported Comment. Original Details:
Author: narupley
Created: 2013-07-08T06:14:47.000-0700

**Comment by cturczynskyj** [comment]
Duplicate of: https://github.com/nextgenhealthcare/connect/issues/4538
