### ISSUE TITLE
Add editable Privacy Statement / Authorized users only banner into login process.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2197]
Platinum client ID # 14071 suggests: It would be nice if the application could call a banner before access to the login page...If you choose to put it in some future release as a definable parameter in the mirth.properties using a reference to a particular text file that would be nice...

Reference case # 21252
(Perhaps having the banner displayed on the Mirth Connect Login screen just below the Username and Password fields would be most efficient?  Perhaps changing the Login button slightly to read: Accept and Login?)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2255
Reporter: hdmoscm
Created: 2012-11-01T06:12:53.000-0700

**Comment by rbergeron-psi** [comment]
During our security review an issue was flagged in not being able to see the DOD security banner before logging into the administrator. I am wondering if we can open this ticket to help us address the issue that has been flagged by our security team.
