### ISSUE TITLE
Which java version to use to compile it from source?

### ISSUE THREAD

**Issue by Loki-Afro** [nextgenhealthcare/connect#22]
Didn't see that issues are enabled here, I posted the question on Stackoverflow, please answer where ever you want I'll copy your answer to sackoverflow/github if you don't mind :)

https://stackoverflow.com/questions/61522274/mirth-connect-which-java-version-to-use-to-compile-it-from-source

**Comment by Loki-Afro** [comment]
Question was answered on stackoverflow, seems like it requires java 8 from oracle.

but a complete guide on how to build and run this would be very helpful!

**Comment by cturczynskyj** [comment]
We have a build guide up on the wiki now [https://github.com/nextgenhealthcare/connect/wiki/Clone-Build-and-Run-from-Source](https://github.com/nextgenhealthcare/connect/wiki/Clone-Build-and-Run-from-Source)
