### ISSUE TITLE
Channels created in Mirth Connect 2.2.1 can't be imported into 3.0.0 Beta 1

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2270]
Channels created in Mirth Connect v2.2.1 can't be imported into v3.0.0 Beta 1. Once you select the channel for import and click ok, nothing happens. Also no output can be found for it in mirth.log. 

The new version should be backward compatible with v2.2.1 channels. It would be impossible for us to re-created all channels for the new version. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2333
Reporter: gepingwu
Created: 2013-01-16T15:16:23.000-0800

**Comment by rbeckman-nextgen** [comment]
The version you're testing with is 3.0.0 Beta 1, and there isn't (nor will there be) support for imports / channel migration from another version to 3.0.0 Beta 1, or from 3.0.0 Beta 1 to any other version.

There WILL BE, however, an automatic migration process to and from the 3.0.0 GA, when that is eventually released.

Imported Comment. Original Details:
Author: narupley
Created: 2013-01-16T16:00:22.000-0800

**Comment by sadikpasha06** [comment]
can you provide any official documentation or Blogs from NextGen (Mirth Connect) on this issue Forword and backward compatibility ?
