### ISSUE TITLE
Choose a different table font or automatically resize columns based on font

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2582]
The Tahoma truetype is not installed on Linux environments by default, therefore some of the fixed-width table columns in the administrator may not be wide enough to display all of the information. This can be fixed by installing the Tahoma font manually by running the following.

wget http://download.microsoft.com/download/ie6sp1/finrel/6_sp1/W98NT42KMeXP/EN-US/IELPKTH.CAB
cabextract -F 'tahoma*ttf' IELPKTH.CAB
mkdir -p /usr/share/fonts/truetype/msttcorefonts/
mv -f tahoma*ttf /usr/share/fonts/truetype/msttcorefonts/
chmod 644 /usr/share/fonts/truetype/msttcorefonts/tahoma*
fc-cache -v
rm -f IELPKTH.CAB

However, we can also think about picking a different font that is available by default on all machines, or allowing columns to resize automatically based on the font available.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2649
Reporter: wayneh
Created: 2013-06-17T16:37:16.000-0700

**Comment by tonygermano** [comment]
I believe this issue should be reopened. It's still a problem, and the workaround described no longer works.

**Comment by tonygermano** [comment]
Also, the workaround mentioned no longer works, as Tahoma is not free and was removed from the MS TrueType font package long ago.
