### ISSUE TITLE
Malformed swagger.json file

### ISSUE THREAD

**Issue by anthonypants** [nextgenhealthcare/connect#3]
[The Swagger 2.0 documentation](https://swagger.io/docs/specification/2-0/basic-structure/) requires an info block, which contains a title, a description (optional), and the version of the API. Mirth Connect generates an info block which contains only the API version number.

**Comment by cturczynskyj** [comment]
With the swagger documentation refresh in 3.9.0 the info block is now populated.
```
{
  "openapi": "3.0.1",
  "info": {
    "title": "NextGen Connect Client API",
    "description": "Swagger documentation for the NextGen Connect Client API.",
    "version": "3.9.0"
  },
...
}
```
