### ISSUE TITLE
No longer able to webstart with default security settings on Java 7 update 51

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3028]
New security requirements are now being enforced in Java 7u51. More information here: https://blogs.oracle.com/java-platform-group/entry/new_security_requirements_for_rias
\\
\\
{quote}**Developers:**

 As of 7u51, (January 14, 2014), your RIAs must be updated. The updates required are on the packaging and distribution; no API code changes should be required. The impetus for these changes relates to potential re-purposing of sandboxed applications, whereby placing permissions within a signed JAR prevents modification of your specified permission level.
RIAs must contain two things:

    Code signatures from a trusted authority. All code for Applets and Web Start applications must be signed, regardless of its Permissions attributes.
    Manifest Attributes
        Permissions – Introduced in 7u25, and required as of 7u51. Indicates if the RIA should run within the sandbox or require full-permissions.
        Codebase – Introduced in 7u25 and optional/encouraged as of 7u51. Points to the known location of the hosted code (e.g. intranet.example.com).{quote}

There are a couple of workarounds for this. First, you can add your webstart URL to the Exception Site List in the Java security settings (e.g. "http://localhost:8080"). Second, you can turn the security level down from High (the default and minimum recommended level) to Medium.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3114
Reporter: narupley
Created: 2014-01-15T09:54:25.000-0800

**Comment by rbeckman-nextgen** [comment]
Attaching screenshots

Imported Comment. Original Details:
Author: narupley
Created: 2014-01-15T09:57:04.000-0800

**Comment by tonygermano** [comment]
Closing this as no longer relevant. Mirth no longer supports java 7, and java no longer supports webstart.
