### ISSUE TITLE
Add complete user security roles

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#314]
Channels should be assigned to particular users or groups. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-297
Reporter: admin
Created: 2007-04-05T00:06:12.000-0700

**Comment by rbeckman-nextgen** [comment]
Bayatree is asking for a way they can encrypt the channel when we deploy it on any  customer site so that users can't change or view the code. (Perhaps a view Dashboard only account, and a view Dashboard and Message filter account?) (vTiger 5424)

Imported Comment. Original Details:
Author: hdmoscm
Created: 2008-08-26T06:04:03.000-0700

**Comment by rbeckman-nextgen** [comment]
At our compagny we need 3 types of roles:
1) read-only: only seeing messages that have been sent 
2) operator: the same as the first but with the ability to reprocess a message
3) administrator: can do everything



Imported Comment. Original Details:
Author: vanno
Created: 2008-11-02T13:46:34.000-0800

**Comment by rbeckman-nextgen** [comment]
Schuylkill Health in Pottsville, PA is looking for something like this as well.  Currently our HIS vendor, CPSI, maintains our Mirth engine.  We'd like to at least be able to view inbound/outbound logs, status screens/messages/etc.  CPSI tells us they are waiting on Mirth to add the ability to open this up to us without giving us complete access.

Any idea when this will be available?

Imported Comment. Original Details:
Author: jfritsch
Created: 2010-02-17T10:24:11.000-0800

**Comment by rbeckman-nextgen** [comment]
This is available as the User Roles Plugin:
http://www.mirthcorp.com/products/mirth-connect#Extensions

Imported Comment. Original Details:
Author: jacobb
Created: 2013-10-22T16:44:49.000-0700

**Comment by wi4seo** [comment]
Hi,

FREE Registration for Mirth Unconference 2023 is Now Opened!

To know more, please visit the event page and register yourself: https://wi4.org/mirth-connect-unconference-feb-2023/

Stay Tuned for More Updates!
