### ISSUE TITLE
Add OAuth authentication to the HTTP and Web Service Sender connectors

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3261]
Imported Issue. Original Details:
Jira Issue Key: MIRTH-3360
Reporter: narupley
Created: 2014-07-01T08:16:18.000-0700

**Comment by mochsner** [comment]
Found another issue for inbound OAuth that was a good find, but this is the integration I was originally looking for. It sounds like outbound OAuth (from Mirth) is not supported, and may not be for a while. Sounds like this may be something we need to develop custom in plain Javascript then?
