### ISSUE TITLE
Database Writer gets stuck in 'Reading' state causing all new messages to queue indefinitely

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3360]
Periodically, the Database Writer will get stuck in the 'Reading' state.  When this happens all new messages are queued indefinitely.  The only way to start processing again is to pause/start the channel or re-deploy the channel.  When this happens the database is alive and well but Mirth gets stuck.  Here is the relevant stack trace(s) from the mirth log:

{noformat}
ERROR 2014-09-16 12:11:28,372 [pool-6-thread-1] com.mirth.connect.connectors.tcp.TcpReceiver: Error receiving message (TCP Listener "Source" on channel 6641f092-f6aa-40bd-87dd-9bf8ff9f0493).
java.net.SocketException: Socket closed
>---at java.net.SocketInputStream.socketRead0(Native Method)
>---at java.net.SocketInputStream.read(SocketInputStream.java:152)
>---at java.net.SocketInputStream.read(SocketInputStream.java:122)
>---at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
>---at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
>---at com.mirth.connect.model.transmission.framemode.FrameStreamHandler.read(FrameStreamHandler.java:120)
>---at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:560)
>---at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:462)
>---at java.util.concurrent.FutureTask.run(FutureTask.java:262)
>---at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>---at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>---at java.lang.Thread.run(Thread.java:744)
ERROR 2014-09-16 12:11:28,949 [Thread-37] com.mirth.connect.donkey.server.channel.DestinationChain: Error processing destination BoxView Database Cluster.
java.lang.IllegalStateException: Pool closed
>---at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1135)
>---at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
>---at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
>---at com.mirth.connect.connectors.jdbc.DatabaseDispatcherQuery.getConnection(DatabaseDispatcherQuery.java:156)
>---at com.mirth.connect.connectors.jdbc.DatabaseDispatcherQuery.send(DatabaseDispatcherQuery.java:89)
>---at com.mirth.connect.connectors.jdbc.DatabaseDispatcherQuery.send(DatabaseDispatcherQuery.java:127)
>---at com.mirth.connect.connectors.jdbc.DatabaseDispatcherQuery.send(DatabaseDispatcherQuery.java:81)
>---at com.mirth.connect.connectors.jdbc.DatabaseDispatcher.send(DatabaseDispatcher.java:107)
>---at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:599)
>---at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:336)
>---at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:224)
>---at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1428)
>---at com.mirth.connect.donkey.server.channel.Channel.processSourceQueue(Channel.java:1530)
>---at com.mirth.connect.donkey.server.channel.Channel.run(Channel.java:1517)
>---at java.lang.Thread.run(Thread.java:744)
{noformat}

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3460
Reporter: marksigep
Created: 2014-09-16T22:40:49.000-0700

**Comment by rbeckman-nextgen** [comment]
Patches for trunk and 3.0.3 to catch exception.  Exception can be safely ignored since the data source will be closed and re-opened in the follow code.

Imported Comment. Original Details:
Author: marksigep
Created: 2014-09-17T04:52:20.000-0700

**Comment by rbeckman-nextgen** [comment]
Investigate whether this still happens in 3.2.

Imported Comment. Original Details:
Author: narupley
Created: 2015-04-28T08:21:27.000-0700

**Comment by rbeckman-nextgen** [comment]
I do not believe this is an issue anymore after the switch to HikariCP.

Imported Comment. Original Details:
Author: marksigep
Created: 2015-09-02T19:58:20.000-0700

**Comment by rbeckman-nextgen** [comment]
This should no longer be an issue since the call to dataSource.getConnection is inside a try..catch now.

Imported Comment. Original Details:
Author: narupley
Created: 2017-01-29T10:40:19.000-0800

**Comment by davutg** [comment]
The issue is there but I'm unable to reproduce. It's happening 2-3 times a year while writing to SQLServer thru JDBC. It's in try catch as generated template in use. This happens with 3.6.1. Anything changed for this with 3.10 current version?

Can we use JS timeout, something like 
```
setTimeout(()=>{
     Task_JDBC_TRANSACTION();
},timeout)
```

**Comment by toddmueller** [comment]
We are still running into this issue with 3.6.1. Any update on how to resolve this?

**Comment by pacmano1** [comment]
It looks like it was patched and closed.   i.e. you need a later version of Mirth connect.   Nextgen doesn't fix old releases.

Although @davutg says he still sees it 3 times a year.    I do use DB writers but only in JS mode so I never see this.

**Comment by davutg** [comment]
@pacmano1 as we discussed in the group and implementing below timeouts we less likely encountered such an issue.
jdbc:jtds:sqlserver://YOURSERVER:1433/YOURDB;loginTimeout=7;socketTimeout=5
Maybe another case, but if there's any RECEIVED (but not processed) message stopping/halting not working. So, what I'm trying to do for such cases is handling underlying reasons causing stuck. For reading timeout, for sending destination another timeout, for connecting another timeout... otherwise any indefinite op may cause the same consequence. Halt is not able to halt when there's any unpressed message always.. and without stopping the channel we can't delete that unprocessed message. For such a catastrophic case I'm going for the last resort and restarting entire mirth service.

**Comment by pacmano1** [comment]
What do you think is the underlying problem?  Query is
blocked at SQL Server by some other query?   I just don't see this problem in my environments for over 10 years or so I am curious.

**Comment by davutg** [comment]
@pacmano1 of course environment to environment there are differences. There are multiple possibilities as underlying reasons. DB state, db transaction locks , network issues.. and handling these underlying cases is setting timeout instead of indefinitely waiting.. 

or a single threaded channel has an unhandled sql exception, so addressing this underlying problem is try catch block. 

We’ve also channels working seamlessly so long. However, there are extreme cases happening ie DBA is killing a long running session. That’s why environment and implementation matters.

**Comment by davutg** [comment]
For mission critical projects I design multiprocess applications, so I am not killing entire process and other tasks(threads) along with it. When you’re not able to stop a channel using a certain port what’s your solution for a mirth instance running 100+ channels. I’m curious if I am the only one encountering this halt not working cases..

**Comment by pacmano1** [comment]
Sure, was wondering about your specific use case and what downstream analysis you do when the timeout occurs.   Mostly to help others.   For example at some places, people leave transactions open blocking other queries.  Other places require far bettter DB tuning.   IMHO, actual network connectivity errors should be near zero or zero exclusive of planned downtimes.  

As for 100 channels - I have had (before I knew better) 1400 channels running on an engine, and still never encountereed your situation such that I need to restarrt an engine (which is then still an issue if you have to do it).  But the largest variables is I am not on MSSQL for most work, rather PostgreSQL, I realize that helps you none.   

Whether to re-open this issue or create a new one is your call of course.

**Comment by tonygermano** [comment]
This is most likely related to this issue, which is for the DB Reader side.

https://github.com/nextgenhealthcare/connect/issues/3304
