### ISSUE TITLE
Ability to add custom banner before log on.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3393]
When the  Mirth Connect administrator starts up, we would like a way to add the custom warning banner before being challenged for the username and password.

A hook to display a custom text or page before the log on screen would be ideal.. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3496
Reporter: rbergeron
Created: 2014-10-21T13:35:12.000-0700

**Comment by rbeckman-nextgen** [comment]
You can already do that by replacing public_html/images/splashscreen.png with your own image (clear your Java cache before launching the client again). But perhaps we should build in a more standard way of doing that, as replacing the PNG file seems a bit hacky.

Imported Comment. Original Details:
Author: narupley
Created: 2014-10-21T13:39:52.000-0700

**Comment by rbeckman-nextgen** [comment]
I think it would be nice to have a more standard way, maybe a parameter in mirth.properties with the location of the file..

Imported Comment. Original Details:
Author: rbergeron
Created: 2014-10-21T13:42:00.000-0700

**Comment by rbergeron-psi** [comment]
During our security review an issue was flagged in not being able to see the DOD security banner before logging into the administrator. I am wondering if we can open this ticket to help us address the issue that has been flagged by our security team.
