### ISSUE TITLE
Add ability for CLI to load plugin JARs

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3422]
Currently, the CLI ships with all the core extension JARs. Unlike the Administrator, if the user has installed additional extensions, it will not load them dynamically. Consequently, if the client API returns any serialized data to the CLI containing references to any additional extension code, it will fail to deserialize and generate an error in the CLI.

It would be ideal if the CLI somehow dynamically loaded all non-core extension JARs.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3525
Reporter: brentm
Created: 2014-11-13T10:28:14.000-0800

**Comment by rbeckman-nextgen** [comment]
What about just making the CLI load all client and shared folders in the /extensions folder. That way if an extension is installed then it will just work. If someone has just the CLI installed they can still install extensions manually. All we need to do is load the jars right? There is no need to run any services or things like that since the CLI is just a client.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-11-17T09:37:58.000-0800

**Comment by rbeckman-nextgen** [comment]
Yup, that'll work if they're running the CLI from the MC installation/home directory. If they're running the CLI from somewhere else, how do they get the extensions?

Imported Comment. Original Details:
Author: narupley
Created: 2014-11-17T09:42:27.000-0800

**Comment by rbeckman-nextgen** [comment]
Unless I'm missing something, wouldn't you just create an extensions subfolder manually and install manually. As long as there is a sub-folder called extensions, it should work. It could even get the pluginMetadata from the server its connecting to and only load the ones it finds (and complain if it doesn't find one that is installed on the server).

Imported Comment. Original Details:
Author: wayneh
Created: 2014-11-17T10:54:53.000-0800

**Comment by rbeckman-nextgen** [comment]
That would work, but it sounds like something only we would know how to do.

If I'm a non-administrator connecting to a Mirth Connect instance via a standalone CLI, I would have to download the Administrator JNLP, look in each of the sub-JNLPs, manually download each of the dependency JARs for each of the plugins specified, and put those in my extensions folder that I create manually.

Of course I could just e-mail the administrator and say "hey can you send me your zipped extensions folder so I can include it in my CLI?".

Imported Comment. Original Details:
Author: narupley
Created: 2014-11-17T11:00:30.000-0800

**Comment by rbeckman-nextgen** [comment]
Something will have to be done manually for standalone CLI no matter what. The only other feasible option I see is to download it automatically from the server. I think as long as we download the pluginMetaData/connectorMetaData from the server and inform the user upon CLI start of which plugins are missing, that should be ok. We could tell them to contact their system administrator or something. 

Imported Comment. Original Details:
Author: wayneh
Created: 2014-11-17T12:42:19.000-0800

**Comment by rbeckman-nextgen** [comment]
It appears that CLI **already** loads the shared jars of extensions. However it simply doesn't load the client jars which it probably should since it is basically a client. 

The following is already in CommandLineLauncher.java

`
private static void addSharedLibsToClasspath(List<URL> urls) throws Exception {
        IOFileFilter sharedLibFileFilter = new WildcardFileFilter("*-shared.jar");
        File extensions = new File("./extensions");

        if (extensions.exists() && extensions.isDirectory()) {
            Collection<File> sharedLibs = FileUtils.listFiles(extensions, sharedLibFileFilter, FileFilterUtils.trueFileFilter());

            for (File sharedLib : sharedLibs) {
                logger.trace("adding library to classpath: " + sharedLib.getAbsolutePath());
                urls.add(sharedLib.toURI().toURL());
            }
        } else {
            logger.warn("no extensions found");
        }
    }
`

Imported Comment. Original Details:
Author: wayneh
Created: 2014-12-22T15:27:37.000-0800

**Comment by rbeckman-nextgen** [comment]
Any model classes that the CLI might reference (like data returned by the client API) should be in the shared jars and not the client jars. There aren't likely to be any cases in which the CLI references classes from a plugin's client jars.

The only remaining problem is that the CLI will not be able to load plugin shared jars if it is running outside of the server root folder. In this case, the workaround is to manually copy the required jars into an /extensions subfolder where the CLI resides.

Imported Comment. Original Details:
Author: brentm
Created: 2014-12-29T10:18:21.000-0800

**Comment by manaschandanroy** [comment]
@rbeckman-nextgen did you find a way to load the custom jars. I just created a sub folder inside extension folder of  fhir, but i feel it is not installed. Is there any way to load the custom jar , some command to run it and install it in cli
My channel shows as disabled as the custom jars are still missing . Would appreciate the help
