### ISSUE TITLE
Code templates for getting HTTP request headers, parameters use deprecated functions.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3630]
Under the HTTP Listener Functions category of code templates are the following:

Get HTTP Request Header
Get HTTP Request Parameter

Both of these, however, use deprecated methods.

For the Header template, it gives you:
sourceMap.get('headers').get('Header-Name')

For the Parameter template, it gives you:
sourceMap.get('parameters').get('parameterName')

When using them, it logs the following errors:

ERROR (com.mirth.connect.userutil.MessageHeaders:39): The get(key) method for retrieving Http headers is deprecated and will soon be removed. Please use getHeader(key) or getHeaderList(key) instead.

ERROR (com.mirth.connect.userutil.MessageParameters:39): The get(key) method for retrieving Http parameters is deprecated and will soon be removed. Please use getParameter(key) or getParameterList(key) instead.

These code templates should be updated to use the correct, non-deprecated methods.

Also, while fixing these, it would probably be useful to add code templates for getting the entire header list or parameter list.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3744
Reporter: ericb
Created: 2015-07-03T16:14:06.000-0700

**Comment by tonygermano** [comment]
This is still an issue for parameters as of mirth 4.3.0. It looks like the headers code template was fixed as of 4.0.0 in https://github.com/nextgenhealthcare/connect/commit/d0b5f9996959a92ffdde8f149a3c6b4b6c5900ff

**Comment by jdonextgen** [comment]
Fix committed and will be released in MC 4.4.0.

**Comment by jdonextgen** [comment]
Fix committed and will be released in MC 4.4.0.

**Comment by jonbartels** [comment]
https://github.com/nextgenhealthcare/connect/commit/bca27fcee0dd351d733cbd701355c95cf37dfcb8
