### ISSUE TITLE
Mirth Doesn't support  NCPDP D.0 standard it supports only 5010 

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3655]
Mirth Connect works fine for NCPDP 5010 standard but NCPDP D.0 standard is having few additional fields .

In NCPDPReference.java file additional fields are added but when use D.0 message in message template section it throws error "Invalid NCPDP template".

In order to fix this issue kindly see attached screens , i have modified code using eclipse and now it works fine for D.0 Standard.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3771
Reporter: charan
Created: 2015-09-02T22:56:22.000-0700

**Comment by rbeckman-nextgen** [comment]
Foe exmaple you can test with Filed "2J" which is "Prescriber First Name"  , this field is additional in D.0 standard .
So if this field is present in NCPDP message in current version than it will throw an error of invalid NCPDP message.

This is because in NCPDPVocabulory.java file version is given only "51" (5010) there is no entry for D.0 version.

Imported Comment. Original Details:
Author: charan
Created: 2015-09-02T23:01:03.000-0700

**Comment by rbeckman-nextgen** [comment]
Can some one provide an update on this ??.
Do we expect this bug getting resolved??


Imported Comment. Original Details:
Author: charan
Created: 2015-11-25T01:39:00.000-0800

**Comment by dongravlinnordic** [comment]
> Can some one provide an update on this ??.
> Do we expect this bug getting resolved??
> 
> Imported Comment. Original Details:
> Author: charan
> Created: 2015-11-25T01:39:00.000-0800

does this work yet?
