### ISSUE TITLE
Add the ability to determine exactly which queue thread messages go to

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3669]
Right now the Thread Assignment Variable uses a hash algorithm to automatically assign queue threads to messages being dispatched.

However, because it's a deterministic hash, collisions may happen. Say for example you only have 2 possible values for the thread assignment variables (e.g. "true" or "false"), and 2 queue threads. Right now it's _**not**_ guaranteed that messages for each value will go into each of the 2 threads. The hash could collide them into one thread anyway.

Instead what would be useful is an option to specify a table of possible discrete values. The number of entries in the table would be limited to the number of queue threads currently configured. If any message comes in with a value in that table, it will be sent directly to the corresponding queue thread. Otherwise the hash/modulo operation will occur as normal.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3786
Reporter: narupley
Created: 2015-09-16T07:36:53.000-0700

**Comment by rbeckman-nextgen** [comment]
What's the likelihood that the hash would collide?

Imported Comment. Original Details:
Author: jacobb
Created: 2015-09-16T10:22:55.000-0700

**Comment by rbeckman-nextgen** [comment]
It really depends on the number of queue threads you have, and the number of possible discrete values. In the ideal case, a deterministic hash is completely random (in the real world it's not exactly random, but Murmur3 does a pretty good job, and the best job of all the hash algorithms that I researched). But if we assume that it's truly random, then when you have 2 possible discrete values and 2 queue threads, the chance of them colliding into one thread is 50%. If you increase the queue threads to 100 while still keeping only two possible discrete values, the chance of them colliding into one thread is 1% (but then you'll have at least 98 threads not doing anything).

In a more common real-world case, you don't just have a small set of discrete values. For example if you're using the patient external MRN, you might have thousands, tens of thousands, even hundreds of thousands of different possible MRN values. If you have 10 queue threads and 10,000 possible MRN values, _obviously_ some are going to collide (pigeonhole principle). But the chance of them all colliding into one thread in that case is ridiculously low (1 in 10 ^9999^).  Even the chance of one queue thread _not_ being used at all in that case is extremely low (1 in 10 ^458^ or so, still vastly more than the number of elementary particles in the observable universe).

In general the more discrete values, the more even the queue thread distribution should be, with uneven bumps being way outside the standard deviation. The issue only really manifests itself when the number of possible discrete values is low.

Imported Comment. Original Details:
Author: narupley
Created: 2015-09-16T11:28:42.000-0700

**Comment by rbeckman-nextgen** [comment]
In my case we have 408 discrete values. These values are location identifiers and we want a "bucket" for each location. 
I have run all these values thru your hashing algorithm an these we're my findings:

10 thread pool:
bucket | locations
0	36
1	50
2	36
3	37
4	45
5	33
6	45
7	40
8	48
9	38

With 408 thread pool:
Only about 260 "usable" threads.

I don't think I should increase the thread number beyond 408. It would reduce the chance of hash collision but I dont think Mirth would handle such a huge amount of threads would it? 



Imported Comment. Original Details:
Author: hugosoares2
Created: 2015-09-17T03:00:36.000-0700

**Comment by rbeckman-nextgen** [comment]
You'll probably get different values every time you restart the channel, because the hash function is initialized with a pseudorandom seed. The number of threads isn't constrained by Mirth Connect, but rather by the machine it's running on (CPU cores, RAM, OS, etc.). A typical server can handle thousands of threads without issue.

Another possible way we could tackle this is like so. When the destination queue starts, it has X available threads/buckets. When it encounters a new thread assignment value, instead of using the hash it could just pick the first unassigned thread, and assign it to that value. It continues to do that for all new values until it has reached the X ^th^ value. At that point all the threads have an assigned value. Then we have a couple of options. We could continue to round-robin threads for any new values, or we could just start using the hash algorithm.

The disadvantage of the first option is that we have to keep a map of all values and their associated thread IDs. It could potentially grow unbounded if new thread assignment values are always being encountered and old ones may never be used again. This would actually be quite common with the main use-case, external patient MRNs. We _could_ use a linked map that automatically removes old values when it reaches an arbitrary cap (maybe 10X or something). But removing old values means that technically we're no longer guaranteeing that messages for a given value will _**always**_ be sent to the same queue thread. I also have concerns about the queue performance with this option (microseconds matter here). The advantage is obviously that the thread distribution is guaranteed to be as even as possible.

The second option allows up to X (the thread count) values to be guaranteed to be in different threads, and then from that point on it works the way it currently does. It's a hybrid approach that only requires a regular map of size X and nothing else.

I prefer the second option because it's simpler and requires less work from the destination queue itself (very important for overall performance). In your case with 408 values, if you have 408 threads then every thread would be guaranteed to be used. If you have 406 threads then all of them would still be guaranteed to be used, but any value past the 406 ^th^ would use the hash. So then you'd have a 1 in 406 (0.2%) chance of the remaining two values to collide into one thread. If you have significantly more values than you have threads (like 408 values and 10 threads), then the distribution would be slightly better than it is now because the first 10 values encountered would always go into 10 different threads.

Imported Comment. Original Details:
Author: narupley
Created: 2015-09-17T07:35:14.000-0700

**Comment by rbeckman-nextgen** [comment]
I believe the second option would be enough because I roughly know how many buckets I need anyway it is just a matter of controlling the distribution on those buckets in a predictable manner and has efficiently has possible...

I am just wondering if/how we could visualize the bucket distribution and processing on the dashboard. I could simply use a custom metadata field with the same var has the thread assignment var and use the filtering options to get some sense of what's happening on each bucket....

Imported Comment. Original Details:
Author: hugosoares2
Created: 2015-09-18T06:09:11.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 7907: The destination queue will now round-robin buckets up to the maximum queue threads set. When this number is reached, the hash function will be used from then on. This approach allows users with a discrete set of possible thread assignment values to ensure that no values will collide into the same queue thread.

Imported Comment. Original Details:
Author: narupley
Created: 2016-02-05T16:27:44.000-0800

**Comment by rbeckman-nextgen** [comment]
This looks good. 

I've been running different tests to verify the new functionality. 

Let's say you send in 800 messages with unique bucket values and you have 400 threads. In this scenario the first 400 messages were correctly adquired by each thread. After that we went back to the old random behavior. 

Here is how many messages each thread processed for the different values:
1 value - 147 Threads
2 values - 145 Threads
3 values - 79 Threads
4 values - 21 Threads
5 values 6 Threads
6 values - 2 Threads

run 2:
1 value - 155 Threads
2 values - 141 Threads
3 values - 66 Threads
4 values - 26 Threads
5 values 11 Threads
6 values - 1 Threads

If you add them up you can see that all 400 threads were used for at least the first round of messages because of this change. You can see that some threads were assigned a couple more values than the others but that is just the nature of this approach. 

Like it was mentioned above, if you had something like 402 values and 400 threads there is a very small chance that the last two values would be assigned to the same thread so there would be 398 threads with one value and 2 threads with two values in most cases.

Also verified that the round robin values are still preserved after the first time the messages are received. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-03-30T16:35:03.000-0700

**Comment by rbeckman-nextgen** [comment]
Just to be clear the old behavior would have been that not all 400 threads might have been used in these test cases. This really only benefits scenarios where the number of values is in the same magnitude as the number of threads. In cases where there is a huge number of possible values the behavior should be the same really(only marginally better).

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-03-30T16:44:37.000-0700

**Comment by rbeckman-nextgen** [comment]
Why not separate the number of threads from the definition of a collision?  There are really two questions here:

 - How collisions are determined for the purposes of blocking messages.
 - How much work is done in parallel (i.e. threads) which could be constrained by external considerations like memory usage, DB pools, external libraries that aren't threadsafe, etc.

If I have 20,000 patients, it should be possible for a single thread to process all unblocked messages.  I need only define my buckets (patient ID) and when to retry errored/blocking messages (e.g. every 5 minutes or after exhausting the queue).  Once I've defined my buckets, I have the **option** (but not obligation) to parallelize the work.

Imported Comment. Original Details:
Author: ambsw
Created: 2019-01-07T12:07:49.000-0800

**Comment by rbeckman-nextgen** [comment]
The number of threads **are** already separate from the definition of a collision.

The Queue Thread Count determines how many threads will be used. If you leave it at 1, no parallelization is done, so there's your option.

The Thread Assignment Variable determines which messages are in the same group and thus should process in order. It's not sufficient to just consider these "blocking" other messages, we must be sure to process any such messages in the order that they were put into the queue. And that could apply to multiple groups of messages too. For example if you have two messages in the queue with PID 1 and two messages with PID 2, the first messages for PID 1 and 2 can still process simultaneously.

It's also possible that I'm not fully understanding your idea. Maybe if you expanded on it? What exact queue options would the end-user see and how would the queue threads have to work on the backend?

Imported Comment. Original Details:
Author: narupley
Created: 2019-01-07T12:43:32.000-0800

**Comment by rbeckman-nextgen** [comment]
[I'm running 3.6.1; if this has changed in a more recent version, please let me know.]

It may make sense to focus on my single-threaded example:

> If I have 20,000 patients [and define a bucketing value to the Patient ID], it should be possible for a single thread to process all [messages for unblocked patients].

I assume Mirth Connect cannot do this because I can only assign a "Thread Assignment Variable" (TAV) if threads >1.  If the two concepts were completely independent, it should be possible to bucket without threading.  If I understand the current implementation, they're tightly coupled.  If a thread blocks, it blocks for everything hashed into it (which may include several values in the Thread Assignment Variable).

In principle (thought probably not in practice) setting the TAV to patient ID should create 20k virtual buckets in my example above (order preserved within each bucket).  Threads should round robin through the 20k virtual buckets (not a number of buckets equal to the number of threads).  If the message fails, it should only block the one virtual bucket defined by the TAV (and no others).
 
In this way, the number of workers is unrelated to the number of buckets.  Even a single thread can try a message for patient 1 then 2 then 3 then 4.  No single patient can block the others because there's no coupling between thread/worker and bucket.

Imported Comment. Original Details:
Author: ambsw
Created: 2019-01-07T16:09:40.000-0800

**Comment by jonbartels** [comment]
I found a snippet that will tell you what queue bucket a message is in.

Per the detailed conversation above, that you should read again because it is very informative, you should never really need this information since Mirth has a sufficiently robust hashing and bucketing algorithm:

```
var internalConnectorMessage = org.apache.commons.lang3.reflect.FieldUtils.readField(connectorMessage, "connectorMessage", true);
var bukkit = internalConnectorMessage.getQueueBucket();
$co('bukkit', bukkit);
return bukkit;
```
