### ISSUE TITLE
Values within the code template/library exported xml file are inconsistent

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3704]
In Mirth Connect 3.3.0, exporting the same code template libraries yields different results; the fields within the <contextSet> tag seem to get scrambled around after testing multiple exports.  No modifications were made to the libraries or templates. The channel IDs under the <enabledChannelIds> tag seem to switch around as well. The change in xml file happens most consistently after a restart of the Connect service.

See below for examples:

First export
`
<delegate>
<contextType>DESTINATION_FILTER_TRANSFORMER</contextType>
<contextType>GLOBAL_DEPLOY</contextType>
<contextType>CHANNEL_UNDEPLOY</contextType>
<contextType>DESTINATION_DISPATCHER</contextType>
<contextType>GLOBAL_UNDEPLOY</contextType>
<contextType>CHANNEL_BATCH</contextType>
<contextType>GLOBAL_PREPROCESSOR</contextType>
<contextType>GLOBAL_POSTPROCESSOR</contextType>
<contextType>SOURCE_RECEIVER</contextType>
<contextType>CHANNEL_ATTACHMENT</contextType>
<contextType>CHANNEL_DEPLOY</contextType>
<contextType>CHANNEL_POSTPROCESSOR</contextType>
<contextType>DESTINATION_RESPONSE_TRANSFORMER</contextType>
<contextType>CHANNEL_PREPROCESSOR</contextType>
<contextType>SOURCE_FILTER_TRANSFORMER</contextType>
</delegate>
</contextSet>
`

Second export after a restart of the Connect service gives a different output
`
<contextSet>
<delegate>
<contextType>GLOBAL_UNDEPLOY</contextType>
<contextType>DESTINATION_RESPONSE_TRANSFORMER</contextType>
<contextType>CHANNEL_DEPLOY</contextType>
<contextType>GLOBAL_PREPROCESSOR</contextType>
<contextType>DESTINATION_DISPATCHER</contextType>
<contextType>DESTINATION_FILTER_TRANSFORMER</contextType>
<contextType>CHANNEL_UNDEPLOY</contextType>
<contextType>CHANNEL_ATTACHMENT</contextType>
<contextType>GLOBAL_DEPLOY</contextType>
<contextType>GLOBAL_POSTPROCESSOR</contextType>
<contextType>CHANNEL_PREPROCESSOR</contextType>
<contextType>SOURCE_FILTER_TRANSFORMER</contextType>
<contextType>SOURCE_RECEIVER</contextType>
<contextType>CHANNEL_BATCH</contextType>
<contextType>CHANNEL_POSTPROCESSOR</contextType>
</delegate>
</contextSet>
`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3821
Reporter: calvinouk
Created: 2015-10-19T15:47:38.000-0700

**Comment by rbeckman-nextgen** [comment]
This is expected because those are regular Sets, not linked or anything. Those two exports are completely valid, it doesn't matter at all what order that context types are in.

However we _could_ switch to a linked set in those cases, so that a diff tool won't complain about it.

Imported Comment. Original Details:
Author: narupley
Created: 2015-10-19T15:52:03.000-0700

**Comment by rbeckman-nextgen** [comment]
"Settings->Backup Config" and 'exportcfg' in CLI are impacted as well.

vote +1 because i think that exports and backups should give reproducible results

Imported Comment. Original Details:
Author: aloyse
Created: 2015-10-19T23:51:43.000-0700

**Comment by tonygermano** [comment]
Duplicate of #5004
