### ISSUE TITLE
Add OAuth 2.0 token verification mode to HTTP Authentication settings

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3728]
This would add the ability to extract an access token from a request header or query parameter in the incoming request, and hit a verification endpoint on a remote OAuth 2.0 server.

The requirements would be:
* The access token is plainly accessible from a request header (e.g. Authorization header) or a query parameter.
* The verification endpoint is a URL pointing to a remote OAuth 2.0 server that supports a GET request, passing the access token in the same way it was received (as a request header or query parameter).
* The verification endpoint returns a < 300 response code if the verification was successful, and a >= 400 response code if not.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3845
Reporter: narupley
Created: 2015-11-24T10:42:03.000-0800

**Comment by rbeckman-nextgen** [comment]
Revision 7897: Added OAuth token verification mode. Mirth Connect does **not** act as a resource server or resource owner here. It is more of a passthrough client that simply hits a verification endpoint, passing along the access token. Users can decide whether the access token is expected as a request header (e.g. Authorization) or a query parameter (e.g. auth_token). Upon request, the authenticator will perform a GET request to the verification endpoint, and based solely on the response code will either accept or reject the request. If rejected, the originating system is expected to request a new access token from the resource server and then submit a new request to the channel.

Imported Comment. Original Details:
Author: narupley
Created: 2016-02-01T12:51:09.000-0800

**Comment by rbeckman-nextgen** [comment]
To test, certainly you can try with an actual OAuth server API, like Imgur/Facebook/etc. It would suffice however, to just use a separate HTTP Listener and point the verification URL to that.

Imported Comment. Original Details:
Author: narupley
Created: 2016-02-01T13:02:57.000-0800

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** local OSX Yosemite 10.10 with Java 8 Update 51 
**Version(s)/Build(s) to verify new feature:** mirthconnect-3.4.0.7925.b1883
**3rd party tools for this test**
Postman - API sender <https://www.getpostman.com/>
IMGUR API service:  <https://api.imgur.com/>
**What tested:**
From Mirth Connect:
* Create channel with source = HTTP Listener, port #8600
* Under HTTP Authentication, select Authentication Type = OAuth
* Access Token Location = Request Header, Authorization
* Verification URL = https://api.imgur.com/oauth2/secret
* Deploy Channel 

From Postman
* Perform “Get Access Token” using the following info
`Imgur Authorization Endpoint: https://api.imgur.com/oauth2/authorize
Imgur Access Token: https://api.imgur.com/oauth2/token
Client ID: 5fac0ec0cafe6fc
Client secret: dfb3cb65528512319875e005738f97c71d561019
Grant Type = client credentials`
* Perform GET request using url = http://10.10.15.97:8600
* Select Authorization = OAuth2 and select "Add token to header" 
* Send GET request

**Observations:**
-Status 200 OK from Postman
-Listener channel rec'd & sent 1 message for each request from Postman
-Verified access token being passed through as authorization=[ Bearer <access_token> ] 
Source headers = `{accept-encoding=[gzip, deflate, sdch], connection=[keep-alive], postman-token=[8491d4ba-e52d-c1dc-0790-b1fe746f72aa], authorization=[Bearer 14647e7bf993b0ede9266446b1ae02dbe027752f], cache-control=[no-cache], host=[10.10.15.97:8600], accept-language=[en-US,en;q=0.8], user-agent=[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36], accept=[*/*]} `
Source method = GET
Source clientCertificateChain = [ ]
!msg_mappings.png!

Imported Comment. Original Details:
Author: minht
Created: 2016-03-01T10:14:47.000-0800

**Comment by rbeckman-nextgen** [comment]
**What tested:**
* Create Channel 1, acting as OAuth server 
Source = HTTP Listener, port 8888 
SSL Settings Enabled = Yes, enter SSL settings for Server & Client certificate, 
Authentication Type = none
Copy the HTTPs URL for the next channel
* Create Channel 2, this is the passthrough channel
Source = HTTP Listener, port 8890,
Authentication Type = OAuth 2.0 
Access Token Location = Request Header, Authorization
Verification URL =  paste the URL from Channel 1 (https://10.10.15.97:8888/OAuth/)
Use SSL Manager = Yes, enter SSL settings for Server & Client certificate

* From Postman, using the same access token as above, perform GET request to url = http://10.10.15.97:8600
* Verify successful connection from Postman
* Verify secure request received at Channel 1 ( port 8888)

**Observations:**
Successful verified SSL enabled for OAuth server request 
!OAuthServerMappings.png!


Imported Comment. Original Details:
Author: minht
Created: 2016-03-02T12:13:38.000-0800

**Comment by rbeckman-nextgen** [comment]
Verified OAuth 2.0 token verification mode with HTTP Listener

Imported Comment. Original Details:
Author: minht
Created: 2016-03-02T12:14:14.000-0800

**Comment by mochsner** [comment]
@rbeckman-nextgen  - nice feature! Is there any pre-existing documentation on this other than this issue? Would love to help improve it and add another OAuth2 server (in my case I use azure) as an example of authentication folks can use. Some sort of guide on how to use it on Azure (if I can get it working) would be awesome, even if I need to create it.
