### ISSUE TITLE
Implement Connection Pooling for User Queries

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3819]
Some channels run hundreds of database queries per second. It essential for those channels to have a pool of connections so that they are not constantly opened and closed, which is an expensive operation. I have created a JavaScript implementation of Hikari connection pool with two public methods, queryPoolDbConn() and updatePoolDbConn() and one private method, getPoolDbConn(). This implementation has proven itself to be well-performant and relatively robust. However, in some cases possibly caused by dropped DB connection, the Hikari DataSource fails to recover when the database gets back online and that requires restart of Mirth Connect.

Being a fundamental infrastructure facility, such implementation of connection pool is must be incorporated into the Mirth Connect application.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3939
Reporter: aitougan
Created: 2016-04-25T11:17:46.000-0700

**Comment by rbeckman-nextgen** [comment]
Duplicates MIRTH-2228

Imported Comment. Original Details:
Author: narupley
Created: 2016-04-25T11:19:18.000-0700

**Comment by tonygermano** [comment]
Adding attachments from original issue in Jira

[clearConnectionPools_evict.js.txt](https://github.com/nextgenhealthcare/connect/files/5226957/clearConnectionPools_evict.js.txt)
[getPoolDbConn_hikari_evictConnection.js.txt](https://github.com/nextgenhealthcare/connect/files/5226958/getPoolDbConn_hikari_evictConnection.js.txt)
[queryPoolDbConn.js.txt](https://github.com/nextgenhealthcare/connect/files/5226959/queryPoolDbConn.js.txt)
[updatePoolDbConn.js.txt](https://github.com/nextgenhealthcare/connect/files/5226960/updatePoolDbConn.js.txt)

**Comment by dfauraz** [comment]
I real solution in resources, or in the database connector itself would make sense.
Using javascript should not be necessary for getting connection pools, IMHO
