### ISSUE TITLE
Address XML external entity vulnerability

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3822]
[https://www.owasp.org/index.php/XML_External_Entity_%28XXE%29_Processing]

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3942
Reporter: narupley
Created: 2016-04-26T07:23:01.000-0700

**Comment by cturczynskyj** [comment]
Update with requirements:

- External entity resolution is no longer allowed anywhere XML is parsed.
- Run Tests to compare after fix and verify any unexpected behaviors

See [OWASP Cheatsheet](https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#java) for more info.
