### ISSUE TITLE
Error "The Mirth Connect Service could not be started."

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3824]
**What is the issue:** Getting Error in Window Notification Area for MC server manager even though MC services started
**Is the Issue Consistent (list details):** 
- stop services would show successful notification
- start or restart services would show Error notification 

**Steps to Reproduce:**
* From Window Control Panel\All Control Panel Items\Notification Area Icons => "mcmanager.exe" behaviors = Show icon and notifications 
* Launch Mirth Connect Server Manager
* Select "Start" or "Restart"   

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3944
Reporter: minht
Created: 2016-04-26T11:53:24.000-0700

**Comment by rbeckman-nextgen** [comment]
Getting the Error in Windows 10 as well. 

Imported Comment. Original Details:
Author: khaleshahs
Created: 2018-07-06T10:25:10.000-0700

**Comment by rbeckman-nextgen** [comment]
I appear to get this issue when NOT running on Derby. It was typically not an issue when running on Derby as the database solution. When I switch to Postgres or SQL server the issue begins to manifest on Windows Server 2016, even on a clean database with no channels installed.

Service appears to actually start succesfully, but the error message appears any time I start service with Mirth Connect Service Manager. No errors when starting with Windows "Services" control panel applet.





Imported Comment. Original Details:
Author: vlight
Created: 2020-01-23T06:32:50.000-0800

**Comment by astaerk** [comment]
I can confirm this problem for me and multiple colleagues.
We're currently running Mirth 3.7.0 with OpenJDK 1.8.0_202 and MS SQL Server 14 on Windows Server 2016.

According to the mirth.log the server has been started successfully. No Errors at all in the log. But starting with the Mirth Connect Service Manager shows the error "The Mirth Connect Service could not be started.". After this the m gets orange and the service is running.

**Comment by daniellabirch** [comment]
I just upgraded to 3.11 and I am experiencing this same issue in Windows.

**Comment by shaytan1986** [comment]
Any update on this?

**Comment by alacrator** [comment]
confirmed on mirth 3.12.0.b2650, JDK 17.0.1 SQL server 2017

**Comment by pladesma** [comment]
The "Internal-Issue-Created" label indicates that we have a backlog item to work on this issue in the future though it's not necessarily a high priority at the moment.

**Comment by JackieK5** [comment]
After reviewing this item, we have determined that we will not be addressing the issue at this time.  It may be reviewed again in the future if time permits, or it may be revisited if related work is being done, but for now it is being closed.
