### ISSUE TITLE
Message Storage Settings different for each Tier (DEV, TEST, PROD)

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3831]
I want to be able to set all my channels to Development and uncheck the delete options for my Development environment.  But in our TEST and PRODUCTION we have much more strict settings on some and all channels.
The problem is that we use an export config file to update these other tiers.
So these settings have to be constantly attended to.  I would rather have some way of setting these based on the tier they are being deployed to.
Still thinking of the best way the mirth connect tool could implement this.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3952
Reporter: stickybandit
Created: 2016-05-03T09:28:28.000-0700

**Comment by thorst** [comment]
This isnt a bad idea, but should be restated as "Set message storage globally, and override at channel level". This way you could set your dev or prod settings, and in 99% of the cases itll work, and in that 1% you override with the settings you need. Ill open a ticket. Im also opening a ticket for more granular storage settings.
