### ISSUE TITLE
HTTP Listener redirects POST to GET when the URL doesn't ends with /

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3937]
Create a channel
Source Connector HTTP Listener with Base Context Path = xxx and port 4657
In a source transformer: logger.info(msg);
Destination Connector anything (use JS Writer for simplicity)
Deploy

Send a POST request to http://localhost:4657/xxx with an XML body
The log in the transformer has an empty body (Content)

Capturing the communications with Wireshark, I noticed the POST gets redirected using GET, and here the HTTP Request Body is lost.

Now send a request to http://localhost:4657/xxx/ (with a / at the end), the redirect disappears, and the Request Body is in the log.

IMO this shouldn't be the expected behavior, also it is very difficult to deb and figure out what was wrong.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4059
Reporter: ppazos
Created: 2016-09-29T11:52:40.000-0700

**Comment by rbeckman-nextgen** [comment]
I'd imagine the client is deciding which method to use after the redirect. Either way the behavior you are seeing is expect, you can read more about it here:
http://www.mirthproject.org/community/forums/showthread.php?p=40999

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-09-29T13:58:38.000-0700

**Comment by rbeckman-nextgen** [comment]
By setting a Base Context Path of "xxx", you are considering that to be your top-level **{color:red}directory{color}*. You can make a request at the directory itself (/xxx/), or you can request any *resource** (/xxx/res1) or other subdirectory (/xxx/dir1/) underneath the directory. But by requesting /xxx you are now making a request for resource "xxx" inside the directory "/". So now you're working at a higher context path than the one you've specified to be the base, which is illegal. Jetty returns a 404 if the resource cannot be found, but it also returns a 302 with a Location header if it does find a corresponding path but it's a directory instead of a resource.

The fact that your client followed up the initial POST request with a GET request to the returned redirection header has nothing at all to do with Mirth Connect. That's just how normal HTTP clients usually handle redirection.

You'll also notice that the HTTP Listener does indeed correctly added the trailing slash to the generated URL: 

!http://i.imgur.com/MeFM6Gr.png!

Imported Comment. Original Details:
Author: narupley
Created: 2016-09-30T08:59:16.000-0700

**Comment by rbeckman-nextgen** [comment]
@Eduardo, the client needs to send POST because a payload should be received by the HTTP Listener Source Connector, if the client doesn't support redirection handling, my case, it is not possible to send a HTTP message to the channel if the path doesn't end with /

@Nick URLs are not physical paths, so it is not pointing to any directory, it is a resource locator and of course a resource identifier. I guess the interpretation would be the path with a trailing slash to be pointing to a collection of resources, but today there is no direct mapping between URLs and directories in the file system, and resources are not physical files. Anyway, the problem is the client not being able to follow the redirect.

I guess the rule of the thumb will be to always define the path with the trailing / when payload is needed on an HTTP Listener. Thanks.

Imported Comment. Original Details:
Author: ppazos
Created: 2016-11-02T10:52:09.000-0700

**Comment by jerchap** [comment]
Is this really as designed?  I don't recall seeing this behavior on other web servers.
