### ISSUE TITLE
Creating a new channel group before the channel panel fully loads deletes ALL other channel groups

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4084]
Preconditions:
* have some channels
* have some of those channels in groups

Steps:
* Log in to MC
* Go to Channels
* **BEFORE** the channel listing displays (like the blank white screen)
*# create a new channel group
*# save the channel group

Post conditions: 
* All your channel groups except the channel group you just created and the default group are gone.
* There is an entry in Events that shows that the user updated channel groups and the removedChannelGroupIds list has all of the channel groups

Workaround:
Admin needs to allow the channel panel to fully load before managing channel groups.

Impact: 
Medium-High (Critical)
An administrator can trigger this inadvertently, some systems with heavy load or lighter system specs take a bit to load the channel panel. No channels or data are lost, but losing ALL of the channel groups requires restoring them from a backup or by hand. Losing ALL of the channel groups makes MC disorganized.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4207
Reporter: jbartels
Created: 2017-08-17T09:07:55.000-0700

**Comment by rbeckman-nextgen** [comment]
This appears related to MIRTH-4030 in that both had a consequence of all but the default group being deleted.

Some general remarks or thoughts on cause + solution:
* The removedChannelGroupIds value seen in Events is referenced several times in MC code with some odd-to-me caching behaviors. Glancing at the code makes me think there is some way that MC could do a "get all from cache" when it should do a "use what I was given"
* channels would not be effected by the issue, they are saved one by one rather than bulk edited from a list page
* MIRTH-4030 had a similar consequence and solved it by blocking harmful operations from being available. This is a tolerable solution but it seems like theres some underlying bug in how channel groups are updated/created/deleted. Hiding a harmful option doesn't really fix the bug.
* if all channel groups are sent back to the server for an update operation, could those objects be sent with a flag indicating if they were created, updated, or deleted? does this make it easier to synchronize client and server information rather than sending separate lists? IOW if I only touched one channel group, just send that one with the relevant operation.

Me and my staff at Zen would be happy to help with triage, reproduction, correction, and testing of this bug. 

This issue did effect a production NextGen customers appliance. One of my teammates logged in to do a deploy and created a group before the channel panel loaded. It then deleted all of the customers groups on that production appliance.

Imported Comment. Original Details:
Author: jbartels
Created: 2017-08-17T09:15:09.000-0700

**Comment by rbeckman-nextgen** [comment]
The main problem with this one is how we're updating groups. The API call updates all groups all at once, where instead maybe it should also have additional endpoints for single CRUD operations. Definitely still on our radar, but this may involve some larger API changes that could be breaking, so we'll hold off until the next version to tackle them.

Imported Comment. Original Details:
Author: narupley
Created: 2018-11-15T09:57:39.000-0800

**Comment by jonbartels** [comment]
Fixed in 4.4 https://github.com/nextgenhealthcare/connect/wiki/4.4.0---What's-New#creating-a-new-channel-group-before-the-channel-panel-fully-loads-deletes-all-other-channel-groups
