### ISSUE TITLE
keystore.type in mirth.properties never used

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4099]
The key keystore.type in mirth.properties is not used, the consequence is that we are not able to use a JKS KeyStore type.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4223
Reporter: bourtala
Created: 2017-10-18T00:42:57.000-0700

**Comment by rbeckman-nextgen** [comment]
See also MIRTH-4282.

Imported Comment. Original Details:
Author: cschultz@chadis.com
Created: 2018-12-12T17:23:58.000-0800

**Comment by cturczynskyj** [comment]
Found a pull request for this that seems relevant.
