### ISSUE TITLE
Connection Log in Administrator prints Timestamps in 12-hour format

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4124]
Connection Log in Administrator prints Timestamps in 12-hour format. Should be 24-hour.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4248
Reporter: agermano
Created: 2018-02-22T14:00:50.000-0800

**Comment by mcgregor182** [comment]
Any roadmap for this issue?? We are on 3.9.1 and the server logs date format is still incorrect.

**Comment by traujots** [comment]
starting 01/27 at 5:46 pm ...

![image](https://user-images.githubusercontent.com/78225930/106305705-4a1fa300-625d-11eb-800a-c4763d2a202c.png)

**Comment by anibal2j** [comment]
Any ideas when this could be addressed? Is it that complex to get it fixed?
