### ISSUE TITLE
Mirth Connect v3.7 Offline License Key Validation

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4244]
Feature request to add offline license key validation. In the event of a prolonged network disaster (fiber line to data center is cut, etc.), there will be no outbound access to the Mirth Connect license server and therefore a disruption in service to a Mirth Connect instance until network connectivity is restored.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4368
Reporter: mpang
Created: 2019-01-17T15:36:22.000-0800

**Comment by rbeckman-nextgen** [comment]
This would also assist in our scenario whereby we are hosting Mirth Connect on a private WAN with no internet access. Providing external access to a licence server is simply not practical. 

Imported Comment. Original Details:
Author: rcoles
Created: 2019-05-10T06:10:24.000-0700

**Comment by rbeckman-nextgen** [comment]
Hi

I see v3.8 has been released which looks like it includes support the the new MySQL drivers, which we are really keen to get, unfortunately until this issue with offline license validation is resolved, we are version locked at v3.6.2!

Do you have any time frame for when this issue will be included in the development cycle?

Cheers

Stu

Imported Comment. Original Details:
Author: shague
Created: 2019-07-03T12:53:24.000-0700

**Comment by rbeckman-nextgen** [comment]
I was on a long flight hoping to do work in my local Connect dev environment and was unable to, because Connect couldn't contact the license server.  This is an unacceptable change to the software.

Imported Comment. Original Details:
Author: justinsk
Created: 2019-09-26T16:19:04.000-0700

**Comment by rbeckman-nextgen** [comment]
I am also concerned about this, and the fact that there is nowhere in the administrator to view the license expiry approaching.  We were given the wrong license expiry by mistake, and the only way  we picked this up was installing an unsupported extension and picking the error in the log file.  I'd feel more comfortable if the validation was done on the server locally, and there was a way to view any approaching expiry other than via the API.

Imported Comment. Original Details:
Author: seaston
Created: 2020-02-28T03:44:10.000-0800

**Comment by rbeckman-nextgen** [comment]
My project also relies on instances deployed long term with limited or absent network comms. We will be unable to upgrade past 3.6.2 without offline validation.

Imported Comment. Original Details:
Author: lro
Created: 2020-03-25T12:23:18.000-0700

**Comment by narupley** [comment]
FYI this has now been added with 3.8! There is a new offline validation route that can be used instead of the online route, so that you no longer need to rely an internet connection if that is an obstacle for you. There are pros and cons, please contact your sales/account rep and we'll help you out!
