### ISSUE TITLE
Template literals ES6 not supported by Mirth Connect 3.7.1

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4292]
With Mirth Connect 3.7.1 you have the ability to use ES6 but not all ES6 features are supported.

I would like to have Template literals supported.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4417
Reporter: mdehoog
Created: 2019-05-28T03:24:30.000-0700

**Comment by rbeckman-nextgen** [comment]
If you e.g. use let, it will be highlighted as an error but nevertheless work when you run the channel..
When you e.g. define a function in a code template by using default values, the IDE does not even let you save the code template as it considers a function like functionName(parameter=DEFAULTVALUE){} as plain wrong.

Imported Comment. Original Details:
Author: mdehoog
Created: 2019-05-30T07:01:04.000-0700

**Comment by rbeckman-nextgen** [comment]
Mirth depends on Rhino as the javascript engine. Many ES6 features are still not supported in ES6 mode.

https://mozilla.github.io/rhino/compat/engines.html

Imported Comment. Original Details:
Author: agermano
Created: 2019-08-06T09:27:35.000-0700

**Comment by tonygermano** [comment]
Template literals are supported in Rhino 1.7.14, which was released on Jan 6, 2022. The most recent mirth version at the time of this post (4.0.1) is still using Rhino 1.7.13.
