### ISSUE TITLE
Save recent message browser searches so that users can easily redo searches

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4322]
Imported Issue. Original Details:
Jira Issue Key: MIRTH-4447
Reporter: narupley
Created: 2019-07-15T08:00:22.000-0700

**Comment by rbeckman-nextgen** [comment]
Duplicate of MIRTH-2737

Imported Comment. Original Details:
Author: brentm
Created: 2019-08-19T11:50:01.000-0700

**Comment by jonbartels** [comment]
Dupe of https://github.com/nextgenhealthcare/connect/issues/2667

**Comment by jonbartels** [comment]
https://github.com/nextgenhealthcare/connect/issues/3615 has a more complete description
