### ISSUE TITLE
Log out the key that is being retrieved from the deprecated MessageHeaders.get method

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4332]
com.mirth.connect.userutil.MessageHeaders#get is deprecated. It logs out a message stating > The get(key) method for retrieving Http headers is deprecated and will soon be removed. Please use getHeader(key) or getHeaderList(key) instead.

These calls are hard to track down for some usages. They would be easier to track down if this method also logged out what key was being requested. 

I am attaching a patch with a suggestion.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4457
Reporter: jbartels
Created: 2019-09-19T13:48:54.000-0700

**Comment by cturczynskyj** [comment]
Found open PR
