### ISSUE TITLE
Server Log / connection Log timestamp in 12hr format without AM/PM

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4344]
In the Administrator Dashboard on the "Server Log" and the "Connection Log" tab the timestamps show in 12-hr format but without the AM/PM designation.
e.g. it shows "2019-10-22 07:22:08.075" for an even that took place at 19:22 (7:22 PM)

Expected behavior:
- show AM/PM in addition to the current timestamp
or
- show timestamps in 24-hr format

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4469
Reporter: mike_pose
Created: 2019-10-22T16:36:19.000-0700

**Comment by anibal2j** [comment]
Is this issue fixed? I notice the tag closed-due-to-inactivity but this issue remains for me under version 3.10.1. I'd like to have this issue fixed please.

**Comment by tonygermano** [comment]
This was a duplicate of https://github.com/nextgenhealthcare/connect/issues/4124, which is still open.
