### ISSUE TITLE
batchComplete sourceMap variable difficult to use

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4358]
This may only require a documentation update, but I think it could be a stumbling block for anyone trying to use the batchComplete boolean value in this typical manner:

`
if ($('batchComplete')) {
  // this will always execute
}
`

Because the value is being pulled from a Map, it must be an Object. A java.lang.Boolean is what is returned, and objects are always truthy, even if they represent "false."

It can be worked around either of the following ways (and possibly others):

`
if ($('batchComplete') == true) { /* ... */ }
if ($('batchComplete').booleanValue()) { /* ... */ }
`

Any other documented sourceMap variables that are boolean values would be affected in the same way.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4483
Reporter: agermano
Created: 2020-03-30T16:16:52.000-0700

**Comment by tonygermano** [comment]
This could be addressed by implementing the suggestion in https://github.com/nextgenhealthcare/connect/issues/4630

**Comment by cturczynskyj** [comment]
For now, we'll update the Batch Processing section in the Connect User guide (updates will show up after the next release). We'll address #4630 separately.

**Comment by tonygermano** [comment]
@cturczynskyj I don't know if this is all-encompasing or not, but it also affects
- `reprocessed` and `replaced` after reprocessing a message
- `binary` in the JavaScript  attachment handler
- `pollComplete` for the File Reader and once https://github.com/nextgenhealthcare/connect/issues/4210 is complete, the Database Reader
