### ISSUE TITLE
Recent version of Apache POI cannot be used with NextGen Connect

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4378]
We use Apache POI with an home mage extension.

The problem is that the most recent version we can use with NextGen Connect is 3.15-beta2 (They are now at 4.1.2).

Both NextGen Connect (4.0) and Apache POI (4.4) use Apache Common Collection 4, but Apache POI uses a class name ListValuedMap that has been introduced in 4.1. See:

http://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/ListValuedMap.html

Would it be possible to upgrade the "Apache Common Collection 4" library, to at least the 4.1 version ? 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4503
Reporter: sbraconnier
Created: 2020-04-09T22:02:00.000-0700

**Comment by cturczynskyj** [comment]
Updated to Apache Commons Collection 4.4 in Connect 3.10.0
