### ISSUE TITLE
Upgrade postgresql driver

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4386]
Mirth Connect is still distributed with the 9.4.1212 driver.  There have been 19 releases since then and at least one of them includes support for `sslmode=prefer` which is a more secure default that still works in any environment (unlike `require` or no SSL configuration)..

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4511
Reporter: ambsw
Created: 2020-05-08T20:13:52.000-0700

**Comment by tonygermano** [comment]
See commit https://github.com/nextgenhealthcare/connect/commit/683d76a95fd36374655bc20f033aa92886dd1e45 for resolution.

**Comment by tonygermano** [comment]
Duplicate of #4501
