### ISSUE TITLE
Memory Leak in SmbFileConnection

### ISSUE THREAD

**Issue by tisoft** [nextgenhealthcare/connect#4387]
The `SmbFileConnection` leaks instances of `jcifs.context.BaseContext`.

1. The constructor of `SmbFileConnection` creates a new instance of `jcifs.context.BaseContext`:
https://github.com/nextgenhealthcare/connect/blob/2f054b85ce8ccca5dacd809a8ac90428e9d7f943/server/src/com/mirth/connect/connectors/file/filesystems/SmbFileConnection.java#L143
2. The `BaseContext` calls its super constructor in `AbstractCIFSContext` and that registers a shutdown hook for the context:
https://github.com/AgNO3/jcifs-ng/blob/59c3c0a89f541966f38dc50dd43d5e2a315e4fa3/src/main/java/jcifs/context/AbstractCIFSContext.java#L44
3. The connection is used, then eventually it is garbage collected. The `BaseContext` is still referenced in the shutdown hook registration and leaks memory.

This has lead to OutOfMemoryErrors in one of our customers environments, where much SMB polling is done. It is a regression, since previous versions did not have this problem.

The `BaseContext` needs to be `close()`d when the `SmbFileConnection` is destroyed.

**Comment by Bruce31797** [comment]
I think I may be having this issue.  I am on 3.9.0, is there a good way to test to see if I am, and is there a way to apply the fix, or does that have to wait on the next update of Mirth?

**Comment by ChristopherSchultz** [comment]
OP says polling SMB can cause OOME. If you want to test, set your memory size to something small and set up rapid polling. Not sure if this is memory exhaustion or file-handle exhaustion. You could artificially limit the number of file handles available to the process using e.g. `ulimit` to try to cause a failure.

You'll probably need a new version, unless you want to manually patch source/rebuild or replace a .class file in a server JAR.

**Comment by ChristopherSchultz** [comment]
@tisoft If the connection should be closed, it shouldn't need to register a shutdown hook as you report. Does your patch remove the shutdown hook by explicitly calling "close"?

**Comment by tisoft** [comment]
Registering the shutdown hook is done by the jcifs library. I haven't found a way to prevent it. Calling the explicit close in the destroy method, unregisters the shutdown hook, and the BaseContext is garbage collected.

The affected mirth from our customer is running without any issues after the change, it would get the OOME at least daily with out it. (thankfully it is only the test system, we didn't upgrade the production version, yet 😅 )

**Comment by cturczynskyj** [comment]
Fixed in 3.9.1.
