### ISSUE TITLE
When importing a channel via the api linefeeds get lost in all scripts

### ISSUE THREAD

**Issue by Loki-Afro** [nextgenhealthcare/connect#4391]
When exporting a channel through the ui and then importing it via the api by using curl for example the line feeds get lost.

Just to make things clear: **that happens to every line of code and breaks a lot of things**

example curl

```
        curl --insecure \
                -X POST \
                -H  "accept: application/json" \
                -H  "Content-Type: application/xml" \
                "https://localhost:8443/api/channels" \
                -d "@$channel_file"
``` 

relevant part in this example:
```xml
....
  <preprocessingScript>// Modify the message variable below to pre process data
return message;</preprocessingScript>
  <postprocessingScript>// This script executes once after a message has been processed
// Responses returned from here will be stored as &quot;Postprocessor&quot; in the response map
return;</postprocessingScript>
....
```

before export:
![before_export](https://user-images.githubusercontent.com/4738445/83041428-c1eb5d00-a040-11ea-829c-9d4bd7307119.png)

after import via api:
![after_import](https://user-images.githubusercontent.com/4738445/83041441-c44db700-a040-11ea-9521-6c71ca9a8c71.png)

This happens because a different deserialization process happens when it comes directly via the api.

Is there any known workaround or fix available?

**Comment by cturczynskyj** [comment]
Try using `--data-binary "@$channel_file"` instead of `-d "@$channel_file"`

**Comment by Loki-Afro** [comment]
@cturczynskyj great! that actually solved the issue, thank you
