### ISSUE TITLE
Code Contribution and commitment to review and respond in a timely manner

### ISSUE THREAD

**Issue by pacmano1** [nextgenhealthcare/connect#4410]
https://github.com/nextgenhealthcare/connect/wiki/Source-Code-Contribution is great.

How about adding a blurb on timing for review, acceptance and/or non-acceptance?

**Comment by brentmoen** [comment]
Just giving an update that we have this on our radar and a new, expanded draft of the guidelines is in progress. cc @narupley

**Comment by brentmoen** [comment]
Expanded and updated source contribution guidelines have been published. Regarding timing, per the guidelines:

> We can't promise a specific timeframe, but the development team will try to at least respond to the PR within a week.
