### ISSUE TITLE
Changing user password and creating user from CLI?

### ISSUE THREAD

**Issue by bluepuma77** [nextgenhealthcare/connect#4413]
Is it possible to change the admin password and/or create a new user with username/password from command line with a tool or via editing a file?

In the [v3.9 user guide](https://www.nextgen.com/-/media/files/nextgen-connect/nextgen-connect-39-user-guide.pdf) I only found the info about the GUI which I would like to avoid due to automation reasons. Besides that I only found the instructions on page 460 to set the password to the default "admin".

```
UPDATE PERSON_PASSWORD SET PASSWORD = 'YzKZIAnbQ5m+3llggrZvNtf5fg69yX7pAplfYg0Dngn /fESH93OktQ==' WHERE PERSON_ID = ?;
```

Is there a method to set a new admin password or create a new user from CLI?

**Comment by pacmano1** [comment]
See page 403 of https://www.nextgen.com/-/media/files/nextgen-connect/nextgen-connect-39-user-guide.pdf

After starting mccommand, type "help".

**Comment by mochsner** [comment]
@pacmano1  is there any way to do that without having the user/password? Trying to recover the admin user & pass in this case.

**Comment by pacmano1** [comment]
https://forums.mirthproject.io/forum/mirth-connect/support/13131-incorrect-username-or-password-after-reboot-3-x maybe?

**Comment by pladesma** [comment]
If you're trying to recover the admin user and password, you can't do that through the CLI. Refer to the documents that pacmano1 linked.
