### ISSUE TITLE
Add Microsoft's SQL Server JDBC driver

### ISSUE THREAD

**Issue by cturczynskyj** [nextgenhealthcare/connect#4424]
The license for Microsoft's official SQL Server JDBC driver has become more open. Since it likely has better support than the JTDS one we should include it in the Core Connect project by default.

To use it, set the following properties in mirth.properties:

```
database = sqlserver
database.url = jdbc:sqlserver://<host>:<port>;databaseName=mirthdb
database.driver = com.microsoft.sqlserver.jdbc.SQLServerDriver
```

**Comment by kirbykn2** [comment]
well this is a nice surprise
