### ISSUE TITLE
3.10.0 unable to install FHIR extension - does not activate after restart

### ISSUE THREAD

**Issue by drcdev** [nextgenhealthcare/connect#4436]
When installing the posted FHIR extension bundle http://downloads.mirthcorp.com/fhir/3.10.0/fhir-3.10.0.b1356.zip, it will install on the latest 3.10.0 build 2566, but does not appear after restarting the server and starting Administrator from the web url to download a new jnlp. This happened with an upgraded instance as well as a fresh install. It has completely brought my development to a standstill because my channels are all invalid without the FHIR data type.

**Comment by drcdev** [comment]
I've confirmed that 3.9.1 works just fine with the same process using:
- fhir-3.9.1.b278.zip (FHIR extension)
- mirthconnect-3.9.1.b263

Do I need a FHIR extension that is a higher build than the 3.10.0 build of Connect?

**Comment by kpalang** [comment]
This flaw appears with every plugin. See #4437

**Comment by drcdev** [comment]
Closing this issue and will watch #4437 instead. Same issue.
