### ISSUE TITLE
3.10.0 does not install extensions

### ISSUE THREAD

**Issue by kpalang** [nextgenhealthcare/connect#4437]
Just upgraded to 3.10.0 and extension installation seems to be broken.

When using the included extension installer, /somewhere/mirthconnect/extensions/pluginname/ receives an empty plugin.xml.

Tried with an upgrade from 3.9.1 and also a fresh install of 3.10.0

Manual installation works, however, when copying archives to /extensions and unpacking them.

**Comment by kpalang** [comment]
Additional information. All tested extensions were downloaded from NextGen website.
Steps to reproduce:
- Download any extension from official NextGen website
- Start NextGen server
- Install extension trough Extensions view from the left hand pane and install button at the bottom of that page.
- Restart server
- Check logs about incompatible extensions
- Check for empty plugin.xml in /mirthconnect/extensions/pluginname/

**Comment by cturczynskyj** [comment]
Thanks for bringing this to our attention, we're looking into it.

**Comment by cturczynskyj** [comment]
Fixed in 3.10.1
