### ISSUE TITLE
3.10.0 Configuration map variables do not work from HTTP Sender settings

### ISSUE THREAD

**Issue by mikeklemens** [nextgenhealthcare/connect#4439]
Recently upgraded from 3.9.1 to 3.10 - noticed that any configuration map variables mentioned in HTTP Sender destination settings (URL or query parameters) no longer work.  Please let me know if I can provide any other additional details needed to reproduce.

Additional server details:
Using OpenJDK 11.0.9.1 on AWS Linux 4.14.209

**Comment by mikeklemens** [comment]
Additional server details:
Using OpenJDK 11.0.9.1 on AWS Linux 4.14.209

**Comment by mikeklemens** [comment]
After some additional details have been discovered, we have now learned this is because these variables have a "-" in their name.  
MCVE = create a new configuration map variable with a "-" in its name and try to reference it in any destination connector settings

**Comment by jonbartels** [comment]
See http://velocity.apache.org/engine/2.0/upgrading.html under "VTL Changes" it says:
> the hypen ( - ) cannot be used in variable names anymore

The MC release notes at https://github.com/nextgenhealthcare/connect/wiki/3.10.0---What's-New . MC 3.10 upgraded Velocity from 1.7 to 2.2 . The link above is for 2.0 and not 2.2, it seems possible there is a config change or workaround between .0 and .2.

There may be a config change that would help https://velocity.apache.org/engine/2.1/configuration.html#parser-configuration says:
> parser.allow_hyphen_in_identifiers = false
>
>   This is a backward compatibility option, false by default, which allows the '-' character inside variable identifiers (available since 2.1). If enabled, be warned that you will have to surround the mathematical minus sign with spaces for it to be correctly interpreted.

This is specifically discussed in https://velocity.apache.org/engine/2.2/upgrading.html


Additional references:
https://issues.apache.org/jira/browse/VELOCITY-901
https://stackoverflow.com/questions/55701168/hyphen-handling-apache-velocity-2-1-is-this-a-bug

**Comment by jonbartels** [comment]
I tried digging into MC code to learn where or if Velocity config options were set to try adding the parser option noted above. I could not find that quickly.

I also wonder if com.mirth.connect.util.ValueReplacerTests would show the problem in 3.10 or not.

**Comment by cturczynskyj** [comment]
We've come across this issue internally as well and have a fix for it coming soon!

**Comment by cturczynskyj** [comment]
Fixed in 3.10.1
