### ISSUE TITLE
MirthWebServer hardcodes Keystore type used for SSLConnector

### ISSUE THREAD

**Issue by ab-20-m** [nextgenhealthcare/connect#4443]
MirthWebServer hardcodes the Keystore type to JCEKS when setting up the SSLConnector. This behavior will be a blocker to implement #3960. BCFIPS only supports BCFKS and PKCS12. In FIPS approved mode, BCFIPS only allows BCFKS.

**Comment by pladesma** [comment]
Closing as duplicate of #4099.
