### ISSUE TITLE
How to query a pacs from Mirth to retrieve data that are associated to images allocated in this pacs?

### ISSUE THREAD

**Issue by Tia95** [nextgenhealthcare/connect#4446]
I am trying to use Mirth to retrieve data associated with images in a pacs, but I am having problems in dealing with the situation. This is the documentation I am using that explains step by step the procedure to follow: I was basically following this documentation https://www.visolve.com/uploads/resources/vicareplus/OpenEMR_DICOM_Interoperability_using_Mirth.pdf which shows the whole procedure to be followed to receive a DICOM message in Mirth, but I don't know how to use dcmsnd and dcmrcv as required in that documentation Also this documentation I am using from the section "dicom messages" onwards: https://aws.amazon.com/it/blogs/big-data/create-a-healthcare-data-hub-with-aws-and-mirth-connect/ This is the site of the pacs that I'm using, a test server from which to retrieve the images: https://www.dicomserver.co.uk/ This is the documentation of dcm4chee which should be used to send the images to Mirth: https://www.dcm4che.org/ So, what I should do is as shown in the first documentation attached, that is to retrieve the data structure present in the image, which is present in the pacs, and load the image in mirth as attached in the documentation. If someone can help me, I thank him.

**Comment by cturczynskyj** [comment]
Hello. For implementation type questions, please try the NextGen Connect [forums](https://forums.mirthproject.io/) or ask in the Connect Slack channel (information about how to join [here](https://forums.mirthproject.io/forum/mirth-connect/support/15720-join-the-mirth-connect-slack-channel))
