### ISSUE TITLE
[BUG] win1064  Install Mirth Connect3.10.1 For AdoptOpenJDK11 Show EXE4J Error!

### ISSUE THREAD

**Issue by runqinshiye** [nextgenhealthcare/connect#4452]
**Describe the bug**
Install mirthconnect-3.10.1.b280-windows-x64.exe  Faild For AdoptOpenJDK11 Show EXE4J Error!

**To Reproduce**
Setup steps (if required). Example:
1. install OpenJDK11U-jdk_x64_windows_hotspot_11.0.10_9.msi In Win10 64
2. Double Click mirthconnect-3.10.1.b280-windows-x64.exe  Error!

**Screenshots**

![1](https://user-images.githubusercontent.com/76540623/105797750-8a67f280-5fcb-11eb-8293-103480d33ede.png)
![2](https://user-images.githubusercontent.com/76540623/105797764-8e941000-5fcb-11eb-95c2-0723e9d0fc31.png)

**Comment by pacmano1** [comment]
Follow what it said.  OpenJDK may not set the appropriate environment variables.  Did you check?

**Comment by pacmano1** [comment]
https://www.youtube.com/watch?v=TVIZ5a5v2WU is video that does a full walk through of the install but with Amazon Coretto JAVA.

**Comment by runqinshiye** [comment]
thanks @p22coyne , I visit this youtube video,after  Install Amazon Corretto OpenJDK11  to default  path is run ok, this problem is sloved!
