### ISSUE TITLE
[Docs] Contribution guidelines are outdated

### ISSUE THREAD

**Issue by gplusplus314** [nextgenhealthcare/connect#4453]
# Description
The contribution guidelines link in `/README.md` goes to https://www.mirthcorp.com/community/wiki/display/mirth/Source+Code+Contribution+Guidelines, which seems to be outdated. The page seems to assume that this project's version/source control system is Subversion (it uses the term "trunk"), but it is using Git and it's a public GitHub repository.

I would expect to see the contribution guidelines to describe any requirements for a pull request.

Thanks. :)

**Comment by jonbartels** [comment]
Related issue https://github.com/nextgenhealthcare/connect/issues/4410

**Comment by brentmoen** [comment]
@gerryhernandez The updated Source Code Contribution guidelines can be found here in the GitHub wiki:

https://github.com/nextgenhealthcare/connect/wiki/Source-Code-Contribution
