### ISSUE TITLE
HL7 Feed - Not being received by Mirth

### ISSUE THREAD

**Issue by targitus** [nextgenhealthcare/connect#4455]
**Describe the bug**
A configuration of Mirth (version 3.6.0) has been moved from one server to another running Mirth (version 3.9.1). HL7 data feeds in fine to a SQL Server database on the old server but nothing is being received on the new server.

All configuration files, channels has been moved over but remain idle after setting up on the new server. 

From the HL7 feed the follow message is shown:
![error_hl7](https://user-images.githubusercontent.com/78452261/106676342-b6afe000-6584-11eb-8e60-df1f65f016b5.jpg)

Old server:
![image](https://user-images.githubusercontent.com/78452261/106676453-ee1e8c80-6584-11eb-930d-bfebae5dea96.png)

New server:
![image](https://user-images.githubusercontent.com/78452261/106676485-01c9f300-6585-11eb-962c-1ec3912d8b4b.png)

**To Reproduce**
Setup steps (if required). Example:
1. Setup table in database with this schema
2. Add rows '...'

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows Server 2016 Datacenter
 - Java Distribution/Version: Java 8 Update 281, Jave SE Development Kit 15.0.1
 - Connect Version 3.9.1

**Workaround(s)**
Are there one or more workarounds for this issue currently? No

**Additional context**

**Comment by jonbartels** [comment]
This may be a specific channel or config issue rather than a bug.

Consider making a post at https://forums.mirthproject.io/ or asking in Slack to help determine if its a genuine bug or a misconfig. The contents of `mirth.log` will be helpful to debug the issue.

**Comment by targitus** [comment]
Hi there,
Thanks for you reply. Yes this may not be a bug - I wasnt sure what to file it under.
Here is the mirth.log from the new server where the data is not flowing in:
[https://www.dropbox.com/s/jaexllxsex6zrs8/mirth.log?dl=1](url)

**Comment by targitus** [comment]
[https://www.dropbox.com/s/sxyvmilvmyck88h/i4j_log_mirth-administrator-launcher_8672769066017829987.log?dl=1](url)

**Comment by cturczynskyj** [comment]
I don't see any obvious errors in your server log. It's most likely a configuration issue with your server being unreachable or the IP changing or something like that. I'd also encourage you to request assistance on our [forums](https://forums.mirthproject.io/) or our [Slack channel](https://forums.mirthproject.io/forum/mirth-connect/support/15720-join-the-mirth-connect-slack-channel).
