### ISSUE TITLE
[IDEA] Allow Proxy-specific credentials for HTTP Sender

### ISSUE THREAD

**Issue by ab-20-m** [nextgenhealthcare/connect#4456]
**Is your feature request related to a problem? Please describe.**
Currently, the HTTP Sender scopes authentication credentials to ANY_REALM. In the case where an authenticating forward proxy sits between Mirth and an authenticating HTTP server, Mirth will most likely not be able to communicate with the target system. Additionally, it is possible the credentials for the authenticating proxy server will be leaked in the case where a user selects  preemptive authentication and the target server does not require authentication. It would be useful if separate credentials for the forward proxy can be defined in addition to the target server.

**Describe your use case**
Consider the use case where a Mirth instance must communicate through a forward proxy to an HTTP server that requires authentication. The credentials to authenticate to the proxy server will likely not be the same as the credentials to authenticate the the target HTTP server.

**Describe the solution you'd like**
Allow separate credentials to be defined for the authenticating proxy and scope limited to just that proxy server for those credentials.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pladesma** [comment]
Duplicates #5970
