### ISSUE TITLE
Can any one provide me sample channel to read/write messages from AZURE BUS Queues

### ISSUE THREAD

**Issue by rajshah074** [nextgenhealthcare/connect#4460]
I have to read messages from Azure Bus Queue but no idea how to start.

Can any help me with any jar that is required to read data from azure Bus queue.

**Comment by MichaelLeeHobbs** [comment]
Vote to close. This is not a place to request support. To request support please visit [https://forums.mirthproject.io](https://forums.mirthproject.io/) or [Mirth Connect Slack](https://mirthconnect.herokuapp.com/) or [StackOverFlow Mirth Connect](https://stackoverflow.com/questions/tagged/mirth)

**Comment by rajshah074** [comment]
tq
