### ISSUE TITLE
[BUG] Map variable in channel writer should be referenced differently

### ISSUE THREAD

**Issue by mikeklemens** [nextgenhealthcare/connect#4468]
**Is your feature request related to a problem? Please describe.**
It is not very user intuitive when you are able to drag and drop a "Destination Mapping variable" from the list into the "Map Variable" section for a Channel Writer destination.  Dragging and dropping a variable here will automatically add ${FooBar} but this "Map Variable" section only works with variables being written as FooBar. 

**Describe your use case**
I need this feature so it is more logical for new users to more easily map variables across channels.

**Describe the solution you'd like**
I would like either 1) the dragging and dropping of destination mapping variables to automatically put the variable in the correct format needed or 2) for the Map Variable section to support variables in the ${FooBar} format. 

**Describe alternatives you've considered**
The only other alternative solution that I can think of is for there to be better documentation of exactly what the format should look like in each section - maybe the mouse over tool tip could provide that example.

**Additional context**
This solution should be consistent across the application, in any other areas where this type of inconsistency exists.

**Comment by cturczynskyj** [comment]
We tried this locally and were unable to reproduce the behavior you have indicated. If you could give exact reproduction steps, that would help. 

This is what we did:
1. Create a channel listener that does nothing. Copy the channel ID.
2. Create a channel writer
3. Configure the channel writer with a transformer that maps the channel ID of the channel listener to a channel map variable.
4. On the channel writer destination, drag and drop that variable into the "Channel Id" field. This adds the text `${channel_id}` in the text box and switches the drop down to <Map Variable>.
5. Deploy both channels
6. Send a test message to the channel writer
7. Observe the channel listener receives the message

**Comment by pacmano1** [comment]
Actually I see @mikeklemens also.

@cturczynskyj  create a $c var in the transformer of the channel writer.    Velocity syntax will not pass it downstream if you add it Message Metadata.  3.9.1 for me.   Just the var name works like mentioned in the initial post.

@mikeklemens - I stopped passing metadata that way a long time ago - all channel to channel message pass JSON around.  Just 2 cents to take or leave.   I find it easier to inject message programmatically that way.

**Comment by cturczynskyj** [comment]
Thanks for clarifying. We re-tested, using the Message Metadata table this time and also saw the behavior.

**Comment by tonygermano** [comment]
Related Discussion https://github.com/nextgenhealthcare/connect/discussions/4535
