### ISSUE TITLE
[IDEA] Add "PENDING" to the message status selectors for the message view

### ISSUE THREAD

**Issue by jonbartels** [nextgenhealthcare/connect#4469]
I had a channel which did message recovery on every deployment. The logs showed an error in a specific destination  in a response transformer. I wanted to remove these messages from the UI selectively but there was not an easy way to search for them.

I was able to find them by selecting search parameters for my destination and "has error" like this:
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/7669292/110037830-f3e6c980-7d0c-11eb-97c0-a5e9d1944e20.png">

Note that the message statuses are in `PENDING`. 

If I could just search for 'PENDING' directly as with SENT/RECEIVED/ERRORED/etc I could find them quickly.

*ALL* message statuses shown in the list view should be searchable. Add "PENDING" and any other missing message statuses to the status search list.

**Comment by cturczynskyj** [comment]
This seems like a legitimate issue and it looks like it should be relatively simple to implement, pretty much just adding another checkbox for Pending. We did a little looking and Pending is the only missing status currently in com.mirth.connect.donkey.model.message.Status:

`RECEIVED('R'), FILTERED('F'), TRANSFORMED('T'), SENT('S'), QUEUED('Q'), ERROR('E'), PENDING('P');`

I'll create an internal issue for it. Thanks.
