### ISSUE TITLE
[BUG] "this" is broken

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [nextgenhealthcare/connect#4476]
**Describe the bug**
A clear and concise description of what the bug is. Is this consistently reproducible? Yes

**To Reproduce**
Setup steps (if required). Example:
1. Create a code template
```
function logGlobal(k) {
	const foundConsole = typeof console !== 'undefined' && typeof console.log !== 'undefined'
	if (foundConsole) console.log(k + ' = ' + this[k])
	else logger.info(k + ' = ' + this[k])
}
```
2. Create channel with raw data types and source transformer of 
```
var a = 1
b = 2

logGlobal('a')  // expect log message a = 1 - actual a = undefined
logGlobal('b') // expect log message b = 2 - actual b = 2
```

Running the same test in chrome produces the expected results.

**Expected behavior**
See above

**Actual behavior**
See above

**Environment (please complete the following information):**
 - Container Mirth 3.10.0

**Workaround(s)**
Are there one or more workarounds for this issue currently?

```
logGlobal.bind(this)
```

**Additional context**

**Comment by tonygermano** [comment]
There is nothing wrong with `this` and the workaround won't fix it. The transformer script is wrapped in a function, so declaring a variable with `var` specifically says that you do not want the variable to be assigned to the global object (which is what `this` is referring to in your example.)

The solution would be in your transformer code to not declare a with `var` if you expect it to be global.

**Comment by cturczynskyj** [comment]
What @tonygermano says makes sense. It seems like an issue of scope.

**Comment by MichaelLeeHobbs** [comment]
Sorry, I though I had edited the issue and removed work around. It is an issue of scope but it is still an issue. Currently it works counter intuitive to all other JS runners that I am aware of. `Your` code should all run in the same scope unless you specifically do something to cause it to not run in the same scope or it is explicitly stated that this chunk of code will run in a different scope. Scope is one of the most complex parts of JS so it would be best to not make it more complex.

**Comment by tonygermano** [comment]
I agree that the different scopes in which user code runs should be documented in the user guide, but that's a different request than this issue.
