### ISSUE TITLE
[BUG] Source Inbound Template stored once per message

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [nextgenhealthcare/connect#4480]
**Describe the bug**
A clear and concise description of what the bug is. Is this consistently reproducible?

I'm not sure if this is a bug but in Mirth 3.7.0 the Source Inbound Template is stored once per message. According to the guide ` Both templates can be used in the filter / transformer for easy reference and drag-and-drop capabilities, but only the outbound template has any effect on message processing.` The source inbound template has no other use other than to assist the user as a `reference and drag-and-drop capabilities`. I'm not sure why this would need to be stored once per message and because it is it can very easily bloat a database. In my case I had put in a very large source inbound template. 

7 days of messages 137K
With template table d_mc111 total size: 24GB
After removing template, reprocessing all messages and doing a vacuum full d_mc111 - total size: 3.6GB

**Environment (please complete the following information):**
 - 3.7.0

**Comment by cturczynskyj** [comment]
We tried to reproduce this locally, creating an HTTP listener with an HL7 inbound template, then sent it a message using a separate HTTP sender. We checked the MC# tables and could not find the inbound template reproduced/stored. Can you attach an example of a channel that causes the behavior you are talking about?

**Comment by MichaelLeeHobbs** [comment]
Cannot not duplicate in Mirth 3.10.1
