### ISSUE TITLE
[IDEA] Update Postgres JDBC driver to 42.2.1+ to support scram-sha-256 auth type

### ISSUE THREAD

**Issue by pladesma** [nextgenhealthcare/connect#4501]
**Is your feature request related to a problem? Please describe.**
A customer was unable to start up Connect with Postgres 13 and scram-sha-256 auth type. Recommendation for now is to downgrade auth to md5. Users shouldn't have to downgrade DB auth in order to use Connect. The first version of Postgres to support scram-sha-256 is version 10 and the current version is 13.

**Describe the solution you'd like**
Update the Postgres JDBC driver so that Connect is able to use Postgres DBs configured for scram-sha-256 auth type

**Comment by ab-20-m** [comment]
This issue can close out https://github.com/nextgenhealthcare/connect/issues/4461 once 3.11.0 releases.
