### ISSUE TITLE
[Docs] Administrator Launcher 1.2 released without any Docs, News etc.

### ISSUE THREAD

**Issue by gaensler** [nextgenhealthcare/connect#4516]
Yesterday my Mirth Connect Administrator Launcher prompted, that Version 1.2 is ready for Download, but i couldn't find any documentation, news or similar about it on Github, NextGen.com or the Forums.

Download and Installation was successful, but what are the new features, bugfixes etc. of Version 1.2?

**Comment by narupley** [comment]
Sorry about that, our website team is still in the process of updating the downloads page.

Version 1.2.0 of the launcher addresses #4379.
