### ISSUE TITLE
Security warning on launch

### ISSUE THREAD

**Issue by sfmans** [nextgenhealthcare/connect#4523]
Recently updated on 3.11.0

On every launch from the Connect Administrator Launcher I get the following warning:

![image](https://user-images.githubusercontent.com/83290451/116251245-63ee5a80-a766-11eb-831f-98c5020051ff.png)

**Comment by narupley** [comment]
Upgrade to version 1.2.0 of the Administrator Launcher and that will be resolved. We added a newly renewed certificate that we use for code signing.

https://www.nextgen.com/products-and-services/nextgen-connect-integration-engine-downloads
