### ISSUE TITLE
Channel History Plugin - Can't see time (see screenshot)

### ISSUE THREAD

**Issue by pacmano1** [nextgenhealthcare/connect#4527]
![image](https://user-images.githubusercontent.com/44065187/116483097-10563c80-a84c-11eb-86c4-8b61fcbdb709.png)

**Comment by tonygermano** [comment]
@pacmano1  Did you install Tahoma font yet? Lots of things are truncated like that on Linux when you don't have Tahoma.

see https://github.com/nextgenhealthcare/connect/issues/2129 (workaround no longer works)
https://github.com/nextgenhealthcare/connect/issues/2582 (@cturczynskyj  this one should probably be reopened)
https://github.com/nextgenhealthcare/connect/issues/4019 (I mentioned how I copied the font from my Windows install in a dualboot system)

**Comment by tonygermano** [comment]
The Wine project also has a free version that is supposed to have the same metrics, but I'm pretty sure it doesn't look as nice as the Microsoft one. You can get it from here https://github.com/wine-mirror/wine/tree/master/fonts or probably from a local Wine installation if you have one.

**Comment by pacmano1** [comment]
Yes, copied and installed Tahoma from a windows machine.  Thanks @tonygermano .  

This does address this problem - but having that bar re-sizable would probably still be helpful - it is the only product I use that has this artifact. 

LOL, and I can now hardly see the font,  getting old
