### ISSUE TITLE
[BUG] Velocity variables in HTTP Listener response headers

### ISSUE THREAD

**Issue by shamilnn** [nextgenhealthcare/connect#4534]
A sample code to set the HashMap with the custom HTTP headers:

```
var HTTPResponseHeader = new java.util.HashMap();
HTTPResponseHeader.put('Access-Control-Allow-Origin', '*');
HTTPResponseHeader.put('Access-Control-Allow-Methods', 'GET,POST,PUT');
channelMap.put('HTTPResponseHeader', HTTPResponseHeader);
```

When HTTP Listener source connector _Use Map_ is set to ${HTTPResponseHeader} nothing is happening, i.e., no additional HTTP headers are included.
At the same time _Response Content Type_ and _Response Status Code_ do accept velocity variables also set using channelMap.

**Environment (please complete the following information):**
 - Connect Version: 3.11.0

**Workaround(s)**
The obvious workaround is to use "Use Table" and specify HTTP headers directly there. Velocity variables work in that case.
But there is no way to dynamically delete HTTP headers.

**Comment by tonygermano** [comment]
try using the bare key `HTTPResponseHeader` instead of wrapping it as a velocity token

**Comment by shamilnn** [comment]
This is a bit counterintuitive. To be consistent, the HTTP source connector has to use velocity tokens everywhere and/or a channel's map key.

**Comment by tonygermano** [comment]
Did that work for you, then?

I think it is because velocity is a template language. Anything replaced by velocity is going to be a string value, and the string value of the entire Map wouldn't be very useful in accessing the keys and values of the Map.

I did open this suggestion, which I think could help clear up some of the confusion https://github.com/nextgenhealthcare/connect/discussions/4535

**Comment by pladesma** [comment]
It sounds like this isn't a defect and the feature is working as expected. It does seem that the UI is potentially confusing to users, so I suggest looking at the discussion topic that @tonygermano linked and comment and/or upvote it if it's relevant to you.
