### ISSUE TITLE
Mirth Connect Administrator Restarting Itself 

### ISSUE THREAD

**Issue by joelnewnham** [nextgenhealthcare/connect#4536]
Our Mirth Connect Administrator restarted itself during the night and some of the channels didn't redeploy.

Our version of Mirth is Mirth Connect Server 3.5.1 with Java version: 1.8.0_181

This message was in the Mirth Connect logs
INFO  2021-05-06 01:16:55,920 [Shutdown Hook Thread] com.mirth.connect.server.Mirth: shutting down mirth due to normal request

and the following were in the Events in MCA
Error executing Postprocessor script from channel

followed by

Started role "polling"

Is it normal for MCA to restart itself?

**Comment by jonbartels** [comment]
No its not normal. Starting a "Discussion" may be a better venue to solve your problem https://github.com/nextgenhealthcare/connect/discussions . 

It seems unlikely that this is a bug or issue in the code. Rather something at the OS level (OOMKiller? Another user?) is shutting down the MC daemon.

**Comment by tonygermano** [comment]
FYI, Mirth Connect Administrator is the GUI client. It is not normal for the Server to restart itself.

**Comment by cturczynskyj** [comment]
I agree with @jonbartels that this seems more like a question or that you are seeking support and the better place is to use the [Github Discussions](https://github.com/nextgenhealthcare/connect/discussions) area.

**Comment by tonygermano** [comment]
@cturczynskyj It appears that you can convert an issue to a discussion rather than closing it
https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion
