### ISSUE TITLE
[BUG] Message Tree for HL7 v 2.5.1 does not show friendly names for fields

### ISSUE THREAD

**Issue by pacmano1** [nextgenhealthcare/connect#4538]
Message Tree for HL7v2 2.5.1 does not show friendly names for fields

To reproduce:
Add a 2.5.1 message to a message template in a transformer. 
Go to the message tree, friendly names are not displayed.

e.g. a 2.4 message will show this:

![image](https://user-images.githubusercontent.com/44065187/118007777-10594080-b312-11eb-865d-63ca0c6406b7.png)

2.5.1 shows:

![image](https://user-images.githubusercontent.com/44065187/118007862-2961f180-b312-11eb-9d86-576850a6c257.png)

**Comment by pladesma** [comment]
@pacmano1 What version of Connect did you encounter this defect in? Did it work correctly in previous versions? Also, it would be helpful if you could provide us with an example HL7v2 2.5.1 message that we can test with. Thanks!

**Comment by pacmano1** [comment]
Use your own message generator (aka mirth's message generator that is part of the core pack) for a message.  

Dunno on versions other than 3.9.1

**Comment by cturczynskyj** [comment]
Thanks for the info. Tested back a few versions and it occurs at least as far back as 3.6.2 if not older.

**Comment by tonygermano** [comment]
It's because mirth-vocab.jar in client-lib only goes up to 2.5
https://github.com/nextgenhealthcare/connect/tree/3.11.0/generator/reference
