### ISSUE TITLE
[Enhancement] Unnecessary Indexes using more storage than needed

### ISSUE THREAD

**Issue by billmask** [nextgenhealthcare/connect#4551]
**Describe the bug**
There is no wrong behavior of the application but there are unnecessary indexes in the databases XMl files.
This slow down the DMLs and does not help with queries but main problem is storage usage.

**To Reproduce**
Setup steps (if required). Example:
1. Setup table in database with this schema
2. That's all. Duplicated indexes will be there.

1. Install application
2. Check indexes in the database.

**Expected behavior**
Less indexes (I am preparing a Pull Request) to speed up DMLs and save storage.

**Actual behavior**
Duplicated indexes in place.

**Screenshots**
I will detail it in the PR.

**Environment (please complete the following information):**
- Oracle
- PostgreSQL
- MySQL
- SQL Server

**Workaround(s)**
Not needed, but anyone can run the alter tables to drop the indexes.

**Additional context**
none needed

**Comment by billmask** [comment]
As said above, the PR:
https://github.com/nextgenhealthcare/connect/pull/4565

**Comment by tonygermano** [comment]
Not sure that I would classify this as a bug, but removing the unnecessary indexes makes sense to me.

**Comment by billmask** [comment]
I confess I also don't think it is a bug. I can edit the issue and set differently. I can create a new issue and relate it to the PR.
The code owners can say what they think it is better.

**Comment by billmask** [comment]
MOVED TO https://github.com/nextgenhealthcare/connect/issues/4605
