### ISSUE TITLE
[NEED] Java Web Start (jnlp) obsolete

### ISSUE THREAD

**Issue by sreev** [nextgenhealthcare/connect#4556]
**Is your feature request related to a problem? Please describe.**
The Administrator is launched as Java Web Start (jnlp file).  JWS is deprecated in Java 9 and made obsolete in Java 11 & above.

https://en.wikipedia.org/wiki/Java_Web_Start

**Describe your use case**
How is the Administrator supported going forward ?

**Describe the solution you'd like**
What are alternative solutions ?

**Describe alternatives you've considered**
None.

**Additional context**
https://openwebstart.com/

**Comment by tonygermano** [comment]
You asked this 10 hours ago in slack, and I told you that the Administrator Launcher does not use Java Web Start.

You can get it from the NextGen downloads page:

https://www.nextgen.com/products-and-services/nextgen-connect-integration-engine-downloads

Also, as you pointed out, OpenWebStart exists, though I'm not sure how many people have attempted to use it on newer JVMs with Connect or what the results were.

**Comment by sreev** [comment]
I downloaded installer. It still connects to /webstart and downloads jnlp artifacts before showing up the login screen.

<img width="805" alt="Screen Shot 2021-05-20 at 17 59 17" src="https://user-images.githubusercontent.com/441385/119067048-0ed4eb80-b996-11eb-9388-714874ee21be.png">

**Comment by tonygermano** [comment]
It reads the jnlp file, but it does not use Java Web Start to do so.

**Comment by MichaelLeeHobbs** [comment]
@tonygermano is correct this should be closed.

**Comment by pladesma** [comment]
Tony and Michael are correct. Closing this issue.

**Comment by SebStaeubert** [comment]
Is it possible to use OpenWebstart (and how? there is an "IlligalStateException: zip file closed") or is it possible to start the Administrator Launcher with User rights?

**Comment by pacmano1** [comment]
I wasn't able to get open webstart to work.   I don't understand the your second question though.

**Comment by SebStaeubert** [comment]
Unfortunately it is a Windows use case in a educational setting where the accounts of the computer pool have no administrative rights for installing software. So it is not (easily) possible to install the "Administrator Launcher".
[OpenWebstart](https://openwebstart.com/) would be an alternative, because recent JDKs (OpenJDK 17 is available in our setting) have no webstart support anymore. And OWS doesn't necessarily need administrator right and can be installed in the user space.
THX in advance.
