### ISSUE TITLE
[NEED] Java 11 (LTS) and Java 17 (LTS)

### ISSUE THREAD

**Issue by sreev** [nextgenhealthcare/connect#4557]
**Is your feature request related to a problem? Please describe.**
Current java versions supported are java 8 and java 9.
Upgrade to Java 11 (LTS) and Java 17 (LTS).

https://en.wikipedia.org/wiki/Java_version_history

**Describe your use case**
Java 8 and 9 are in extended support period.
Java 11 (LTS) is the prevailing current version in use.

**Describe the solution you'd like**
Java 17 (LTS) is going to be out in Sep 21. It is right about the time, to start looking into adopting it.
Also, take this opportunity to define how to align Connect releases with Java releases, from now on.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by tonygermano** [comment]
There are instructions in the user guide for running on Java 9+. The official docker container runs on java 11. I would suggest asking further questions as  a Discussion before opening more issues https://github.com/nextgenhealthcare/connect/discussions

**Comment by MichaelLeeHobbs** [comment]
@tonygermano is correct this should be closed.

**Comment by sreev** [comment]
https://github.com/nextgenhealthcare/connect/discussions/4559

**Comment by pladesma** [comment]
Closing as per the comments above.
