### ISSUE TITLE
[BUG] A17 MSH segment not parsing the MessageType correctly

### ISSUE THREAD

**Issue by mcswaip1** [nextgenhealthcare/connect#4573]
**Describe the bug**
When the MSH segment is parsed the MessageType = "ADT^A17" and the MessageEvent = ""

**To Reproduce**
Setup steps (if required). Example:
1. Create a channel and send it the following HL7
> MSH|~\&|||||20210527018000||ADT^A17|sbb03|9|2.3
EVN||^1
PID|||112233||Mouse^Minnie^M^^Ms||198006121514|M||||||||||22599
PV1||1|TSANU1^TSA100^A^TSACampus^^^Enterprise^TSADepartment||||||||||||||||1007|||||||||||||||||||||||||20210527018000
PID|||223344||Duck^Donald^D^^Ms||198006121516|M||||||||||22222
PV1||1|TSANU1^TSA100^B^TSACampus^^^Enterprise^TSADepartment||||||||||||||||1009|||||||||||||||||||||||||20210527015000
2. Look in the Mappings for the message in the Dashboard
3. You will see MessageType = "ADT^A17" and MessageEvent = ""

**Expected behavior**
MessageType="ADT" MessageEvent="A17"

**Actual behavior**
MessageType = "ADT^A17" and MessageEvent = ""

**Screenshots**
![image](https://user-images.githubusercontent.com/20447369/120024358-0c3d4c00-bfbd-11eb-99b2-30d0240facfb.png)

**Environment (please complete the following information):**
 - OS: Linux (CentOS)
 - Java Distribution/Version OpenJDK 11
 - Connect Version 3.8.0

**Workaround(s)**
None that I can figure out.

**Comment by tippenring** [comment]
This doesn't look like a bug. Your MSH.2 is missing the ^ delimiter. Therefore ^ is not recognized as a delimiter when parsing the MSH segment.
