### ISSUE TITLE
[BUG] long password not well supported in the welcome form 

### ISSUE THREAD

**Issue by AndreaPravato** [nextgenhealthcare/connect#4594]
**Describe the bug**
A long user password is not well supported in "welcome to Mirth Connect form"

**To Reproduce**
1. New Mirth Connect installation
2. insert long password for the user
3. click on another form field
4. the button to proceed with password setting gets hidden; form fields are cut to the right

**Expected behavior**
User should be able to set a long password or a text-size limit should be clearly set in the form field. 
Form fields should be fully visible and buttons actionable

**Screenshots**
![MirthIssue](https://user-images.githubusercontent.com/4329975/121892686-5b091680-cd1d-11eb-834d-40137ce343fd.png)

**Environment (please complete the following information):**
 - OS: windows server 2012 R2
 - Java Distribution/Version: openjdk 15
 - Connect Version: 3.11.0

**Workaround(s)**
change password from user settings

**Comment by cturczynskyj** [comment]
Tested in MacOS using Java 1.8 and this behavior does not occur. It's possible that it's a bug with the version of Java/OS you are using. I'm curious if anyone else has run into this behavior and what version of Java and what OS they are running.

**Comment by AndreaPravato** [comment]
Thanks. Sorry for late reply. Maybe it helps that
