### ISSUE TITLE
Java 16 compatibility issue with the DatabaseConnection/Factory class using .executeCachedQuery

### ISSUE THREAD

**Issue by LeviLong01** [nextgenhealthcare/connect#4602]
**Describe the bug**

- Issue: Error is thrown when calling .executeCachedQuery(stmt) within the DatabaseConnectionFactory. This only happens with Java 16 (not distribution specific). This does not happen in Java 14 or 15.

- Error: java.lang.IllegalAccessError: superclass access check failed: class com.mirth.connect.server.userutil.MirthCachedRowSet (in unnamed module @0x10af9340) cannot access class com.sun.rowset.CachedRowSetImpl (in module java.sql.rowset) because module java.sql.rowset does not export com.sun.rowset to unnamed module @0x10af9340

**To Reproduce**
Setup steps (if required). Example:
1. Create a channel to query a database.
2. Set the `Source` tab as `JavaScript Reader` with a schedule type of `Time` and set `Poll Once on Start` to `Yes`, in the JavaScript put `return "POLL"`
2. In the Destinations tab create a destination as a JavaScript writer and create a connection to a database with the `DatabaseConnectionFactory.createDatabaseConnection` method.
3. Create a simple SELECT statement.
4. Execute it by doing `.executeCachedQuery(stmt)` where `stmt` is the variable with your SELECT statement

1. Deploy channel

**Expected behavior**
Successfully perform the SELECT query and store the results in a variable called `result`

**Actual behavior**
Error thrown with the error I put up at the top

**Screenshots**
![Java Issue](https://user-images.githubusercontent.com/7453310/122441926-4619c680-cf5b-11eb-9806-41c9bf057673.PNG)

**Environment (please complete the following information):**
 - OS: CentOS 8, Windows 10
 - Java Distribution/Version: Zulu OpenJDK 16, OpenJDK 16
 - Connect Version: 3.10.1, 3.11.0
 - Database: PostgreSQL, MSSQL

**Workaround(s)**
Are there one or more workarounds for this issue currently? Downgrade Java to 15, or possibly just reference the Java libraries directly outside of the Mirth library

**Additional context**

**Comment by cturczynskyj** [comment]
I'm assuming you've done this, but just checking, have you imported the extra vmoptions from `/docs/mcservice-java9+.vmoptions`? Basically, append the contents of that file to the contents of your `mcserver.vmoptions` or `mcservice.vmoptions` (whichever fits how you are running your Connect server).

**Comment by LeviLong01** [comment]
@cturczynskyj Yea I've done that. The Mirth service won't start without that being done, if running Java 9 or greater. And this is only an error on Java 16. 14 and 15 are fine.

**Comment by ab-20-m** [comment]
This is probably caused by [JEP 396:Strongly Encapsulate JDK Internals by Default](https://openjdk.java.net/jeps/396). The behavior for the --illegal-access option changed from permit to deny as the default. Try adding --illegal-access=permit to the .vmoptions and see if things still go boom.

**Comment by LeviLong01** [comment]
@ab-20-m that solved it. Thank you!

**Comment by jonbartels** [comment]
Can/should this bug remain open for a change to MC internals to not depend on sealed classes?

Setting JVM options is a great workaround but not needing the workaround seems ideal.

**Comment by LeviLong01** [comment]
I agree @jonbartels 

I was gonna create a discussion in the "Feature/Enhancement Ideas" section to still have some awareness of this problem.

Is that the best place to report bugs that would require some work from Mirth? 

I'm also not sure if Java 17 will still have this considering it's the next LTS release, so it could possibly not have this problem. But a note on Java 16 should still be documented somewhere for Mirth and Java support.

I can leave this open along with a discussion in the other section.

**Comment by jonbartels** [comment]
There was previous discussion in this issue which was ported from the old JIRA https://github.com/nextgenhealthcare/connect/issues/1810

Gerald Bortis and Wayne Huang were heavy hitters for Mirth Connect but that ticket is from 2011 and last updated in 2014. The described issue and a means to move the dependency have been known for a while.

**Comment by Fdawgs** [comment]
`--illegal-access=permit` no longer works with Java 17: https://www.oracle.com/java/technologies/javase/17-relnote-issues.html

**Comment by mooncat69** [comment]
I solved this by adding this to my .vmoptions file: `--add-opens=java.sql.rowset/com.sun.rowset=ALL-UNNAMED`

**Comment by NicholasIoanJones** [comment]
None of the above suggestions work for Java 18 - is the only option to downgrade to Java 15?
Is there a fix being worked on or is Mirth locking in to Java < 16?

**Comment by Fdawgs** [comment]
> None of the above suggestions work for Java 18 - is the only option to downgrade to Java 15? Is there a fix being worked on or is Mirth locking in to Java < 16?

The below works with Java 17, using Mirth 3.12.0:

```
--add-modules=java.sql.rowset
--add-exports=java.base/com.sun.crypto.provider=ALL-UNNAMED
--add-exports=java.base/sun.security.provider=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.math=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/java.security=ALL-UNNAMED
--add-opens=java.base/java.security.cert=ALL-UNNAMED
--add-opens=java.base/java.text=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/sun.security.pkcs=ALL-UNNAMED
--add-opens=java.base/sun.security.rsa=ALL-UNNAMED
--add-opens=java.base/sun.security.x509=ALL-UNNAMED
--add-opens=java.desktop/java.awt=ALL-UNNAMED
--add-opens=java.desktop/java.awt.color=ALL-UNNAMED
--add-opens=java.desktop/java.awt.font=ALL-UNNAMED
--add-opens=java.sql.rowset/com.sun.rowset=ALL-UNNAMED
--add-opens=java.xml/com.sun.org.apache.xalan.internal.xsltc.trax=ALL-UNNAMED
```

As Java 18 isn't an LTS version you probably don't want to be using that in production anyway.

**Comment by NicholasIoanJones** [comment]
@Fdawgs Thank you for the prompt reply. I'm using Mirth 4.0.0 - do you think the same will work with Java 17?

**Comment by Fdawgs** [comment]
@NicholasIoanJones hopefully. The Mirth Connect instance on my org's test server is on 4.0.0 and is running with Java 17 using the previously mentioned launcher options.

**Comment by NicholasIoanJones** [comment]
@Fdawgs Thanks. After a short fight with JDK versions on my mac I can confirm that Mirth 4.0.0 / Java 17 / Options above work perfectly. Thank you for your help, I was getting frustrated there!
