### ISSUE TITLE
Source Code How to use Fhir extension

### ISSUE THREAD

**Issue by MrTianFei** [nextgenhealthcare/connect#4614]
I have downloaded the Mirth Connect source code and the fhir-3.11.0.b1424.zip plugin. Where should I put the FHIR plugin in the Connect source code and how do I make the FHIR plugin work

**Comment by pacmano1** [comment]
I don't think the install has changed.  It is installed like other extensions.  Use the mirth administrator to install it. See https://m.youtube.com/watch?v=YzgCEHoC87w

You also mentioned "source code".  Are you actually compiling mirth connect source code or just trying to run mirth?

**Comment by MrTianFei** [comment]
I am compiling mirth connect source code,I wanted to add the Fhir plugin, but have some  problem 

![question](https://user-images.githubusercontent.com/86398277/123363671-96210a80-d5a5-11eb-957a-9958bc7016a7.gif)

**Comment by jonbartels** [comment]
You don't need to compile Mirth Connect from source. You can download prebuilt binaries at https://www.nextgen.com/products-and-services/NextGen-Connect-Integration-Engine-Downloads . This should then let you follow the video that @pacmano1 posted to install the extension.

**Comment by MrTianFei** [comment]
Yes, I know this way works, but I am a programmer, I want to know the source code how to install the extension

**Comment by jonbartels** [comment]
I don't know the solution but I have a few ideas that might help:

1. What error messages are shown in your console or `mirth.log` ? Can you please post those as code snippets? It is sometimes hard to read errors in a GIF
2. Does the extension install when using the pre-built MC? I understand you want it to load in your development copy but checking in a regular build will make sure there is not a corrupt file or something like that.
3. Compare the files in your MC install directory after installing the plugin, then again after restarting MC. When a plugin is installed the ZIP is unpacked into the MC lib directory. If restarting MC from your IDE deletes this directory or removes other plugin configs that could be your problem.

**Comment by cturczynskyj** [comment]
The FHIR extension is closed source so you won't be able to gain access to its source by importing it into Eclipse. If you just want to know how to build and run Connect in Eclipse with the FHIR extension installed, we can work on adding that to the [wiki documentation](https://github.com/nextgenhealthcare/connect/wiki/Clone-Build-and-Run-from-Source).

**Comment by MrTianFei** [comment]
Yes, I really need the information. Thank you very much for everyone's help

**Comment by cturczynskyj** [comment]
Added a new [wiki page](https://github.com/nextgenhealthcare/connect/wiki/Build-With-Closed-Source-Extensions) on how to do this.

**Comment by MrTianFei** [comment]
Thanks a lot
