### ISSUE TITLE
[BUG] On FHIR Builder, cannot find "focus" field for "MessageHeader" resource in R4 version

### ISSUE THREAD

**Issue by Mo-la-machette** [nextgenhealthcare/connect#4634]
**Describe the bug**
On FHIR Builder, I cannot find "focus" field for "MessageHeader" resource in R4 version. I can find it for older version of FHIR.

**To Reproduce**
Install FHIR Extension

1. Create a new code template
2. Select type : 'FHIR Resource Builder'
3. Select FHIR version: 'R4'
4. Select Resource : 'MessageHeader'

**Expected behavior**
Expected to have field 'focus' of type 'Reference[]' in the builder panel for Resource MessageHeader

**Actual behavior**
field focus doesn't appear in the builder 

**Screenshots**
![Capture d’écran_2021-07-16_16-43-09](https://user-images.githubusercontent.com/18366684/125966576-02e5618d-e28d-4b89-95f2-8b977cc34bf2.png)

**Environment (please complete the following information):**
 - OS: RedHat 8.4 GA
 - Java Distribution/Version : OpenJDK 11
 - Connect Version :  3.11.0

**Workaround(s)**

**Additional context**

**Comment by pladesma** [comment]
We tested this locally, and `focus` appears as a field for `MessageHeader` in `R4`. The fields are in a different order, so you may just need to scroll down to find it.
![image](https://user-images.githubusercontent.com/4097281/126007211-ff8f57cf-0b0a-4c46-b342-e0314f940f36.png)

**Comment by Mo-la-machette** [comment]
Hello,

Indeed, I succeed to display the "focus" field after relsoving some display problems on my virtual machine

Sorry for opening a wrong ticket and thanks !
