### ISSUE TITLE
[BUG] Channel Step `sequenceNumber` is not respected when `POST`ing

### ISSUE THREAD

**Issue by prestontw** [nextgenhealthcare/connect#4635]
**Describe the bug**
When posting a channel through the channels API, steps' `sequenceNumber` has lower priority than the type of step it is, leading to a misordering of steps.

**To Reproduce**
Setup steps (if required). Small reproducing repo is available [here](https://github.com/prestontw/mirth-sequencenumber-repro). The following steps will use this repo.
Example:
1. Install docker-compose, jq, Mirth Connect Administrator, and git
2. `git clone https://github.com/prestontw/mirth-sequencenumber-repro.git`
3. Within the repository, run `docker compose up -d` to start up the Mirth server within a docker container
4. Launch the Mirth Administrator (on localhost:8443)

1. Import the channel `example_hl7_to_fhir_channel.xml`
2. Note that the intermediate javascript log step is the second step (has sequence number `1`)
<img width="1152" alt="Screen Shot 2021-07-16 at 5 09 03 PM" src="https://user-images.githubusercontent.com/11056277/126010262-ea48fd20-de7b-41e1-ab90-4980ec7e2a26.png">

3. Copy the channel locally using `save-channel.sh` in the directory
4. Note that, after formatting, there is no difference between this file and the previous version.
5. Note that the intermediate logging step has `sequenceNumber: 1`:
  ```
            "com.mirth.connect.plugins.javascriptstep.JavaScriptStep": [
            {
              "@version": "3.11.0",
              "name": "Intermediate js logging step",
              "sequenceNumber": 1,
  ```
6. Delete the channel
<img width="1152" alt="Screen Shot 2021-07-16 at 5 11 22 PM" src="https://user-images.githubusercontent.com/11056277/126010306-a9986947-92a1-48ed-a25d-de97cf2ed732.png">

7. Import the channel to Mirth over the channel API with `import-channel.sh`
8. Refresh, open the channel, view the Source transformation
9. Note that the intermediate logging step is now a much later step
<img width="1152" alt="Screen Shot 2021-07-16 at 5 14 48 PM" src="https://user-images.githubusercontent.com/11056277/126010318-d6c0c8e9-4310-4aa4-a487-bd76e1df5e6c.png">

**Expected behavior**
After importing with `import-channel.sh`, the intermediate logging step should retain its original position in the transformation.

**Actual behavior**
After importing with `import-channel.sh`, the intermediate logging step is in a new position. Notably, it is now grouped with the other javascript step.

**Screenshots**
(pasted inline above)

**Environment (please complete the following information):**
 - Host OS: MacOS
 - Docker image: custom image with FHIR extension based on `FROM nextgenhealthcare/connect:3.11`
 - Connect Version 3.11

**Workaround(s)**
Convert all of the steps to a common format, such as JS. This removes a lot of the benefits of the Mirth GUI, though.

**Additional Context**
Reproducing repo is available at https://github.com/prestontw/mirth-sequencenumber-repro

**Comment by cturczynskyj** [comment]
Tested this locally and it looks like this only happens when exporting the channel as JSON. For the time being if you stick to XML it should work properly, keeping your transformer steps in the correct order.

**Comment by prestontw** [comment]
@cturczynskyj is there a way to import and export the channel in xml format over the API? From the examples I've seen, it's only been using json.

**Comment by cturczynskyj** [comment]
@prestontw Yes, you can set the accept parameter to "application/xml". In your example code you are using curl so you can add the curl parameter `-H  "accept: application/xml"`.

**Comment by prestontw** [comment]
@cturczynskyj thank you. I have made changes in the repo above (https://github.com/prestontw/mirth-sequencenumber-repro/commit/1e0f64171519b2f795bda2d1c85f885498207b28) to reflect your hint. However, now I'm seeing that the `Scripts` of the channel are now losing their line endings, leading the `return message` of the preprocessing script being part of the comment, leading to preprocessing not actually returning the message:
![image](https://user-images.githubusercontent.com/11056277/126232822-97018f0a-508c-482e-9df5-a8d7e3812f75.png)

I can work around this by not having a comment on the first line, but it would lead to issues if I have a comment anywhere at all. It also removes the newlines in general JS steps, leading to hard-to-edit code: 
![image](https://user-images.githubusercontent.com/11056277/126232980-7915067e-8f7b-449e-86d7-1abf15da7f79.png)

Exporting the channels in JSON was a workaround for XML not respecting newlines.

Do you have any recommendations? I'm on MacOS 11.4. The curious thing to me is that importing the channel through the GUI respects line endings. What is the difference between using the API and using the GUI? I know the GUI is implemented over the API, so it's unexpected to me that there would be a difference.

**Comment by prestontw** [comment]
It looks like it's an issue exporting the channel over the api: https://github.com/prestontw/mirth-sequencenumber-repro/blob/1e0f64171519b2f795bda2d1c85f885498207b28/saved-channel.xml#L1585 doesn't have a newline separating the comment from the `return message;`.

**Comment by cturczynskyj** [comment]
This may be how Curl is handling the POST body. I see you are using `-d` but I think you may also need to use `$` before your body as well, like `$'your_xml_body'`, to include new lines in the XML. Alternatively, you may be able to just use `--data-binary` instead of `-d` which should send the information exactly with no processing.

**Comment by prestontw** [comment]
> Alternatively, you may be able to just use `--data-binary` instead of `-d` which should send the information exactly with no processing.

This worked, thank you so much @cturczynskyj ! This fixes the issue I had with exporting/importing over xml. Should we leave this issue open since the issue with importing over JSON still remains?

**Comment by cturczynskyj** [comment]
Glad you got it working with XML 👍 

And, yes, we'll leave this issue open for now.

**Comment by prestontw** [comment]
@cturczynskyj one other note is that I can reproduce this with XML format too---if I reorder the steps, it imports them in that order rather than the order specified by `sequenceNumber`. If you're curious, I can try to copy to the linked repo, though it should be pretty quick to reproduce in any repo.
