### ISSUE TITLE
Question about removing a selected set of messages

### ISSUE THREAD

**Issue by harrietkramer** [nextgenhealthcare/connect#4665]
Is there a quick way to delete a bunch of queued messages in mirth without removing all messages?  I want to only remove queued messages in a group that I have searched for.  If so how is this done?

**Comment by jonbartels** [comment]
Use "Remove Results" after searching for the queued messages you want to remove. "Remove Results" operates on the same search terms used in the message view when finding which messages to remove.

<img width="473" alt="image" src="https://user-images.githubusercontent.com/7669292/128354544-c25188db-8837-4be6-a8ec-9e69362065c4.png">

**Comment by tonygermano** [comment]
Also, consider asking questions like this in a Discussions post, not an issue. This question is answered in the User Guide, so not really an issue.

https://github.com/nextgenhealthcare/connect/discussions
