### ISSUE TITLE
Channels switch to the wrong context

### ISSUE THREAD

**Issue by VolodymyrSheremet** [nextgenhealthcare/connect#4675]
The attached archive contains a log of work and two channels: LMS Download and LMS Import

The dependence of the LMS Import channel on the LMS Download channel is set so that they are deployed in the correct order.
The channels are synchronized through the java.util.concurrent.locks.ReentrantLock object, which deploys the LMS Download channel.
If, when the LMS Download channel receives a new file, the time limit between the download of two files of the same package has been exceeded, the LMS Download channel waits for at least one session of the LMS Import channel to be executed.

From the log you can see that the LMS Download channel is working in the thread with ID 57, and the LMS Import in the thread with ID 79.
However, starting from the timestamp 2021-08-11 13: 27: 51.697, for some reason, the LMS Download channel and the LMS Import channel have changed their context: the LMS Download channel started working in the thread with ID 79, and the LMS Import channel in the thread with ID 57.

This results in a fatal error.

To Reproduce you can use given channels with corrected timeouts. 

Windows 10 64-bit
OpenJDK Runtime Environment Zulu11.41+23-CA (build 11.0.8+10-LTS)
Mirth Connect 3.9.1
[ThreadProblem.zip](https://github.com/nextgenhealthcare/connect/files/6968068/ThreadProblem.zip)

**Comment by tonygermano** [comment]
JavaScript Tasks are executed using a thread pool (you can see this in the thread name in your logs.) I don't know that there is an expected guarantee that the pre-processor script and the post-processor script will by executed by the same thread.

Maybe you could use an Semaphore with a single permit instead of the ReentrantLock? This wouldn't be dependent on thread ownership of the lock, and it doesn't look like you acquire the lock more than once in the same thread without releasing it first, which I think it the main feature of the ReentrantLock.

I think all you would need to do is switch your `lock` and `unlock` calls to `acquire` and `release` calls instead.

**Comment by VolodymyrSheremet** [comment]
I agree, in this particular case, the semaphore should work as expected. However, this is rather a special case.
In most cases, full-fledged synchronization is required using ReentrantLock, and if different scripts of the same channel are not executed in the same thread, then such synchronization will be impossible in principle.

**Comment by jonbartels** [comment]
I apologize for challenging the frame of the question - is there another or a better way to synchronize the operations across two channels that still meets the use case?

If  this frame challenge is acceptable to you @VolodymyrSheremet I'll reply in more detail. If you want to focus on the existing thread coordination strategy I will focus on that.

**Comment by VolodymyrSheremet** [comment]
Mmm... In this particular case, we completely changed the approach and implemented everything within one channel without synchronization. Therefore, this particular issue can be considered closed.

However, the question of the synchronization problem in Mirth remains open. I repeat: with the existing implementation, using ReentrantLock to synchronize the operation of two channels is impossible due to the fact that the same script code can "change" the thread.

Perhaps developers should implement channel properties that will tell whether they need to "bind" code execution to a thread or not.

For example: _bind channel code to thread_

**Comment by tonygermano** [comment]
> In most cases, full-fledged synchronization is required using ReentrantLock, and if different scripts of the same channel are not executed in the same thread, then such synchronization will be impossible in principle.

I'm actually not used to seeing people try to synchronize channels in this way. More often I would see one channel being used to trigger the next and queues used to hold messages until they are ready to process. Can you give an example of a scenario where a ReentrantLock would be required?

**Comment by pladesma** [comment]
It sounds like @VolodymyrSheremet found an alternative way to implement their channels, so we're going to close this issue. If you would like to further discuss this issue, please create a Discussion topic.
