### ISSUE TITLE
Update of dcm4che to Version 5

### ISSUE THREAD

**Issue by lampi87** [nextgenhealthcare/connect#4687]
Hello everyone,

As dcm4che2 is deprecated is there any plan to switch to dcm4che 5?
Or is it already supported?

Best regards,
Alex

**Comment by evulhotdog** [comment]
Would love to hear what the plan is, if any, being that dcm4che has been EOL for quite some time.

**Comment by cturczynskyj** [comment]
Closing this. Please create a topic in the discussion area to discuss with other users or rewrite this using one of the issue templates (ex: "Feature Request").

**Comment by tonygermano** [comment]
@cturczynskyj You can do this instead of closing.

![image](https://user-images.githubusercontent.com/39179051/131408988-73b90c77-0c50-4717-aacc-a7bb53c51587.png)
