### ISSUE TITLE
Ways to send message to channel and return message ID

### ISSUE THREAD

**Issue by tom08zehn** [nextgenhealthcare/connect#4738]
Can I replace `VMRouter.routeMessage()` by something else that returns the message ID instead of a response object?

I think I could do the same as here: https://github.com/nextgenhealthcare/connect/blob/development/server/src/com/mirth/connect/server/userutil/VMRouter.java#L104

... and then get the message ID:
https://github.com/nextgenhealthcare/connect/blob/924d1860bcb5f01fe125edcfae183d7410e61976/donkey/src/main/java/com/mirth/connect/donkey/server/channel/DispatchResult.java#L42

Or is there an easier way?

_Originally posted by @tom08zehn in https://github.com/nextgenhealthcare/connect/discussions/4589#discussioncomment-1346157_

**Comment by tonygermano** [comment]
Could you return the messageId as part of the Response?

If not, then what you suggested sounds like it should work, and I don't believe there is an easier way.

**Comment by tom08zehn** [comment]
Nope, the `VMRouter` only returns the plain `Response` object that just contains status, message and maybe an error. I think it's not possible to "inject" the message ID into the response... But yes, it would be nice if the response would already contain the message ID...

My idea works, let me share my code:

```js
// Convert payload to RawMessage and inject sourceMap variables
var rm = new RawMessage(payload);
// In the channel, you can check it as follows: if($s("foo") == "bar")
var sm = Maps.map().add("foo", "bar");
rm.setSourceMap(sm);

// Forward message to channel and get response and message ID
// var res = router.routeMessageByChannelId(destinationChannelId, rm);
// ^^ As router (VMRouter) only returns a response object but not the message ID
//    we need to rebuild what routeMessageByChannelId(String channelId, RawMessage rawMessage) is doing, see:
// https://github.com/nextgenhealthcare/connect/blob/master/server/src/com/mirth/connect/server/userutil/VMRouter.java#L104
// https://github.com/nextgenhealthcare/connect/blob/master/donkey/src/main/java/com/mirth/connect/donkey/server/channel/DispatchResult.java#L42
var messageId;
try {
	// Convert raw message
	var raw = rm.isBinary() == true ? rm.getRawBytes() : rm.getRawData(); // attention: native Java Boolean
	var rawMessage = new com.mirth.connect.donkey.model.message.RawMessage(raw, rm.getDestinationMetaDataIds(), rm.getSourceMap());
	// Dispatch message to channel
	var dispatchResult = com.mirth.connect.server.controllers.ControllerFactory.getFactory().createEngineController().dispatchRawMessage(destinationChannelId, rawMessage, false, true);
	if(dispatchResult == null) throw new Error("Couldn't dispatch message");
	// Get response
	var selectedResponse = dispatchResult.getSelectedResponse();
	if(selectedResponse == null) throw new Error("Couldn't get response");
	var responseStatus_ = new com.mirth.connect.userutil.Response(selectedResponse).getStatus();
	if(responseStatus_ != com.mirth.connect.userutil.Status.SENT) throw new Error("Sending message failed, status: " + responseStatus_);
	// Get message ID
	messageId = dispatchResult.getMessageId();
	if(!messageId) throw new Error("No message ID returned");
} catch(err) {
	throw new Error("Error routing message to channel ID " + destinationChannelId + ": " + err.message);
}
logger.debug(messageId);
```

**Comment by pacmano1** [comment]
I think @tonygermano meant constructing it a part of the response itself.  For example just making it an element of a JSON blob that is returned from the downstream channel.  Ie in the retuned message.  But point noted.
