### ISSUE TITLE
[IDEA] Migrate from iText to PDFBox based solution for PDF generation

### ISSUE THREAD

**Issue by cturczynskyj** [nextgenhealthcare/connect#4739]
iText version 2.1.7 is old (2009) and cannot be updated because newer versions use an incompatible license (AGPL vs MPL). To continue moving with the times and to a compatible library that is still supported we should move to a PDFBox based solution (PDFBox is already an included library).

1. The solution should be compatible with the current PDF generation functionality.
2. RTF functionality will remain unchanged for the time being and continue using iText

Solution chosen: openhtmltopdf

**Comment by tonygermano** [comment]
Does this mean that PDFBox will finally be upgraded to 2.0.x? Ultimately, I think that is a good thing (3.0.0 is currently in pre-release,) but this could potentially cause a lot of broken user code that depends on the 1.8.x branch. Most of the questions in the forums and slack that end up with a recommendation to use an isolatedClassLoader have to do with PDFBox, and people have worked around the version differences or missing library modules in a number of different ways. You might want to put a big warning in the release notes about this.

**Comment by tonygermano** [comment]
To answer my own question post-release, it appears that PDFBox has been upgraded to pdfbox-2.0.24.

**Comment by cturczynskyj** [comment]
> To answer my own question post-release, it appears that PDFBox has been upgraded to pdfbox-2.0.24.

Yup, sorry, forgot to reply earlier. It has been updated and we added a blurb about it in the [3.12.0 upgrade guide](https://github.com/nextgenhealthcare/connect/wiki/3.12.0---Upgrade-Guide#pdfbox-library-update).
