### ISSUE TITLE
[BUG] Cannot Login With admin User After Initial Installation 

### ISSUE THREAD

**Issue by WDC** [nextgenhealthcare/connect#4879]
**Describe the bug**
I am installing Mirth Connect 3.12.0 on CentOS 8 Stream with OpenJDK 11.0.13 (JRE 18.9) and cannot login with any usernames or passwords. I have tried `admin/admin`, I have successfully reset the password using the CLI, I have reinstalled from scratch, and I have updated the parameters in `conf/mirth.properties`, but I still receive the "Invalid login credentials" error on the HTTPS web-based endpoint.

I amusing `changepw 1 "newpassword"` to change the password using CLI, and it replies with "User "admin" password updated." However, that new password does not work in the web portal, but does work when I modify `conf/mirth-cli-config.properties`. 

**To Reproduce**
1. Install Mirth Connect with MySQL.
2. Start the systemd package.
3. Attempt to login with admin/admin
4. See error message.

**Expected behavior**
The default login of username: admin and password: admin to let me into the web configuration portal.

**Actual behavior**
"Invalid login credentials" error message on the login screen.

**Screenshots**
<img width="818" alt="image" src="https://user-images.githubusercontent.com/1221004/144098973-23b81ef3-580f-4a10-8a57-0dd2647f23d6.png">

Thank you!

**Comment by jonbartels** [comment]
You can see how the `admin/admin` account is initialized at https://github.com/nextgenhealthcare/connect/blob/9a6228fb3c01b270578b8fda2e5fc015d1764dce/server/dbconf/mysql/mysql-database.sql#L96 . How does that compare to what you see in `person` and `person_password` after making your changes?

When you modify `conf/mirth.properties` what properties are you altering specifically? DB connection strings? Something else?

**Comment by WDC** [comment]
Prior to changing the password:
```
MariaDB [mirth]> select * from PERSON_PASSWORD;
+-----------+------------------------------------------------------------+---------------------+
| PERSON_ID | PASSWORD                                                   | PASSWORD_DATE       |
+-----------+------------------------------------------------------------+---------------------+
|         1 | NJND6z7rZvATS/2wBCKrshAU6vcyQScJj8DUkspJJUplqaxWzd7pUg==  | 2021-11-30 17:40:19
```
Then updating the password with the CLI:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/1221004/144118539-c02c519f-5b6c-4bfa-9cf9-b7d1848ea20b.png">
And now the database again:
```
MariaDB [mirth]> select * from PERSON_PASSWORD;
+-----------+------------------------------------------------------------+---------------------+
| PERSON_ID | PASSWORD                                                   | PASSWORD_DATE       |
+-----------+------------------------------------------------------------+---------------------+
|         1 | obbmFzCuNShUuIf1M4ZYDP3loVTEeVd76B7zmxvXJFXR4bSv9cPk3Q==
 | 2021-11-30 19:56:26 |
+-----------+------------------------------------------------------------+---------------------+
```

So the CLI tool definitely is updating the correct user. When I exit `mccommand` and then immediately go back into it, I get a Java error because of incorrect password, which is expected. As such I go to `./conf/mirth-cli-config.properties` and make it look like this:
```
address=https://localhost:8443
user=admin
password=jonbartels
version=0.0.0
```

And now when using `mccommand` I am able to login!

Back to the web GUI, however, I get the same red banner when using `admin` and `jonbartels`.

Could this have to do with me accessing the system from a subdomain? I am using `https://some.kinda.subdomain.com:8443` to access the web portal. It would appear that authenticating against `https://127.0.0.1:8443` is no problem.

If that is the case, how would I go about changing the URI of the installation?

Thank you for your reply!

**Comment by WDC** [comment]
And a followup, I am only editing `server.url` to `https://some.kinda.subdomain.com:8443` and the username and password in the `./conf/mirth-cli-config.properties`. Other than that and the MySQL database connection parameters, the file is all-original to the latest `.tar` from the website.

**Comment by WDC** [comment]
I tried the same install process on an x86_64 server, and everything worked as expected.
