### ISSUE TITLE
[BUG] Transformer batch from csv  add [] to variable

### ISSUE THREAD

**Issue by postheimer** [nextgenhealthcare/connect#4881]
Hello 

i have a channel , he read a csv on process batch 

each row/column is mapper to a variable from iterator , all work goo but 

when i write the final flat file , all my variable have a [ ]   ? 

i'm in mirth connect 3.10.0  

i have tried a regex but no luck

**Comment by pacmano1** [comment]
Post your code and or the full channel.   We can't guess what you wrote.

**Comment by postheimer** [comment]
[COVID.zip](https://github.com/nextgenhealthcare/connect/files/7635505/COVID.zip)
here is the channel template
