### ISSUE TITLE
[BUG] Configuration Map Variable surrounded with dashes does not work in ${} replacement

### ISSUE THREAD

**Issue by michaelmarcuccio** [nextgenhealthcare/connect#4961]
Configuration Map Variable surrounded with dashes does not work in ${} replacement

**To Reproduce**
1. Add configuration map variable named: --test--
2. Try to use the variable in channel with ${--test--} replacement functionality such as in a file reader path.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Distribution/Version: OpenJDK 11
 - Connect Version: 3.12

**Comment by MichaelLeeHobbs** [comment]
I'd not call this a bug. Mirth uses a template engine and - is likely not valid as part of a variable name where as it is valid as part of a key name in a map variable. You have basically stepped into a gray area between two libraries so to speak.

**Comment by ab-20-m** [comment]
When Mirth upgraded to Velocity 2.2, the library by default disallowed hyphens in variable names. See Issue:[4439](https://github.com/nextgenhealthcare/connect/issues/4439)

Mirth 3.10.1 set the [Velocity Parser Configuration Property](https://velocity.apache.org/engine/2.3/configuration.html#parser-configuration) to allow hyphens in variable names, but Velocity may still not allow double hyphens (--) or starting a variable with hyphens.

**Comment by tonygermano** [comment]
It should still work to do `${maps.get('--test--')}`. If I recall correctly, you have to do this if the map key contains a `.`, too.

**Comment by michaelmarcuccio** [comment]
As there is this alternative ${maps.get('--test--')} I am closing this issue.
