### ISSUE TITLE
[IDEA] Make implementing custom plugins more developer-friendly

### ISSUE THREAD

**Issue by pladesma** [nextgenhealthcare/connect#4988]
**Is your feature request related to a problem? Please describe.**
When implementing a custom ServicePlugin, you must always override getObjectsForSwaggerExamples() even if you don't need the method to do anything. The interface should provide a default implementation, so that this isn't necessary. This also helps prevent breaking 3rd party plugins when a user upgrades Connect.

Also, ServicePlugin and MultiFactorAuthenticationPlugin lack proper Javadocs to explain the intended usage of their methods.

**Additional context**
PRs already exist to address these issues.

**Comment by MichaelLeeHobbs** [comment]
#17
