### ISSUE TITLE
[IDEA] Channel and Connector Edit Lock or Warning

### ISSUE THREAD

**Issue by thorst** [nextgenhealthcare/connect#5056]
We have a lot of channels and a lot of developers. This can cause collisions where two developers are trying to modify the same channel at the same time. They don't realize there is a potential issue until after they have made a bunch of changes and they go to save and realize someone saved a newer copy than what they had loaded. They should then copy any changes they have out, try to determine who else was making changes, and see if there are conflicts with their pending changes, refresh their config, reinstate changes, and then save and deploy.

This situation is completely avoidable though if we were to have a feature that would say "Hey, User A is also editing this channel". User B would then be able to ask User A to get out so they could make their changes. It could be assumed when you enter a channel that you are editing it, OR you could have the user explicitly press a lock icon to give them write access.

Using more channel reader/writers to minimize destination editing conflicts helps so that most of the code lies in an independent channel, however, this doing this feels against the grain as to what would be most efficient. There is more parsing the transaction, more saving states to a database, more overall processing that is only done in an effort to stymie people from stomping on each other. Instead it seems we should have all the destinations in one channel (where practical) but that leads to more developers hitting one specific channel.

Even more granularity may be desired. For example, if you have locking at the connector level, there would be less collisions, but then you would need to consider top level changes that aren't at the connector level. 

I have another ticket about saving and deploying at the connector level, and locking at the connector level, in combination with those features would be the most ideal world to ensure many developers can manage one instance of Connect at once.

​​​​​​​Link to other request: https://github.com/nextgenhealthcare/connect/issues/5055

**Comment by MichaelLeeHobbs** [comment]
Don't edit code in mirth. Use and IDE with git. Push your changes before copying the code over or syncing it. There's a tool out there to sync Mirth code. This wont completely prevent the issue you are talking about but should get really close if not all but eliminate it. Beside this there are a lot of benefits to using an IDE. A good IDE will catch many common errors that the Mirth editor wont. I recommend WebStorm over VSCode. WebStorm out of the box is very solid. You can make VSCode nearly as good as WebStorm but it take a lot of work to configure and get all the plugin just right. Then you need to make sure everyone on your team is on the same page.

**Comment by thorst** [comment]
I use ace editor on an internal website that pulls connector code and saves it back. I can then check in code to a repo with the user even having to think about it. I also have the ability to see who else is using my tool for that same connector to warn them.

However, I'd rather leverage locking/warning via a built in API. That would be to setChannellock and getChannelLock methods so that way my tool could know if a user is using the mirth ide, and an ide user could know someone is using my website.

Sometimes it is easier to use mirth directly for something, and unless I want to rewrite the entire ide (I don't want to) then there is always this potential for collision. 

I will check out the sync. Thanks!

**Comment by MichaelLeeHobbs** [comment]
@thorst anyway you willing to share the ace editor mirth site? Assuming you built the editor have it take a hash of the code before you make changes. Then before it commits the changes have it take another hash of the current code. If they differ then you have your warning. Next step would be to have it track the full code. Then before commit have it run a diff on the current state. Then it could show you the changes and give you options to merge. Doing a simple hash/alert should be easy, however tracking full state and handling diff/merge would be a lot of work.

Edit:
Another option would be to create a table called locks. Have your editor create a lock entry when your editing. Make sure to include a `expires_at` and `user` column. The  `expires_at`  is now + 3 minutes. As long as the user is actively making changes then the lock remains valid and ie updated by the editor. If the user 'A' walks away then the lock will expire in 3 minutes and is eligible to be overwritten by another user. When 'A' returns if their lock has not been overwritten then they can continue where they left off and their lock will be refreshed. If there lock was overwritten then their changes should be discarded.

**Comment by thorst** [comment]
I would like to make it more open source yes, but I don't expect I'll have time to accomplish that anytime soon.

I have diffing on my old site (built around cloverleaf) but the issue still comes from users in the ide at the same time as my site.

I either need official api's, or I need to write a plug in. I'm not opposed to writing a plug in, but not sure what it's even capable of, or if I'd have to modify the ide directly.

Are there any good resources for plugin writers?

**Comment by MichaelLeeHobbs** [comment]
https://github.com/kpalang/mirth-sample-plugin On the Mirth Slack there is a active plugin-development channel.

**Comment by jonbartels** [comment]
The megathread at https://github.com/nextgenhealthcare/connect/discussions/4689 may be relevant in that some strategies to manage source and concurrent development are discussed there. There is no magic solution... yet. 

Related issues with similar use cases, both relatively ancient:
https://github.com/nextgenhealthcare/connect/issues/1256
https://github.com/nextgenhealthcare/connect/issues/1177

**Comment by cturczynskyj** [comment]
Interesting use case. Would it be good enough to know, when attempting to save a channel, that changes have been made since you opened the channel for editing. Like a dialog popup saying something like:

"<user_name> has made changes to this channel since you started editing and your changes will overwrite theirs. Are you sure you want to save your changes?"
