### ISSUE TITLE
[Bug/Question] Disabled channel's last modified date keep getting updated.

### ISSUE THREAD

**Issue by aungktun** [nextgenhealthcare/connect#5057]
We are using MC 3.5.0.8232 as locally hosted on widows server with ms sql.
Noticed that disabled and not deployed channels' last modified date columns keep showing with current datetime stamp in Channels view.
What is causing it to update in MC?

**Comment by MichaelLeeHobbs** [comment]
Code template changes that the channel depends on.

**Comment by pacmano1** [comment]
Answer above
