### ISSUE TITLE
I'd like to connect to a message broker or queue system

### ISSUE THREAD

**Issue by Salles-FA** [nextgenhealthcare/connect#5081]
Hi,

I'm using Mirth Connect as an option to connect a multi-channel health care device with some message broker or queue system. This is an academic project for a post graduation I'm in.

I'm searching and struggling to find some documentation regarding this. I only found an old article explaining how to connect to an Azure Queue Store, but it isn't working with the current version of Mirth Connect.

- https://www.spheregen.com/mirth-connect-with-microsoft-azure-queue-storage/

Could you please give me any tips?

It could be to AWS SQS, Kafka, RabbitMQ... Or any other one.

I thank you in advance,
Fábio

**Comment by pacmano1** [comment]
If you are new to Mirth, I would use a broker that supports REST calls, that's standard functionality in Mirth.
