### ISSUE TITLE
Add Login Notification Requiring User to Accept the Notification

### ISSUE THREAD

**Issue by lmillergithub** [nextgenhealthcare/connect#5107]
One such security requirement is needed. It should be possible that the we can require users to accept a notification each time the user logs in. The user should not be able to proceed into the application until they accept the usage conditions listed in the notification.

**Comment by jonbartels** [comment]
I'm curious about this feature. Is this like a login message to the effect of "You're being monitored by $COMPANY. All activity here must conform to employee handbook page 48." or a NextGen EULA?

**Comment by lmillergithub** [comment]
The login notification is user defined. It is also an option so you don't have to activate it unless your company requires it.
