### ISSUE TITLE
[BUG] KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory

### ISSUE THREAD

**Issue by cseeger-harris** [nextgenhealthcare/connect#5121]
**Describe the Bug**
After re-deploying with the container version 4.0.0, we are getting an error on startup relating to the keystore file we created.  Not sure if there is a new update on how we should be importing the files (or something we are doing wrong), but it seems appropriate based on the 4.0.0 user guide.  We have validated that the keystore contains two values, one "mirthconnect" that we created and one "encryption", created by the application automatically on startup

Stack dump:
```
Importing keystore /opt/connect/appdata/file.p12 to /opt/connect/appdata/keystore.jks...
ERROR 2022-03-30 18:02:38,725 [Main Server Thread] com.mirth.connect.server.MirthWebServer: Could not load web app
java.lang.IllegalStateException: KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory. (Use org.eclipse.jetty.util.ssl.SslContextFactory$Server or org.eclipse.jetty.util.ssl.SslContextFactory$Client instead)
	at org.eclipse.jetty.util.ssl.SslContextFactory.newSniX509ExtendedKeyManager(SslContextFactory.java:1289)
	at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:1271)
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:373)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:244)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:321)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at com.mirth.connect.server.MirthWebServer.startup(MirthWebServer.java:366)
	at com.mirth.connect.server.Mirth.startWebServer(Mirth.java:466)
	at com.mirth.connect.server.Mirth.startup(Mirth.java:345)
	at com.mirth.connect.server.Mirth.run(Mirth.java:162)
WARN  2022-03-30 18:02:39,253 [Main Server Thread] com.mirth.connect.server.Mirth: Could not start web server.
```

**To Reproduce**
Setup to reproduce:
1. New instance of mirth running with no prior keystore file.
2. Use OpenSSL to import a private key and certificate file into a p12 (pkcs12) format file.
3. Import newly created p12 file into keystore.jks with alias "mirthconnect"
4. KeyStore should contain only one entry that this point
```
mirth@mirth-connect-******:/opt/connect/appdata$ keytool -list -v -keystore keystore.jks Enter keystore password:  
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 1 entry

Alias name: mirthconnect
Creation date: Mar 30, 2022
```
5. Run ./mcserver
6. KeyStore should now contain two values (encryption was added)
```
mirth@mirth-connect-******:/opt/connect/appdata$ keytool -list -v -keystore keystore.jks 
Enter keystore password:  
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 2 entries

Alias name: encryption
Creation date: Mar 30, 2022
Entry type: SecretKeyEntry


*******************************************
*******************************************
```
7. It should be noted that we are overriding the default JCEKS and using PCKS12 for the keystore format using: _MP_KEYSTORE_TYPE = 'PKCS12'

**Environment:**
 - OS: Kubernetes (Azure AKS) running Ubuntu
 - Java Distribution/Version: "latest" container image
 - Connect Version = 4.0.0

**Workaround(s)**
None that I am aware of.

**Additional context**
Running in Kubernetes (Azure AKS)

**Comment by jonbartels** [comment]
EDIT - I re-read the original post and it does look like OP has the correct `Entry type` for each object. I'll leave my comment up but I don't think its helpful to the problem, sorry for not reading more carefully!

The `Importing keystore /opt/connect/appdata/file.p12 to /opt/connect/appdata/keystore.jks...` does not appear when I run `mcserver` locally. Is this something from the container? That seems relevant because if `file.p12` is overwriting your `keystore.jks` that could explain the issue.

Notes - 
`com.mirth.connect.server.controllers.DefaultConfigurationController#initializeSecuritySettings` calls:

```
            configureEncryption(provider, keyStore, keyPassword);
            generateDefaultCertificate(provider, keyStore, keyPassword);
```

Those two methods generate a keypair for encryption and SSL. They both use the same keystore, so surely MCs usage of jetty has to support having multiple keypairs in a single keystore.

I observe that `configureEncryption` generates its key with `secretKey = keyGenerator.generateKey()` which returns a `SecretKey` while `generateDefaultCertificate` calls `KeyPair sslKeyPair = keyPairGenerator.generateKeyPair();` which returns a `KeyPair`.

I ran this on a fresh MC 4.0 install on my desktop:
```keytool -v -list -keystore appdata/keystore.jks -storepass sooperdoopersecret -storetype JCEKS 
Keystore type: JCEKS
Keystore provider: SunJCE

Your keystore contains 2 entries

Alias name: encryption
Creation date: Mar 31, 2022
Entry type: SecretKeyEntry


*******************************************
*******************************************


Alias name: mirthconnect
Creation date: Mar 31, 2022
Entry type: PrivateKeyEntry
Certificate chain length: 1
```

Is it possible that your hand-crafted keystore needs to be generating a different kind of key for `encryption`?

You might run `keytool -list` on a bog standard keystore and diff it against the output from your keystore. I bet the key type or an extension will be different between the two.

Please post what you find, this is an interesting problem.

**Comment by cseeger-harris** [comment]
@jonbartels I created the cert from a single base64 cert and base64 key using openssl (within the container itself).  Here is the command I used:
`openssl pkcs12 -export -name mirthconnect -inkey /mnt/secrets-store/key.pem -in /mnt/secrets-store/cert.pem -out /opt/connect/appdata/file.p12 -nodes -passout pass:$_MP_KEYSTORE_STOREPASS
`
I then create a new keystore with the following keytool command:
`keytool -importkeystore -srckeystore /opt/connect/appdata/file.p12 -srcstoretype pkcs12 -destkeystore /opt/connect/appdata/keystore.jks -deststoretype pkcs12 -deststorepass $_MP_KEYSTORE_STOREPASS -srcstorepass $_MP_KEYSTORE_STOREPASS -srcalias mirthconnect -destalias mirthconnect`

Keystore/cert password is passed in via environment variables.  It seems to work if I do not create my own keystore before mcserver is started.  I wonder if it's the call to open an existing keystore that is failing?

This worked fine prior to 4.0.0.

Not sure if this is relevant, but googling found similar issues, with an example fix here: https://github.com/apache/nifi/pull/4471/commits/0bb575561ee1feeaa09c04316d88cb23c6639860

**Comment by jonbartels** [comment]
What happens if you put `file.p12` somewhere other than `appdata`? 

I hope I'm not fixating on a red herring, where does the `Importing keystore /opt/connect/appdata/file.p12 to /opt/connect/appdata/keystore.jks...` message come from?

Also regarding "worked prior to 4.0" - many Jetty libraries were updated in 4.0. It's plausible that this change is new to MC because it was introduced in the intervening time with Jetty updates.

**Comment by cseeger-harris** [comment]
The file is imported just fine from appdata, but even moving it into a directory up didn't change anything.  The "importing keystore" string comes from keytool when you run the import:

```
keytool -importkeystore -srckeystore /opt/connect/file.p12 -srcstoretype pkcs12 -destkeystore /opt/connect/appdata/keystore.jks -deststoretype pkcs12 -deststorepass $_MP_KEYSTORE_STOREPASS -srcstorepass $_MP_KEYSTORE_STOREPASS -srcalias mirthconnect -destalias mirthconnect

Importing keystore /opt/connect/file.p12 to /opt/connect/appdata/keystore.jks...
```

From what I can tell, the error may be related to using new SslContextFactory(); vs new SslContextFactory.Server();.  The error calls it out if you scroll far to the right:

```
java.lang.IllegalStateException: KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory. 
(Use org.eclipse.jetty.util.ssl.SslContextFactory$Server or org.eclipse.jetty.util.ssl.SslContextFactory$Client instead)
```

I have no reason to believe the p12 I am creating is bad.  It imports fine into the keystore and i can convert it back to base64 without issue.

**Comment by jonbartels** [comment]
Your keystore has the same key formats as what MC builds for itself (thats good!). If Jetty needed a different call for its SslContextFactory then a basic off-the-shelf install of MC wouldn't work. I agree that you have constructed your p12 and keystore correctly. It looks consistent with how MC creates its own keystore.

I have crossposted your question to the MC Slack channel. If the brain trust over there comes back with any good ideas I will crosspost them here. https://mirthconnect.slack.com/archives/C02SW0K4D/p1648746892472399

**Comment by jonbartels** [comment]
@cseeger-harris you should pop into Slack and see replies from the user "A" - https://mirthconnect.slack.com/archives/C02SW0K4D/p1648748358268299

Briefly that user had some ideas:
* PKCS12 vs JCEKS
* SNI

That user also cited the specific Jetty version and code which showed the issue.

**Comment by jonbartels** [comment]
Copying discussion from Slack:

```
[A](https://app.slack.com/team/UBTM4RQHM)  [16 hours ago](https://mirthconnect.slack.com/archives/C02SW0K4D/p1648761718235329?thread_ts=1648761647.016729&cid=C02SW0K4D)
Is the certificate you are using a Wildcard or have SAN entries?




[cseeger-harris](https://app.slack.com/team/U039HTVR6QM)  [16 hours ago](https://mirthconnect.slack.com/archives/C02SW0K4D/p1648761729039689?thread_ts=1648761647.016729&cid=C02SW0K4D)
it is a wildcard

[A](https://app.slack.com/team/UBTM4RQHM)  [16 hours ago](https://mirthconnect.slack.com/archives/C02SW0K4D/p1648761746225559?thread_ts=1648761647.016729&cid=C02SW0K4D)
That's the issue. I was able to reproduce using a self-signed with a SAN entry.

[cseeger-harris](https://app.slack.com/team/U039HTVR6QM)  [16 hours ago](https://mirthconnect.slack.com/archives/C02SW0K4D/p1648761759256439?thread_ts=1648761647.016729&cid=C02SW0K4D)
ah ok

[cseeger-harris](https://app.slack.com/team/U039HTVR6QM)  [15 hours ago](https://mirthconnect.slack.com/archives/C02SW0K4D/p1648761776593149?thread_ts=1648761647.016729&cid=C02SW0K4D)
well good to know someone else can reproduce :slightly_smiling_face:
:+1:
1


[cseeger-harris](https://app.slack.com/team/U039HTVR6QM)  [15 hours ago](https://mirthconnect.slack.com/archives/C02SW0K4D/p1648761809995369?thread_ts=1648761647.016729&cid=C02SW0K4D)
I linked a similar issue from another repo that might be related

[A](https://app.slack.com/team/UBTM4RQHM)  [15 hours ago](https://mirthconnect.slack.com/archives/C02SW0K4D/p1648761838044429?thread_ts=1648761647.016729&cid=C02SW0K4D)
I'm not sure what needs to change in how Mirth setups the Jetty server to support those certs but the version of Jetty that introduced the change in behavior was 9.4.23.

[cseeger-harris](https://app.slack.com/team/U039HTVR6QM)  [15 hours ago](https://mirthconnect.slack.com/archives/C02SW0K4D/p1648761839046839?thread_ts=1648761647.016729&cid=C02SW0K4D)
there are several, that one was just straight forward code

[cseeger-harris](https://app.slack.com/team/U039HTVR6QM)  [15 hours ago](https://mirthconnect.slack.com/archives/C02SW0K4D/p1648761863448269?thread_ts=1648761647.016729&cid=C02SW0K4D)
ah ok, guessing jetty was updated in 4.0.0 vs 3.12?

[A](https://app.slack.com/team/UBTM4RQHM)  [15 hours ago](https://mirthconnect.slack.com/archives/C02SW0K4D/p1648761894729259?thread_ts=1648761647.016729&cid=C02SW0K4D)
Yup. 9.4.44
```

**Comment by cturczynskyj** [comment]
This doesn't look to be limited to PKCS12 as I just ran a test and I believe it also occurs with a wildcard cert in a JCEKS keystore. Has anyone else tried/encountered that?

**Comment by cseeger-harris** [comment]
> This doesn't look to be limited to PKCS12 as I just ran a test and I believe it also occurs with a wildcard cert in a JCEKS keystore. Has anyone else tried/encountered that?

Forgot to note, I was using a wildcard cert when I first ran into this.  When I allow mirth to create its own cert, it works fine.  Seems like they have created an internal issue and done some triage.  Thanks, devs!

**Comment by bdurrow** [comment]
Is there a workaround for this or do we just need to wait until 4.0.1 is released?  I see that the Fix-Commited label was added but can't find any recent commits.

**Comment by pladesma** [comment]
There is no current workaround, but we will release 4.0.1 soon, by the end of the month.
