### ISSUE TITLE
[BUG] Alert - Possible wrong information for channel

### ISSUE THREAD

**Issue by boukenka** [nextgenhealthcare/connect#5145]
**Describe the bug**
The API and the XML export does not return the correct list of Channel IDs from my point of view.

**To Reproduce**
Setup steps :
1. Setup a MIRTH Source server
2. Create 2 channels _Channel Test 1_ and _Channel Test 2_
4. Their IDs are 5662c269-12d9-4a7f-af96-d9dc94946434 and 06de3020-4852-4679-b4ca-2187b927f856
5. Create two Alerts like the attached screenshot
6. Export via the user interface the Alerts (see the attached file and the screenshot)
7. Use the API to retrieve the Alerts. Same result

[Alerts.zip](https://github.com/nextgenhealthcare/connect/files/8521125/Alerts.zip)

**Expected behavior**
The fields _enabledChannels_ and _disableChannels_ should list the correct Channel IDs.

For the Omega Alert, the XML should be : 

```XML
<enabledChannels>
    <string>06de3020-4852-4679-b4ca-2187b927f856</string>
</enabledChannels>
<disabledChannels>
    <string>5662c269-12d9-4a7f-af96-d9dc94946434</string>
</disabledChannels>
```

For the Alpha Alert, the XML should be : 

```XML
<enabledChannels>
    <string>5662c269-12d9-4a7f-af96-d9dc94946434</string>
</enabledChannels>
<disabledChannels>
    <string>06de3020-4852-4679-b4ca-2187b927f856</string>
</disabledChannels>
```

**Actual behavior**
The fields _enabledChannels_ and _disableChannels_ list only the _Channel Test 1_ Channel in the XML Alerts.

I feel like the XML Alert rule is this:

* If the first Channel is enabled in the Alert definition, its ID is in the _enabledChannels_ field. If there are other enabled Channels  in the Alert definition, their IDs will also be present in the _enabledChannels_ field.
* If the first Channel is not enabled  in the Alert definition, its ID is in the _disabledChannels_ field. If there are other disabled Channels  in the Alert definition, their IDs will also be present in the _disabledChannels_ field.

To me this seems to be a very strange logic. 
To know, which Channel is enabled/affected by the Alert, the following must be done : 

A - If the field _enabledChannels_ of the Alert definition is not empty, then all the Channels present in this field are affected by the Alert.
B - If the field _enabledChannels_ of the Alert definition is empty, then all Channels which are not present in the field _disabledChannels_ are affected by the Alert.

Is this correct ? Or is it a bug?

**Screenshots**
![image](https://user-images.githubusercontent.com/16502423/164225632-2a352acb-c59a-4dce-bc7f-b0e0e24cca73.png)
![image](https://user-images.githubusercontent.com/16502423/164225690-1f53673b-2e73-41b7-b231-5ad9c33e35f7.png)

**Environment (please complete the following information):**
 - OS: _linux_ (docker)
 - _Connect Version 4.0.0_

**Workaround(s)**
No real alternative. There is a blockage.

**Comment by pacmano1** [comment]
Is something actually broken when you export and import?    Or otherwise broken? Other than how you think it should have been coded of course which I think is your point on the story.

What is this blocking exactly?  Can you provide a use case?

If not - probably should not be listed as a bug.

**Comment by boukenka** [comment]
If you take a look at XML of the Code Template Library export, it works exactly as it should from my perspective.
The _disabledChannelIds_ field lists the Channel IDs that are not assigned/using the Code Template lLbrary.
The _enabledChannelIds_ field lists the IDs of Channels that are affected/using the Code Template Library.

It is not broken from a functional standpoint. Yes, you are right. 
Rather, that is how it should have been coded. From my point of view.

The blocking point is that it makes it harder to interpret/extract information from the Channels involved in the Alert.
This is why it is written the _Possible_ word in the subject of the issue. 😄 

Is my interpretation of the logic correct in the problem description? Why doesn't the XML section for Channels follow the same functional rule in Alerts and in the Code Template Libraries?

**Comment by pacmano1** [comment]
I think you would have to ask the developer who wrote it.   Maybe Nextgen will chime in.

**Comment by boukenka** [comment]
Thank you for your feedback @pacmano1. I have also contacted the official support.

**Comment by pladesma** [comment]
The `Omega` alert is configured to be enabled for all new channels. In other words, it's enabled on channels by default, so only the `disabledChannels` need to be tracked.

Conversely, the `Alpha` channel is configured to be disabled for all new channels, so it's disabled on channels by default. Therefore, only the `enabledChannels` need to be tracked. So that explains why the Alert models store data as they do.

**Comment by boukenka** [comment]
@pladesma Thank you for the answer. I am closing the issue.
