### ISSUE TITLE
How to stop mirthconnect mcserver using external python script after conversion through channels .

### ISSUE THREAD

**Issue by sal4455** [nextgenhealthcare/connect#5148]
Hi,
I have created a script to start the mirth-server-launcher.jar using python script, but I could'nt find a way how to stop the mirth-server-launcher.jar just after conversion of all messages from mirth channels. Please help me out with this .
Is there any mirth functionality available that I can leverage for stopping mirth server automatically after conversion through channel?
Thankyou in Advance .

**Comment by pacmano1** [comment]
Is there a reason you are not using the standard start (systemd) scripts?  

 I assume you are on linux, but you didn't post much about your environment.

"mirth server automatically after conversion through channel?" what does that mean?

**Comment by pacmano1** [comment]
Also, this should be in discussions, not posted as an issue, moving it there.
