### ISSUE TITLE
[BUG] Appending to msg produces invalid XML

### ISSUE THREAD

**Issue by elavy-harris** [nextgenhealthcare/connect#5193]
**Describe the bug**
If you create a new segment with `createSegment('XXX')` or `new XML('<XXX/>")` and try to append the new segment to the end of msg, invalid XML is produced.

**To Reproduce**
Execute the following code in a transformer:
```
var newSegment = createSegment('XXX');   // or new XML('<XXX/>')
msg += newSegment;
logger.info('msg: ' + msg.toString());
```

(Note that code like this is described in the User Guide, under "Adding Segments to a Message".)

**Expected behavior**
The logged output should end with `<XXX/></HL7Message>`.

**Actual behavior**
The logged output ends with `</HL7Message><XXX/>` and an error is thrown:
`
ERROR MESSAGE: Error converting XML to ER7
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 10712; The markup in the document following the root element must be well-formed.
`

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java: java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
 - Connect Version 4.0.0

**Workaround(s)**
`var newSegment = createSegment('XXX', msg);`

**Comment by jonbartels** [comment]
What happens if you change `msg += newSegment;` to `msg.appendChild(newSegment)`? The error message sounds like its doing string concatenation instead of XML operations.

Is this unique to 4.x? Did this code previously work in 3.x?

What is your `rhino.languagelevel` setting in `mirth.properties`?

**Comment by elavy-harris** [comment]
- `msg.appendChild(newSegment)` works, so maybe this is just a documentation issue?
- I haven't tried it in 3.x and am not using it.
- I have no `rhino.languagelevel`.  I have `rhino.languageversion = es6`.

**Comment by mjtrac** [comment]
In E4X, if you have a top-level XML node, the += operator adds a new top-level node, not a new child.

The top-level node of an HL7Message is \<HL7Message>.  The += operator will add your segment as a new top-level node, which is not what you want.  The conversion back from XML will end at the end of \<HL7Message> and ignore the new top-level node.

PS C:\Program Files\Mirth Connect\server-lib> java -jar .\rhino-1.7.13.jar                                              Rhino 1.7.13 2020 09 02
js> x = \<A/>

js> x += \<B/>
\<A/>
\<B/>

js> x = \<A/>

js> x.appendChild(\<B/>)
\<A>
  \<B/>
\</A>

**Comment by elavy-harris** [comment]
Then apparently this is a documentation issue in the User Guide, under "Adding Segments to a Message".

**Comment by pladesma** [comment]
We will update the documentation in the User Guide.
