### ISSUE TITLE
[BUG] Multiple calls to createSegment ovewrite prior segments

### ISSUE THREAD

**Issue by elavy-harris** [nextgenhealthcare/connect#5262]
**Describe the bug**
If I call createSegment(seg,msg) multiple times, with the same 'seg', only the last one is present in msg.

**To Reproduce**
Insert the following code into a source transformer and process any HL7 message:
```function createSegs() {
	let seg = createSegment('XXX', msg);
	seg['XXX.1'] = 'XXX.1';
	seg = createSegment('XXX', msg);
	seg['XXX.1'] = 'XXX.1#2';
```

**Expected behavior**
Two XXX segments should be added to the message.

**Actual behavior**
Only the 2nd XXX segment is in the message.

**Environment:**
- OS: Windows 10
- Java: java version "1.8.0_333"
 Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
 Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)
- Connect Version 4.0.0

**Workaround(s)**
I was able to work around the issue with the following for each new segment:
```
seg = createSegment('XXX');   // new XML('<XXX/>') works, too.
seg['XXX.1'] = 'XXX.1';
msg.appendChild(seg); // Note that this must be done AFTER populating seg.

**Comment by pacmano1** [comment]
That is acting as designed.

Please see other create segment functions.

![image](https://user-images.githubusercontent.com/44065187/176921404-727a3e4c-6a2c-4778-932c-02b3a2c5294c.png)

**Comment by elavy-harris** [comment]
I'm not using that flavor.  I'm using the prior one, which says that it creates a _new_ segment in the message:
![image](https://user-images.githubusercontent.com/102183351/176923119-99b73b99-da49-40ec-9cf2-101129b437c8.png)

It doesn't say _where_ it creates the segment, but the documentation says that it creates it at the end of the message:
![image](https://user-images.githubusercontent.com/102183351/176923511-2e38be00-097f-4457-b331-e416169daae2.png)

**Comment by jonbartels** [comment]
`createSegment` with two args is defined in `JavaScriptBuilder.java` as:

```
        // Helper function to create segments
        builder.append("function createSegment(name, msgObj, index) {");
        builder.append("if (arguments.length == 1) { return new XML('<' + name + '></' + name + '>'); };");
        builder.append("if (arguments.length == 2) { index = 0; };");
        builder.append("msgObj[name][index] = new XML('<' + name + '></' + name + '>');");
        builder.append("return msgObj[name][index];");
        builder.append("}\n");
```

See how it always defaults the index to zero?

If you create multiple segments you have to use the three arg variant and pass the index.

**Comment by pacmano1** [comment]
Thanks @jonbartels , I mentioned the other calls but your explanation is better.  elavy-harris, a documentation "bug" perhaps.

**Comment by pladesma** [comment]
This appears to be working as designed, so I'll close this issue.

**Comment by elavy-harris** [comment]
As designed, perhaps, but there are still issues.  As @pacmano1 suggested, the documentation and JSDoc should be updated to indicate the actual behavior, assuming that the code itself remains unchanged.

To me, however, the behavior makes no sense and should be changed.  The logic appears to be:
- If there are no segments with the given name, create one.  (That's OK.)
- if there ARE segments with the given name, overwrite the first one.

Why would _anyone_ use a function called createSegment to overwrite a pre-existing segment?!
