### ISSUE TITLE
[Docs] Reconsider "Private and Confidential - Do Not Distribute" footers in Mirth Connect User Guide linked on Github

### ISSUE THREAD

**Issue by ab-20-m** [nextgenhealthcare/connect#5265]
The currently linked version of the [User Guide](https://www.nextgen.com/-/media/Files/nextgen-connect/nextgen-connect-310-user-guide.pdf) contains "Private and Confidential - Do Not Distribute" footers. The document is publicly linked from a public non-authenticated website to a public, non-authenticated server that serves up the document without any form of EULA or warning. That is about as non-private and non-confidential as it can get.

**Comment by pacmano1** [comment]
LOL, that was perfect.  

...
Private and Confidential - Do Not Distribute

**Comment by pladesma** [comment]
Haha yeah, you make a good point. We're actually moving to a new [user guide](https://docs.nextgen.com), and we've been updating our links to point to it, so this won't be an issue going forward.
