### ISSUE TITLE
[BUG] Mirth 4.x  encoding on Windows 2022

### ISSUE THREAD

**Issue by Rippenator** [nextgenhealthcare/connect#5277]
**Describe the bug**
We have found with our new installation of Mirth on Windows 2022 servers that when a message comes in from a different LIMS system that some characters are not found in particular µ.   We found if we drop this message in mirth it works as expected.  But if the message comes into Mirth from the outside when on a Windows 2022 Machine that it does not recognize it and returns unknown character.

**To Reproduce**
Setup steps (if required). Example:
Incoming message with µ in the sample.
{ex}
OBX|23|NM|420^TRYPTOPHAN^LRR^^^^^^TRYPTOPHAN||71|µmol/L|23-71||||F|||20220616095400|1230002040^WI STATE LAB OF HYGIENE-BCG^LLB^^^^^^WI STATE LAB OF HYGIENE-BCG||||20220616143301||||WI STATE LAB OF HYGIENE-BCG^D^^^^^^^^1230002040|465 HENRY MALL^^MADISON^WI^53706-1501^USA^B^^DANE||||||

Results from a different lims system that has was working fine prior to the upgrade with defaults set, coming into the system with µ in the results.

**Expected behavior**
Message/results process thru without error 

**Actual behavior**
Message processes but sends the wrong character.  in our case it was Âμmol/L that the customer received.  In Mirth before we set the encoding I have a screenshot below.  the symbol that Mirth produced was � (unicode Block) replacement char.

**Screenshots**
![image](https://user-images.githubusercontent.com/105882385/177877615-50ad1151-b4a3-476e-8f4c-9bff57008eb1.png)

**Environment (please complete the following information):**
 - OS: Windows 2022 / Oracle 19c
 - Java Distribution/Version  jdk-18_windows-x64
 - Connect Version 4.0.1

**Workaround(s)**
Are there one or more workarounds for this issue currently?
We have found that if you change the encoding on the incoming channel from default to Windows-1252 and the destination submitter channels to Windows-1252 the message processes correctly.

**Additional context
Some information we found
https://devblogs.microsoft.com/oldnewthing/20220531-00/?p=106697

**Comment by tonygermano** [comment]
I don't think this is a bug. That's a risk you take with using "Default" instead of being explicit. Mirth just picks up the default from Java. I would bet that if you installed an older mirth version on the same OS and java distribution you'll see the same behavior.

Not sure if this will work or not, but you might try setting `-Dfile.encoding=windows-1252` in your server's vmoptions file to avoid needing to touch all of your channels.

**Comment by ab-20-m** [comment]
JDK18 included [JEP 400: UTF-8 by default](https://openjdk.org/jeps/400). Prior to that on Windows, the JDK would set the default encoding based on the system locale information. For the *Nix systems that usually ended up being UTF-8 but on Windows it wasn't. 

The supported mechanism to fall back to the previous behavior when using JDK 18+ is to use `-Dfile.encoding=COMPAT`. As @tonygermano pointed out, depending on the default encoding is dangerous. Setting to `-Dfile.encoding=windows-1252` "should" work but generally setting that system property to a specific encoding was never supported and your mileage may vary.
