### ISSUE TITLE
Newlines in base64 attachment

### ISSUE THREAD

**Issue by bulldozer2003** [nextgenhealthcare/connect#5301]
Can newlines added to attachments printed out as base64 be removed? Adding additional characters to the attachment, even if translated to base64 makes using the attachment as base64 impossible without additional processing.

### Discussed in https://github.com/nextgenhealthcare/connect/discussions/5300

<div type='discussions-op-text'>

<sup>Originally posted by **bulldozer2003** July 20, 2022</sup>
I am trying to send an attachment as part of a JSON object using the HTTP sender destination. The server kept responding with "invalid JSON" which I determined is due to there being newlines in the base64 string. My HTTP sender is configured to send the test content below where `${attachment}` is a variable containing the `${ATTACH:...}` token string. When I use this, everything is sent as I expect but the base64 contains those additional newlines which breaks the JSON.
```
{
  "foo":"bar",
  "baz":"${attachment}"
}
```

I am loading the attachment from an SMB share using a javascript attachment script. I'm loading the file as a byte array and using `addAttachment(file, 'audio/mpeg', true)`. I don't believe reading the file from SMB would add newlines to an mp3 file arbitrarily.

In trying to troubleshoot where the newlines are coming from I added a javascript writer destination with the following:
```
var attachment = getAttachment($('attachmentId'), false);
logger.info(attachment.getContent());
logger.info(attachment.getContentString());
```

The output of `getContentString()` contains the newlines implying mirth is adding them when I load the file?

We are using mirth version 3.12</div>

**Comment by pacmano1** [comment]
I think you want to rephrase your ask.  

RFC 2045, which defined Base64 requires a newline after 76 characters
