### ISSUE TITLE
[SECURITY] Directory listing on Jetty web server

### ISSUE THREAD

**Issue by mlarcelet** [nextgenhealthcare/connect#5317]
**Describe the security issue**
 MirthConnect Web portal and API : the Jetty web server is configured to automatically list the contents of directories that do not have an index page present (category [CWE-548](https://cwe.mitre.org/data/definitions/548.html))
examples : 
![image](https://user-images.githubusercontent.com/28092386/181722430-e35f6d43-445e-48a0-885b-a8d1b07a533b.png)

**Vulnerability Location**
Jetty web server

**Environment**
 - OS:  Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-122-generic x86_64)
 - Java Distribution/Version : OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
 - Connect Version : 4.01

**Suggested remediation**
https://webtide.com/indexing-listing-vulnerability-in-jetty/

**Comment by joaryche** [comment]
This "vulnerability" is for an earlier version of jetty than the one Connect uses.   The ability to see the client-libs and extensions/libs are special paths added specifically for the user.   This not an issue but a feature.
