### ISSUE TITLE
[BUG] Registering the first user is now mandatory

### ISSUE THREAD

**Issue by is-simon** [nextgenhealthcare/connect#5331]
It is not really a bug, you probably have knowingly introduced this, but it is now mandatory to register the first user that starts the administrator, [see here](https://github.com/nextgenhealthcare/connect/blob/development/client/src/com/mirth/connect/client/ui/FirstLoginDialog.java#L50).

I would like to suggest that you reconsider this decision. We are a company using NextGen Connect and we have a developers team working on a daily basis on some home made extensions. I personally have to delete my appdata folder several times a week (working with derby while developing), and now, each time I do that, I have to unplug my ethernet cable to be sure that my first test user (which was only 3 fields to enter before, I used "admin" everywhere, 3 seconds and I was done. Now I have to fill all the required fields. How annoying...) is not registered with NextGen Healthcare. Everything seems to work since the connection error is ignored ([see here](https://github.com/nextgenhealthcare/connect/blob/0974c6ad4d6fc683d544f6f23da0def551812ecc/client/src/com/mirth/connect/client/ui/Frame.java#L1981)) but that is just worst IMHO.

So I'm asking, please reconsider. We just can't adopt the 4.1.0 version with that in place.

We have a valid license with NextGen Healthcare that we are paying for every year, but even so, we just can't work with this new requirement.

**Comment by jonbartels** [comment]
Discussion - https://github.com/nextgenhealthcare/connect/discussions/5321

Related issue - https://github.com/nextgenhealthcare/connect/issues/5329

**Comment by tonygermano** [comment]
I released a plugin that bypasses registration on first login for 4.1.0 since there is no other means to opt-out.

https://github.com/tonygermano/mirth-user-privacy-plugin
