### ISSUE TITLE
[BUG] FHIR Sender: proxy and headers

### ISSUE THREAD

**Issue by cldparisi** [nextgenhealthcare/connect#5354]
I use “FHIR Sender” (with plugin FHIR on Mirth 3.10.1) but I have two problem:

-	It can’t use a proxy in “FHIR Sender” (like in “Web Service Sender”),  I can use it in “HTTP Sender” but not in FHIR and Web Sender.
Has anyone solved that problem?
is it possible set a proxy for “all Mirth” and use it  on all channels? 

-	It can’t add a headers, It’s possible to do it in “Web Service Sender” and “HTTP Sender” but it’s not possible in “FHIR sender”.
Is it possible to add headers by code before sending message?
is there another workaround?

Thanks

**Comment by pacmano1** [comment]
@cldparisi If you post here and the forums, please cross reference those.

Also, you are both asking questions (better for the discussion section) and asking for a feature, those two things should probably be two seperate things.   When you create a feature request it has a template you shoud follow.

I am converting this "bug" to a discussion for now.
