### ISSUE TITLE
Mozilla Public License compliance and mirth-crypto.jar missing source code

### ISSUE THREAD

**Issue by tonygermano** [nextgenhealthcare/connect#5390]
`mirth-crypto.jar` is a dependency of mirth, which is included as a pre-compiled library with other 3rd-party jars (see [mirth-crypto.jar](https://github.com/nextgenhealthcare/connect/blob/4.1.0/server/lib/mirth-crypto.jar).) The source for this library is not available.

However, it is not mentioned in [THIRD-PARTY-README.txt](https://github.com/nextgenhealthcare/connect/blob/4.1.0/server/docs/thirdparty/THIRD-PARTY-README.txt) as having a different license than the rest of the project which is released under MPL-2.0, according to the [LICENSE](https://github.com/nextgenhealthcare/connect/blob/4.1.0/LICENSE).

Without specifying a different license that allows distribution and without supplying the source code, this makes it impossible for an individual to distribute mirth, as granted under section 2.1(a) of the MPL-2.0 license, and comply with the responsibilities listed in sections 3.1 and 3.2 of the license.

https://github.com/nextgenhealthcare/connect/blob/00c2496bb4236f1c8a5a7cedafc00abf486623f1/LICENSE#L95-L104

https://github.com/nextgenhealthcare/connect/blob/00c2496bb4236f1c8a5a7cedafc00abf486623f1/LICENSE#L163-L184

Please release the source for this required library with the rest of the project. It is very reasonable for an individual to want to audit how security is applied to encryption and user passwords. Application security should not be a black box. The request for visibility into this functionality has come up in the past, dating back to at least to 2014.
https://forums.mirthproject.io/forum/mirth-connect/support/10008-mirth-3-0-encryption-settings?p=68928#post68928
https://forums.mirthproject.io/forum/mirth-connect/support/3255-reset-admin-password?p=104351#post104351
https://forums.mirthproject.io/forum/mirth-connect/support/13131-incorrect-username-or-password-after-reboot-3-x?p=81749#post81749

**Comment by pladesma** [comment]
The mirth-crypto source code has been committed in the development branch

**Comment by tonygermano** [comment]
See commit https://github.com/nextgenhealthcare/connect/commit/cdd07a928253846a2fc3b513d5738e75636d8779 for changes.
