### ISSUE TITLE
[ERROR] Error Downloading/Verifying Codebase 

### ISSUE THREAD

**Issue by Vpret** [nextgenhealthcare/connect#5401]
Hello Hubs,

We are facing some issue with mirth, can anyone help in this, need urgently,

While loading Main JNLP

Unable to retrieve payload from HTTP request. URL:http://localhost:___/webstart
java.lang.Exception:unable to retrieve payload from HTTP request. URL:http://localhost:___/webstart
at com.mirth.connect.client.launcher.f.a.(sourcefile:791)
at com.mirth.connect.client.launcher.f.a.(sourcefile:671)
at com.mirth.connect.client.launcher.f.a.(sourcefile:167)
etc....

**Comment by pacmano1** [comment]
Is the enging running?
Does netstat show the port is listening?
Does mirth.log show anything?

You have posted no details.  Much like saying "my car won't start".
