### ISSUE TITLE
[BUG] logger.info results in ParameterizedMessage output

### ISSUE THREAD

**Issue by matthydehoog** [nextgenhealthcare/connect#5423]
From MC4.0 onwards the script logger.info results into a different output.

The command
_logger.info("User {} has logged in using id {}");_
in a source transformer gives:

[2022-09-14 17:04:10.198] INFO (transformer:?): User {} has logged in using id {}

Using the same code in a channel deploy script gives:

[2022-09-14 17:04:56.555] INFO (deploy:?): ParameterizedMessage[messagePattern=User {} has logged in using id {}, stringArgs=[], throwable=null]

Using MC 4.1.1

**Comment by jonbartels** [comment]
@pladesma  https://github.com/nextgenhealthcare/connect/discussions/5343 has users reporting different places where the logging behavior is different. These user reports might be helpful to make sure the problem is solved everywhere it occurs

**Comment by anei20018cool** [comment]
open ArrayAppender.java line 43 , change logEvent.getMessage() to logEvent.getMessage().getFormattedMessage()
