### ISSUE TITLE
save  imported channel cause null error 

### ISSUE THREAD

**Issue by linxd** [nextgenhealthcare/connect#5425]
**Describe the bug**
 import a channel.
 then edit, save, then report : 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.mirth.connect.client.ui.ChannelSetup.saveChanges(ChannelSetup.java:1129)
	at com.mirth.connect.client.ui.Frame.doDeployFromChannelView(Frame.java:2942)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 
the code :  
 ```
try {
			originalStateChannel = parent.mirthClient.getChannel(currentChannel.getId(), false);
        	if (originalStateChannel != null) {
        		Integer userId = originalStateChannel.getExportData().getMetadata().getUserId();
    			if (userId != 0 && userId != null) {
    				otherUsername = parent.mirthClient.getUser(userId).getUsername();
    			}
        	}
		} catch (ClientException e1) {
			
		}
```
should  change  this 👍 : 
if (userId != 0 && userId != null) {  

to :
if ( userId != null&&userId != 0 ) {

?

**Comment by pacmano1** [comment]
What version of Mirth?  What version of java?  What host operating system?
   
I do not understand your report.  We import channels all the time without error.

**Comment by pacmano1** [comment]
Attach a channel that demonstrates the behavior perhaps?

**Comment by pladesma** [comment]
As pacmano1 pointed out, you should provide more information regarding the issues you report.

However, the code change you suggested is a good idea, so we'll make that change in the upcoming version. Also, I just wanted to note that that particular code isn't included in any released versions yet, so it should not affect anyone using the officially released builds.
