### ISSUE TITLE
[IDEA] Multiple File Selected when Sending Messages

### ISSUE THREAD

**Issue by joaryche** [nextgenhealthcare/connect#5444]
**Describe your use case**
When sending message to the channel from the dashboard, a dialog allowing me to edit or choose a file opens.   When I click on the button for Open Text File,  I can only select one file.   

**Describe the solution you'd like**
I would like to be able to select multiple files so I can speed up the sending of files instead of opening them up one at a time.

**Comment by pacmano1** [comment]
And how would those files be ordered since the file selection box has arbitrary ordering?  Probably should sort that out here for feedback.
