### ISSUE TITLE
[SECURITY] Getting SSL Issue (connection not secure) on localhost:8443 for Mirth connect application

### ISSUE THREAD

**Issue by usharaniyerra** [nextgenhealthcare/connect#5472]
**Describe the security issue**
We are getting SSL Issue (connection not secure) on localhost:8443 in browser for Mirth connect application.

**Vulnerability Location**
Is this a vulnerability in a 3rd party library or the Connect codebase itself? - Connect codebase itself

**Environment (please complete the following information if it is applicable to the issue)**
 - OS: Windows server 2016 standard
 - Java Distribution/Version Java 8_341
 - Connect Version Mirth connect 3.12.0

**Suggested remediation**
We have updated the mirth self-signed certificate with our company's certificates. 

**Additional context**
After updating the certificate, the login console from the browser with the url https://DNS:8443 showing invalid credentials. But if we revert the cert with self-signed we are able to properly logging in.

Could you please help us whether we are missing any step when updating the self-signed certs with our company's certs? Or Please guide us how we can resolve the issue. Thanks.

**Comment by jonbartels** [comment]
Should be discussed at https://github.com/nextgenhealthcare/connect/discussions/5473 . This probably is not an issue and the discussion at https://github.com/nextgenhealthcare/connect/discussions/5473 is the best place to solve this problem.
