### ISSUE TITLE
[IDEA] Add New JavaScript Utility Methods to Generate a Hash of Channel Messages

### ISSUE THREAD

**Issue by jdonextgen** [nextgenhealthcare/connect#5476]
**Describe your use case**
I need to be able to generate a hash of messages passing through a channel and be able to send it to receiving systems so that receiving systems can verify message integrity by checking the hash.

**Describe the solution you'd like**
Add new JavaScript utility methods that leverage the [MessageDigest](https://docs.oracle.com/javase/8/docs/api/java/security/MessageDigest.html) library to generate a hex hash of messages passing through a channel.

**Comment by pacmano1** [comment]
You can't do https://forums.mirthproject.io/forum/mirth-connect/development/2376-cryptographic-hash-algorithm-in-mirth?p=79508#post79508?

**Comment by ChristopherSchultz** [comment]
I'm sure that's possible, but a javascript method wrapper in the "standard js API Mirth provides would be a nice addition, even if only for improved readability. Also, it doesn't matter that Mirth includes Guava... Mirth can simple implement the js function however it wants and even re-implement it later if Guava is no longer necessary, etc.
