### ISSUE TITLE
Mirth 3.9.0 shwoing unsupported class file major version 61

### ISSUE THREAD

**Issue by prajwal014** [nextgenhealthcare/connect#5513]
**Describe the bug**
On mirth connect 3.9.0 I'm getting below error my project war is complied and built on java17 but mirth webadmin war showing .class version 52 showing this error in mirth log.
Project version details:
Java_home = 17.0.3
mirth version = 3.9.0
Project war built on java 17.0.3

Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:283)
		at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:951)
		at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:936)
		at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:895)
		... 9 more

**Comment by jonbartels** [comment]
"Unsupported classs file major version" means that you compiled with Java X and are running with Java <X. 

Did you compile MC yourself or download it from NextGen?

Look at `mirth.log` right before the error, is there a log message showing what Java version MC is using?

**Comment by ChristopherSchultz** [comment]
I suspect that you are not actually running with Java 17. This error is on the server? Do a `ps` and look for the running process, then look at what command has been invoked to launch the JVM. Perhaps you just need to set `JAVA_HOME` appropriately.

**Comment by prajwal014** [comment]
> "Unsupported classs file major version" means that you compiled with Java X and are running with Java <X.
> 
> Did you compile MC yourself or download it from NextGen?
> 
> Look at `mirth.log` right before the error, is there a log message showing what Java version MC is using?



> I suspect that you are not actually running with Java 17. This error is on the server? Do a `ps` and look for the running process, then look at what command has been invoked to launch the JVM. Perhaps you just need to set `JAVA_HOME` appropriately.

>I have configured java_home to 17.03 and my mirth is also running on the same 17.0.3 I have my 2custome war deployed in mirth which is built on 17.0.3 and I have 3rd war which is webadmin.war which comes with mirth 3.9.0 which is built on java8.
>I downloaded MirthConnect 3.9.0 from NextGen only running it on Java17.0.3
>Mirth log showing that its running on java17.0.3 only
Actual mirth log is --> INFO  2022-11-07 10:22:06,143 [Main Server Thread] com.mirth.connect.server.Mirth: Running Java HotSpot(TM) 64-Bit Server VM 17.0.3 on Windows 11 (10.0, amd64), sqlserver, with charset windows-1252.
>Same java version is configured on my machine as well.

**Comment by prajwal014** [comment]
And when I'm trying to run the deployed web war on browser its giving 503  error.

**Comment by ab-20-m** [comment]
Mirth 3.9+ includes ASM 7.2 which only supports up to Java 14 when processing Java byte files.

I would strongly recommend not deploying any customer/custom WARs within the Mirth Connect Jetty instance even though it will deploy any WAR files under the `webapps` folder. Either use a dedicated Jetty instance you can manage/maintain/update or some other container server such as Tomcat.

**Comment by prajwal014** [comment]
> Mirth 3.9+ includes ASM 7.2 which only supports up to Java 14 when processing Java byte files.
> 
> I would strongly recommend not deploying any customer/custom WARs within the Mirth Connect Jetty instance even though it will deploy any WAR files under the `webapps` folder. Either use a dedicated Jetty instance you can manage/maintain/update or some other container server such as Tomcat.

So what is the solution if want to use only MirthConnect(Any version) with java17.03 builded war is there any alternate version or configuration that helps to run the java17.0.3 war in mirth-connect.

**Comment by jonbartels** [comment]
This should be moved to discussions. It is not an issue with Mirth Connect because @prajwal014 is customizing Mirth Connect.

@prajwal014 - Can you say what you are doing with a custom WAR and Mirth Connect? What are the contents of your `webapps` directory that you are trying to deploy?
