### ISSUE TITLE
http listener with Digest Authentication returns 401 when query string (URL parameters) are passed with Get

### ISSUE THREAD

**Issue by humairnoor** [nextgenhealthcare/connect#5539]
### Discussed in https://github.com/nextgenhealthcare/connect/discussions/5538

<div type='discussions-op-text'>

<sup>Originally posted by **humairnoor** November 19, 2022</sup>
Hi,
I have created http listener, requirement is to use "Digest Authentication", it works perfect with simple endpoint Get request but when I pass query string / url parameters  in "Get" request , I received "401 unauthorized" . I will really appreciate any guidance in this regard.

My Mirth version: 3.5.0

<h2>HTTP ERROR: 401</h2>
	<p>Problem accessing /patient/address. Reason:
		<pre>    Unauthorized</pre>
	</p>
	<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.14.v20161028</a></div>

**Comment by pacmano1** [comment]
@humairnoor Please don't post bugs/issues until you are sure they are that.  Based on your post in discussions I don't think this is a bug, rather an implementation / channel design problem.
