### ISSUE TITLE
[IDEA] Upgrade rhino engine to version 1.7.14

### ISSUE THREAD

**Issue by Vic-M** [nextgenhealthcare/connect#5541]
**Is your feature request related to a problem? Please describe.**
Rhino 1.7.14 now supports javascript template literals, which I'd like to use in Mirth.

**Describe the solution you'd like**
Upgrade the rhino engine to v1.7.14

**Additional context**
Rhino release notes: https://github.com/mozilla/rhino/releases/tag/Rhino1_7_14_Release

**Comment by jonbartels** [comment]
I want to call out that our very own Tony Germano has contributed ELEVEN PRs to Rhino between 1.7.13 and 1.7.14.

It would be a good idea for NextGen to talk to Tony and find out how his changes will benefit Mirth Connect or if any of those changes might present a migration risk.

**Comment by jonbartels** [comment]
Related discussion https://github.com/nextgenhealthcare/connect/discussions/5540
