### ISSUE TITLE
User who has a new PC and can't connect to server

### ISSUE THREAD

**Issue by jolt06** [nextgenhealthcare/connect#5566]
I have a user who has a new PC and i installed MIrth connect.  the issue is that the user can't log in on the new PC. but when they use the same credentials on the old pc they are able to log in. i have even tested the credentials and we are still getting the same issue. 
![log in issue](https://user-images.githubusercontent.com/55763689/205978712-855fea72-ade4-44ed-8b7e-69e8acc3e816.jpg)
this is a old version on the new pc as a test.

**Comment by pacmano1** [comment]
Moving this to discussion until a bug or issue is confirrmed.

You need to provide far more details on your configuration.  

Operating System on both PCs.
Are you using the Admin Launcher?  If yes are you overriding the bundled java version?
If you are not using the Admin Launcher what verstion of java?
