### ISSUE TITLE
[BUG] MCAL 1.3 Frequent Crashes on macOS Monterey

### ISSUE THREAD

**Issue by joshmc82** [nextgenhealthcare/connect#5584]
**Describe the bug**
Frequently, MCAL 1.3 will crash when run from the executable on macOS Monterey. This is not seen when launching from the jar using my default jre. When reviewing logs, I'm seeing` fatal error: Illegal threadstate encountered: 4`. Issue seems to be related to JFX plugin as per https://youtrack.jetbrains.com/issue/JBR-4128/MacOS-Internal-Error-safepoint.cpp919-fatal-error-Illegal-threadstate-encountered-4-using-JavaFX

**To Reproduce**
Setup steps (if required). Example:
1. Launch MCAL as normal from the application (not the jar).

1. Use the MCAL Normally
2. Occasionally see a crash when launching a new instance
3. See error logs in launcher root folder

**Expected behavior**
MCAL should not crash

**Actual behavior**
MCAL process crashes

**Screenshots**
See attached logs
[hs_err_pid28736.log](https://github.com/nextgenhealthcare/connect/files/10212007/hs_err_pid28736.log)
[hs_err_pid28609.log](https://github.com/nextgenhealthcare/connect/files/10212008/hs_err_pid28609.log)
[hs_err_pid28275.log](https://github.com/nextgenhealthcare/connect/files/10212009/hs_err_pid28275.log)
[hs_err_pid37504.log](https://github.com/nextgenhealthcare/connect/files/10212010/hs_err_pid37504.log)

**Environment (please complete the following information):**
 - OS: macOS Monterey 12.6.1 (M1 CPU)
 - Java Distribution/Version: using bundled JRE with MCAL
 - MCAL Version: 1.3

**Workaround(s)**
Bypass the OS-specific executable and launch the jar directly using `java -jar mirth-client-launcher.jar`

**Additional context**
Edited to add:
It seems the launcher script LOOKS for java in some places, but doesn't actually USE it when present.
The script appears to have `/Library/Java/JavaVirtualMachines/*.jdk` and  `/Library/Java/JavaVirtualMachines/*.jre` as search locations. I have multiple compatible JDKs installed at` /Library/Java/JavaVirtualMachines` but it appears none of them are used for some reason.
Would it make more sense to check JAVA_HOME first and attempt to use that first?

**Comment by joshmc82** [comment]
Update: if I edit the launcher script in a text editor and uncomment the line for `INSTALL4J_JAVA_HOME_OVERRIDE` and set it to the same path as my JAVA_HOME environment variable used by the OS, it works fine. Note that setting an environment variable on the OS for `INSTALL4J_JAVA_HOME` does nothing and it will still use the bundled JRE and crash.

**Comment by narupley** [comment]
If you're setting an environment variable on macOS, make sure you're actually setting it for all shells. Just exporting an env var in a terminal window won't do it, you'd need to add it to like bash_profile or something.

Before release we had multiple people test it out on Monterey+ without any issues... but clearly there are still some moles left to whack.

My best guess is that it's an aarch64 issue, not a Monterey issue. We know there are things to iron out there still, like replacing what JRE is bundled with the app!

**Comment by joshmc82** [comment]
@narupley yep, here's what I ran specifically to set the environment var:
`echo 'export INSTALL4J_JAVA_HOME=/Users/josh/.sdkman/candidates/java/current' >> ~/.zshenv`
When I open a new terminal, I can run `printenv` to show all of the environment vars set.
It would be nice to have it just use the JVM at JAVA_HOME (if set). That would more or less avoid all of the issues.

**Comment by ChristopherSchultz** [comment]
> My best guess is that it's an aarch64 issue, not a Monterey issue. We know there are things to iron out there still, like replacing what JRE is bundled with the app!

The log files say `vm_info: Java HotSpot(TM) 64-Bit Server VM (25.181-b13) for bsd-amd64 JRE (1.8.0_181-b13), built on Jul  7 2018 01:02:31 by "java_re" with gcc 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)` so it's definitely the x86-64 build of the JVM. I would say this is likely to be a JVM bug or a bad interaction between this JVM and Rosetta on the aarch64 platform. The best Mirth could do (in the short-term) would be to upgrade to the latest hassle-free-license Java 1.8 JVM and see if this crash stops happening. Better yet, switch to an aarch64 JVM which would also necessitate a major upgrade of the JVM version which might be risky.
