### ISSUE TITLE
Mac OS X Monterey 12.6.2 / Mirth 4.2,  channel loading problems, openJDK

### ISSUE THREAD

**Issue by dobunzli** [nextgenhealthcare/connect#5593]
### Discussed in https://github.com/nextgenhealthcare/connect/discussions/5592

<div type='discussions-op-text'>

<sup>Originally posted by **dobunzli** December 19, 2022</sup>
Hello,
I upgraded from Mirth Connect 4.0 to 4.2. 

I also upgraded OpenJDK from 8 to 19 using JDK FX Zulu installation. In "MCL" I choose "Custom: /Library/Java/JavaVirtualMachines/zulu-19.jdk/" because if not, either "MCL" or "Mirth Connect" will crash.

Then I am able to get into Mirth but when I launch the dashboard my channels are throwing errors like this:

```
Method failed: HTTP/1.1 500 Server Error
com.mirth.connect.client.core.ClientException: Method failed: HTTP/1.1 500 Server Error
Caused by: com.mirth.connect.client.core.EntityException: {
"servlet":"org.glassfish.jersey.servlet.ServletContainer-4efc0396",
"message":"Request failed.",
"url":"/api/4.2.0/channels/statuses/initial",
"status":"500"
}
```

And

```
com.mirth.connect.server.controllers.Cache:187): Code Template Library cache: Failed to load item 4d15d5bd-b78e-406b-be46-23d7f88c1590 from the database
org.apache.ibatis.exceptions.PersistenceException: ### Error querying database.  Cause: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'value' in 'class java.lang.String'### Cause: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'value' in 'class java.lang.String'
```

In Mirth log:

```
ERROR 2022-12-19 13:07:32.454 [qtp502116678-45] com.mirth.connect.model.converters.ObjectXMLSerializer: com.thoughtworks.xstream.converters.ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.Collections$EmptySet
converter           : com.mirth.connect.model.converters.MigratableConverter
message[1]          : Unable to make field private static final long java.util.Collections$EmptySet.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @db44aa2
converter[1]        : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
```

I tried to revert back to openJDK 8 without any success.

echo $JAVA_HOME gives me /Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home

Is there something else I should try or do ?

Thanks in advance !

</div>

**Comment by jonbartels** [comment]
> module java.base does not "opens java.util" to unnamed module @db44aa2

You need an additional option in `mcservice.vmoptions`. See https://docs.nextgen.com/bundle/Mirth_User_Guide_411/page/connect/connect/topics/c_Using_Java_9_or_greater_mirth_connect_ug.html

You're running Java 19. Starting in Java 18 I found that I also had to add `--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED` in addition to the prepackaged Java 9+ options.

**Comment by dobunzli** [comment]
Hello. Thank you very much and sorry that I didn't read the documentation carefully...
Adding these like you said worked for the precedent error messages

Then as I had other errors like "java.lang.ClassNotFoundException: java.sql.Driver"... I reverted back to openjdk 8 (and definitely erased openjdk 19 from computer). After that everything is working well again with Mirth 4.2.0.
Thanks again !
