### ISSUE TITLE
Spam on community board

### ISSUE THREAD

**Issue by jeroen-meijer** [nextgenhealthcare/connect#5604]
I didn't know spam was a thing on GitHub, but here it is.

Asking the mods if this user can be banned and the comment removed.

Originally posted by @SarahGonzalez4653: https://github.com/nextgenhealthcare/connect/discussions/5572#discussioncomment-4515805

**Comment by jonbartels** [comment]
The user wi4seo is also spamming an AI generated "unconference" to several threads. https://github.com/nextgenhealthcare/connect/discussions?discussions_q=involves%3Awi4seo+

**Comment by jonbartels** [comment]
FWIW It appears that the user that Jeroen reported has been completely banned from GitHub.

**Comment by jeroen-meijer** [comment]
Nice. In that case I guess the issue can be resolved, unless people want to use this as a platform for discussion about spam on your repos in general. (I don't know this org, repo or users, though, so it's up to the mods 😋)

**Comment by jonbartels** [comment]
@jeroen-meijer close it. The backlog on this project is pretty large already and the project maintainers are likely on PTO for another few days.
