### ISSUE TITLE
[BUG] logger instance in a Filter step is object of class org.apache.logging.log4j.core.Logger while logger instance in Transformer step is instance of org.apache.log4j.Logger

### ISSUE THREAD

**Issue by nicovn** [nextgenhealthcare/connect#5607]
**logger** instance in a Filter step is object of class org.apache.logging.log4j.core.Logger while logger instance in Transformer step is instance of org.apache.log4j.Logger

logger.info("logger class name: " + logger.class.getCanonicalName());

**Expected behavior**
Consistent object classes

**Versions**
Mirth Connect Version 4.0.0 and higher

**Workaround(s)**
var log4jv1logger = Packages.org.apache.log4j.Logger.getLogger("filter");
log4jv1logger.info("Logging in filter with log4j v1 class type");

**Comment by nicovn** [comment]
Caused by - JavaScriptBuilder.java - line 331

builder.append(" phase[0] = 'transformer'; logger = Packages.org.apache.log4j.Logger.getLogger(phase[0]);");

**Comment by jonbartels** [comment]
What is the impact of this bug? Does it prevent calling `logger` in filter steps?

**Comment by nicovn** [comment]
No impact inside Mirth Connect itself, only if you pass the "logger" instance to a custom Java component you get a different object class than in the prior Mirth versions (only from within a filter step, in a transformer script the behavior is like in pre 4.x versions).

**Comment by lmillergithub** [comment]
We reviewed this issue and after further investigation, we found that we intentionally implemented it this way. Therefore, we are closing this issue.
