### ISSUE TITLE
[BUG] API does not list all required parameters, causes server NPE

### ISSUE THREAD

**Issue by rogin** [nextgenhealthcare/connect#5624]
**Describe the bug**
There's an [outstanding issue](https://github.com/nextgenhealthcare/connect/issues/5096) with the swagger API for GET /channels/{channelId}/messages - not all of the required parameters are marked.

**To Reproduce**
On a fresh install, open https://localhost:8443/api/#/Messages for "/channels/{channelId}/messages"

**Expected behavior**
Parameters 'limit', 'offset', and 'includeContent' marked as required

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Distribution/Version Java 8
 - Connect Version 3.12

**Comment by rogin** [comment]
EDIT: I wasn't logged into /API page, so the original comment was misleading.

Verified the API doc is still incorrect in v4.2.0, and it throws NPE via a local curl and the "Try it out" section.

**Comment by pacmano1** [comment]
If I recall correctly there a many calls that need the swagger docs updates for required components.

**Comment by jonbartels** [comment]
Should the API documentation be updated at https://github.com/nextgenhealthcare/connect/blob/e0db5497aabb94c41071e4a098580e660a1d5d8e/server/src/com/mirth/connect/client/core/api/servlets/MessageServletInterface.java#L192 with a `required = true` option *or* is it better to dig into the underlying code and prevent the NPE?

Are there testing tools that would automatically parse the swagger docs and ensure that API calls work for required/not-required parameters?

**Comment by lmillergithub** [comment]
Fix pushed 05/03/2023

**Comment by jonbartels** [comment]
@lmillergithub what commit fixes this issue? Is it? https://github.com/nextgenhealthcare/connect/commit/dac27346eed15973b1ad9382394498244a358833

**Comment by lmillergithub** [comment]
Yes.

**Comment by jonbartels** [comment]
TY! 

Since the original scope of the issue was documentation related I looked at https://github.com/nextgenhealthcare/connect/blob/development/server/src/com/mirth/connect/client/core/api/servlets/MessageServletInterface.java

Your commit is consistent with what the documentation annotations say the defaults are. Thanks for humoring me and for tolerating the un-requested code review!

**Comment by frankparth** [comment]
@jonbartels Thanks for looking into this! I'm not sure whether it should give an NPE or just give back the correct 4xx response code that a call was made with a missing parameter. 200 with no content when a parameter is missing is just a bit confusing...
