### ISSUE TITLE
[IDEA] Call mirth with a reverse proxy between the client launcher and the mirth server

### ISSUE THREAD

**Issue by gbenosman** [nextgenhealthcare/connect#5629]
**Is your feature request related to a problem? Please describe.**
The client Launcher start by Download a jnlp file, in this file the attribute codebase of the tag jnlp contains the URL of mirth.
This URL is always fix in the code, you cannot change this value. It works very fine when you call directly mirth, but in the case of you have a reverse proxy between, the client cannot access directly to webstart ressources, and the download failed.
See in WebstartServlet the value of atttribute "codebase"

**Describe your use case**
This my compagny the mirth is called via the reverse proxy, We don't use direct call to the mirth server.
The actual problem is that the provided jnlp from the server contains x.x.x.x:YYYY address in codebase attribute value.
I have a logical error after that when it try to download all webstart libs from codebase URL.

**Describe the solution you'd like**
I propose the following solution:
Add in mirth.properties the **codebase.webstart.url** property.
If this property is set, the codebase value in jnlp file will have the value of the property, and the current value in the other case.
I prepared a branch with the solution but I don't have the rights to push a branch/Fork in the repository.

**Describe alternatives you've considered**
Actually when the release is fixed, I must modify the code and push in our Server. I don't have an other alternative today.

**Comment by jonbartels** [comment]
This issue sounds familiar. It may help if you can search old issues and discussions. I tried but couldn't immediately find the issue. I know you're not the first person to ask about this but I cannot find a reference.

The most common scenario is accessing MC via a proxy or load-balancer on port 443 then the client pops up with 8443. 

The proposed solution seems reasonable.

**Comment by jonbartels** [comment]
https://github.com/nextgenhealthcare/connect/issues/5553

**Comment by gbenosman** [comment]
Hello,
Thank you for this response.
Could I have the permission to push my branch and do I pull request please ?
My Mirth server is in an other VLAN, It is a requirement of our CISO. The IP is not accessible also.
I must request our reverse proxy with https://.....com/mirth
The reverse proxy has only the open port for this server on this VLAN on 8443, he manages the redirection.

I test my solution and I works very well in both cases (Without a RP and with de RP)

Regards

**Comment by pacmano1** [comment]
You can do PRs and Nextgen may consider them. You do need to fill out some legal stuff that their team will ask you for prior to including your work in final produce.  You don't need permissions per se to do a PR/fix.  

Their track record on including PRs, expedited or not is less than stellar.    You can see PRs at https://github.com/nextgenhealthcare/connect/pulls

**Comment by pladesma** [comment]
As mentioned above, you should be able to create a pull request from the branch in your forked repository. We can take a look at it once you've done that.

**Comment by ChristopherSchultz** [comment]
Mirth should have better support for reverse proxies in general.

For example, if you try to fetch WSDL files from Mirth and Mirth is behind a reverse-proxy (or even something simple like stunnel or port-redirection), all of the URLs in the WSDL will likely be wrong. Sure, you can re-write the contents of the WSDL in the proxy but then you have to potentially re-write your rewrites as the WSDL evolves over time (more URLs are added, etc.).

**Comment by MichaelLeeHobbs** [comment]
https://github.com/nextgenhealthcare/connect/issues/4808 https://github.com/nextgenhealthcare/connect/issues/4467 https://github.com/nextgenhealthcare/connect/issues/4220 https://github.com/nextgenhealthcare/connect/issues/1779

**Comment by gbenosman** [comment]
Hello,
I found a solution for this this ticket, I wanted to do a pull request but I don't have the rights to push on the git repository.
I sent an email to nextgen but I never got a feedback.

**Comment by jonbartels** [comment]
@gbenosman fork the connect repo then push to your fork and post the link here please

**Comment by gbenosman** [comment]
Hello !
I created a merger request from my fork.
Thanks

**Comment by JulianVolodia** [comment]
Is there any dev build I could use to have that feature? 😉 Until 4.6.0 is released

**Comment by DevSysEngineer** [comment]
@gbenosman can you expand on what is the difference between codebase.webstart.url and server? I use the server option and have nginx as a proxy.
