### ISSUE TITLE
[IDEA] Support oauth authentication for Mail sender

### ISSUE THREAD

**Issue by nicovn** [nextgenhealthcare/connect#5639]
Microsoft will disable basic authentication for emails in near future

[](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online)

It would be good to foresee oauth authentication in the SMTP Sender connector and the Server Settings screen

**Comment by nicovn** [comment]
https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online

**Comment by pacmano1** [comment]
This is a simliar ask to https://github.com/nextgenhealthcare/connect/issues/5508

**Comment by pladesma** [comment]
This is similar enough to 5508 as pacmano1 mentioned, so I'm closing this as a duplicate.
