### ISSUE TITLE
Code template editor window not scrolling

### ISSUE THREAD

**Issue by jimmydo1** [nextgenhealthcare/connect#5640]
**Describe the bug**
When using the FHIR Resource Builder, part of the 'Builder' container window is hidden. This happens roughly after 30 seconds of viewing the code template library page. If i close the page and come back the issue persists.

**To Reproduce**
Setup steps (if required). Example:
1. Login to Mirth Admin
2. Select Channels
3. Click 'Edit Code Templates'
4. Select a code template. (My one is a 'FHIR Resource Builder' type, but it seems to happen to function code templates as well. I can see the function ones doe resize back though)
5. Wait roughly 30 seconds. code template editor area resizes and moves beyond the bottom of the panel. No vertical scroll bar appears..

**Expected behavior**
I expect the editor area to include a vertical scroll bar when the code template is larger than the visible container/panel.

**Actual behavior**
the code template editor container/panel is larger than the visible area. I cannot scroll down as there is no vertical scroll bar

**Screenshots**
Type: FHIR Resource Builder
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/28144139/215237082-0c322969-93cd-4bcb-9fa4-c5de85683f43.png">
Type: Function
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/28144139/215237450-950b858f-d63f-4546-9dbd-958bf9b3886e.png">

**Environment (please complete the following information):**
 - OS: MacOS Ventura 13.0.1
 - Java Distribution/Version 1.8.0_181 (bundled)
 - Mirth Connect Server 4.2.0

**Workaround(s)**
make the editor area larger, but this comes at a compromise of not being able to see the list of code templates and doesn't work if the code template is larger than screen.

**Comment by pacmano1** [comment]
LOL, that's not so fun.  I see it also on 4.0.1.

**Comment by jimmydo1** [comment]
I had a little success by making my resolution higher/text smaller, but i'm forced to squint when looking at the screen haha

**Comment by pladesma** [comment]
Does this occur only when you idle for 30 seconds or does it also happen when you're actively editing the code template?

**Comment by pacmano1** [comment]
It's just broken,  not sure why OP says 30 seconds.

**Comment by jimmydo1** [comment]
The first 30 seconds, the editor is displayed as expected. The window then resizes or refreshes (not sure). I'm actively editing in the code template.

**Comment by jdonextgen** [comment]
A fix for this has been committed and will be released in MC 4.4.0.

**Comment by jdonextgen** [comment]
A fix for this has been committed and will be released in MC 4.4.0.
