### ISSUE TITLE
[BUG] Mirth is consuming all CPU

### ISSUE THREAD

**Issue by jacsonsoares** [nextgenhealthcare/connect#5642]
**Describe the bug**
When the Mirth service is active the CPU consumption level reaches 100%.
I am using Windows 11.

**To Reproduce**
Start Mirth Connect Service

**Expected behavior**
In previous versions, consumption was according to channel processing..

**Actual behavior**
When the Mirth service is active the CPU consumption level reaches 100%.

**Screenshots**
Not applicable.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Distribution/Version 
    openjdk version "11.0.12" 2021-07-20
    OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7)
    OpenJDK 64-Bit Server VM Microsoft-25199 (build 11.0.12+7, mixed mode)
 - Connect Version 4.2

**Workaround(s)**
Not applicable.

**Additional context**
Not applicable.

**Comment by jonbartels** [comment]
Take a thread dump - https://stackoverflow.com/questions/2124672/java-stack-dump-on-windows

Once you have that you can analyse it and see what threads are running or if there are deadlocked threads.

The thread dump will not contain PII/PHI but it will contain channel names. It should be safe enough to post online but you need to exercise good judgement.

**Comment by jonbartels** [comment]
This bug should be closed. The discussion at https://github.com/nextgenhealthcare/connect/discussions/5643 will help @jacsonsoares find the problem. If the root cause is a genuine MC bug then a new issue can be opened.

**Comment by pacmano1** [comment]
Closed until further discovery by OP.
