### ISSUE TITLE
[BUG] Alert Flood

### ISSUE THREAD

**Issue by iurkenty** [nextgenhealthcare/connect#5664]
Description:
I have set up an alert for a Destination Connector whenever I get an ERROR.
I have one message stuck in a queue(intentionally) and I get a flood of alerts for the same message.

**Expected behavior**
I would like to get one alert per message-id per action(ERROR/SENT)

**Actual behavior**
A flood of alerts for the same message with the same ERROR

**Screenshots**
![image](https://user-images.githubusercontent.com/105752711/217597645-a1e00b1c-4ac7-40e4-99d6-a2f601129188.png)

**Environment (please complete the following information):**
 - Ubuntu 22.04
 - Java Distribution/Version [e.g. OpenJDK 11, Java 8 (201)]
 - Mirth 4.2.0

**Comment by iurkenty** [comment]
Is this because the queue is trying to reprocess the message?
If so, is there a work around to only get the alert once?

**Comment by pladesma** [comment]
Yes, the message is reprocessed from the queue, so that's why it errors again and you get another alert. I don't have a good idea for a workaround, but I'll leave this open in case other users want to comment.
