### ISSUE TITLE
[IDEA] Support Encryption for Message Attachments and Metadata

### ISSUE THREAD

**Issue by ab-20-m** [nextgenhealthcare/connect#5673]
**Is your feature request related to a problem? Please describe.**
Currently Mirth supports encryption of message content. Attachments and metadata are always stored plain-text in the backing database. It is not obvious to users that the `Encrypt message content` option would not also include message attachments/metadata. The hover text and documentation make no mention of encrypting attachments and/or metadata, but do not also explicitly state those won't be encrypted. Attachment handlers are the de facto tool to deal with large messages when processed by Mirth.

Certain configurations of Mirth might fall outside of CURES certification if the implementing entity was depending/assuming on Mirth to provide data-at-rest security capabilities when using attachment handlers or protection of metadata columns, dependent on the backend database selection and configuration.

**Describe your use case**
Large messages where the entire message is an attachment, or attachments contain PII/PHI. Sensitive data is stored in metadata for a channel.

**Describe the solution you'd like**
Attachments and metadata can be configured to be encrypted on a per-channel basis. Encryption keys for attachments and metadata are different from the key used to encrypt message content.

**Describe alternatives you've considered**
Don't use message attachments if sensitive data would be included. Use a backing database that supports Transparent Data Encryption (TDE) or Column level encryption and configure appropriately.

**Comment by joaryche** [comment]
closed with 4.3.0
