### ISSUE TITLE
[Docs] Slack Registration down

### ISSUE THREAD

**Issue by ReboundMD** [nextgenhealthcare/connect#5696]
### Slack registration link in README.md no longer working
Readme points to https://mirthconnect.herokuapp.com/ which presents the below message. I've tried following the link using Chrome under multiple profiles, including a Guest profile with no extensions or plugins.

### Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by jonbartels** [comment]
The Postgres Slack community recently had a similar problem. Heroku changed their free tiers a bit and it broke the invite link.

The workaround is that Slack now supports invite links directly - try this https://join.slack.com/t/mirthconnect/shared_invite/zt-1prqon9tg-UQ_~6AsV8IwdITTo3z1aoA

There is also a less-active Discord server run by community volunteers at https://discord.gg/qKWHABkmAM

**Comment by ReboundMD** [comment]
Thanks. That worked. Should I issue a PR to update the link in README to use that shared_invite link?

**Comment by jonbartels** [comment]
@ReboundMD yes! NextGen has improved their PR approval time.

**Comment by pladesma** [comment]
@ReboundMD We would definitely appreciate a PR updating the documentation.

**Comment by ReboundMD** [comment]
Sorry - been caught up in a bunch of stuff. I'll try to figure it out in the next day or two.

**Comment by ReboundMD** [comment]
PR sent from my personal account.

Thanks for the nudge to get another green box in my Contributions Activity.

**Comment by narupley** [comment]
Merged! That's certainly a lot easier than having to maintain some invite bot.
