### ISSUE TITLE
[BUG] Email Contents Output to System.out When Using the ServerSMTPConnection.send() Method

### ISSUE THREAD

**Issue by jdonextgen** [nextgenhealthcare/connect#5766]
**Describe the bug**
Using the ServerSMTPConnection.java class to send emails out. In the send() method, it has “debug” enabled and this is causing email content (To, From, Subject, Content, etc.) to be output to System.out. This poses as a potential security threat since it’s possible for PHI to be included in the email which would then be outputted to the system logs in this case. This is consistently reproducible.

**To Reproduce**
1. Setup Email/SMTP settings under Mirth Connect → Settings → Server → Email
2. Settings Used:
    SMTP Host: smtp.office365.com
    SMTP Port: 587
    Send Timeout (ms): 5000
    Default From Address: [insert own email]
    Secure Connection: select [STARTTLS]
    Require Authentication: Yes
    Username: [insert own email]
    Password: [use password setup from [https://www.office.com/](https://www.office.com/?auth=2) → View account → Security info → Add method → App password]

1. Create a new channel
2. Under Summary → Channel Properties → Data Types: → Set Data Types → Set Inbound and Outbound to [Raw] (this step isn’t required but makes for easier testing)
3. Source and Destination connector types = Channel Reader/Channel Writer 
4. On the Destinations tab, click Edit Transformer
5. Under Transformer Tasks → click Add New Step → switch the Type to JavaScript
6. On the right-hand window under the Reference tab, Filter: on [email]
7. Drag and drop the [Send an Email] reference to the left-hand window under the Step tab
8. This will auto-populate that window with the following JavaScript code:
    ```
    var smtpConn = SMTPConnectionFactory.createSMTPConnection();
    smtpConn.send('to', 'cc', 'from', 'subject', 'body', 'charset'); 
    ```
    Change the ‘to’, ‘cc’, and ‘from’ parameters to ‘[insert your own email]’, change the ‘subject’ and ‘body’ fields to whatever you want, and leave ‘charset’ as the empty string '' 
9. Save Changes
10. Deploy Channel
11. On the Dashboard, send a test message through the channel
12. Observe that an email log is output to System.out and contains the email contents: To, From, Subject, Body, etc.
13. To view the output from System.out, see the Console output in Eclipse for the Mirth Connect Server.

**Expected behavior**
Email Contents should not output to any logs by default.

**Actual behavior**
Email Contents are output to System.out when using ServerSMTPConnection.send() Method

**Environment (please complete the following information):**
 - OS: [e.g. Linux (CentOS), Windows 10, MacOS]
 - Java Distribution/Version [e.g. OpenJDK 11, Java 8 (201)]
 - Connect Version [e.g. 3.8.0]: 4.2.0, 4.3.0

**Workaround(s)**
Are there one or more workarounds for this issue currently?

**Additional context**

**Comment by lmillergithub** [comment]
Fix pushed 05/03/2023
