### ISSUE TITLE
[BUG] Starting Mirth Connect Administrator logs out user when connecting to mirth connect server (on Ubuntu 23.04)

### ISSUE THREAD

**Issue by JayPi4c** [nextgenhealthcare/connect#5803]
**Describe the bug**
When I try to connect to the Mirth Server using the desktop Mirth Connect Administrator (4.3.0) Client on Ubuntu 23.04 I get logged out from the Ubuntu session. I know that the server is reachable and the credentials are alright. In fact, I am able to use the same way to connect to the server on Ubuntu 22.10 without any problems. To check that my system is not screwed up by upgrading from Ubuntu 22.10 to 23.04, I freshly installed Ubuntu 23.04 in a VM and tried to connect: same error: Ubuntu user got logged out. I don't know what happens but at some point Ubuntu decides to not continue with Mirth Connect Administrator but rather completly stop the user session.
I know 23.04 is not an LTS version and the workaround with Ubuntu 22.10 is okay for me for now. But if the problem is a missing binary in Ubuntu or something else, this problem might still be present in the next LTS release of Ubuntu.

**To Reproduce**
1. Have a clean Ubuntu 23.04 installation
2. Download and install latest (4.3.0) Mirth Connect Administrator (link from Mirth Server URL)
3. Enter URL in Mirth Connect Administrator Launcher (1.3.1)
4. Launch client
5. Enter credentials
6. Error: get logged out from Ubuntu 23.04 session

**Expected behavior**
Normal Mirth Connect Administrator view after successful login (not getting logged out from Ubuntu)

**Actual behavior**
The Ubuntu user gets logged out.

**Environment (please complete the following information):**
 - OS: Ubuntu 23.04
 - Java Distribution/Version: (Bundled) 
   - Using JRE version 1.8.0_181-b13 Java HotSpot(TM) 64-Bit Server VM
   - Java home directory = /opt/mirth-administrator-launcher/jre
 - Connect Version: 4.3.0

**Workaround(s)**
Use Ubuntu 22.10

**Comment by JayPi4c** [comment]
As it turns out, it is a problem with the mutter version, that is shipped with Ubuntu 23.04. This problem is known to the mutter devs as described [here](https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/2016308). It's just not distributed to the Ubuntu systems yet. With `mutter - 44.1-1ubuntu1` the problem should be solved.
Also, as another workaround, using X-Org instead of the default Wayland does allow to start the application properly.

**Comment by pacmano1** [comment]
Good write up and follow up!
