### ISSUE TITLE
MCAL 1.4 will not log into engines running version 3.5.1

### ISSUE THREAD

**Issue by rp-ryanwilson** [nextgenhealthcare/connect#5820]
Since upgrading to MCAL version 1.4, I cannot login to any engines running version 3.5.1 of Mirth.  It gives me a prompt to login, lets me enter user credentials, then is stuck at the 'Please wait: Logging in...' screen.

It works fine on engines running version 4.0.1.

The only workaround is to use an older version of the launcher for any engines running this version of Mirth.

**Comment by pacmano1** [comment]
The release notes at https://github.com/nextgenhealthcare/connect/wiki/1.4.0---What's-New-in-MCAL   explicitly say:

If you are running Mirth Connect Administrator version 3.6 or lower that doesn't support Java (OpenJDK) 17 or Java (OpenJDK) 8, then you may need to download Oracle JRE 8 and set it as your "Custom" Java Home in the launcher settings for that server.

Did you try that?

**Comment by rp-ryanwilson** [comment]
I did not.  That resolved the issue.  Thanks!

**Comment by jonbartels** [comment]
@rp-ryanwilson please close this issue since you found a solution
