### ISSUE TITLE
[IDEA] Stored Response Status Code as Individual Variable. 

### ISSUE THREAD

**Issue by RunnenLate** [nextgenhealthcare/connect#5823]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add a Response Map variable to store just the status code 
EXAMPLE: '200', '500', '401'
This value is used a log in the response logic to determine what the next action is to be taken in the channels workflow. 

**Describe your use case**
I need this feature so I can accomplish <X>.

**Describe the solution you'd like**
Seems like the following code could be added to the HttpDispatcher code here 

`connectorMessage.getConnectorMap().put("responseStatusCode", statusCode.toString());`

https://github.com/nextgenhealthcare/connect/blob/e0db5497aabb94c41071e4a098580e660a1d5d8e/server/src/com/mirth/connect/connectors/http/HttpDispatcher.java#L339

**Describe alternatives you've considered**
The current method requires parsing it out from the `$('responseStatusLine')` like so `$('responseStatusLine').toString().substring(9, 12)`

**Comment by rogin** [comment]
PR [created](https://github.com/nextgenhealthcare/connect/pull/6170) this morning.

**Comment by jdonextgen** [comment]
Feature has been committed and will be included in our Mirth Connect 4.5.2 release. Thank you!
