### ISSUE TITLE
[Improvement] MCAL includes executables and libraries for all OSs even in OS specific distributions

### ISSUE THREAD

**Issue by jonbartels** [nextgenhealthcare/connect#5824]
MCAL includes JVMs for MacOS, Unix, and Windows with distributions for other OSs.

Update MCAL so that the OS specific distribution are smaller and only include data needed for that OS.

Example from MCAL 1.4 on MacOS:
```
pwd ; du -h -d 1
/Users/jonathan.bartels/Applications/Mirth Connect Administrator Launcher.app/Contents/java/app/mcadministrator
141M	./windows-x64
263M	./macos
321M	./unix
2.4M	./windows
727M	.
```

**Comment by jdonextgen** [comment]
Enhancement has been implemented and will be included in the MCAL 1.4.2 release. Thank you!
