### ISSUE TITLE
Decode and filter JWT

### ISSUE THREAD

**Issue by 5011-5011** [nextgenhealthcare/connect#5840]
@bharbharHi, I would like to know if you can help me.
I'm working on filtering the jwt by its time of issue. I have tried to do this by creating functions that take the jwt from the incoming request header, then decode it and filter it by its broadcast time.
However I have not been successful, I think the problem is because it does not decode the jwt and does not process the following.
I have read that certain libraries like jsonwebtoken are not compatible with Mirth connect, I have my doubts about this.
If you could help me I would appreciate it, I've been stuck on this for a while.

_Originally posted by @bharbhar in https://github.com/nextgenhealthcare/connect/discussions/5503#discussioncomment-4061307_

**Comment by pacmano1** [comment]
@5011-5011 This should be in discussions, not submitted as an issue.  I am moving it now.
