### ISSUE TITLE
Duplicating Destination uses same ID as previous destinations.

### ISSUE THREAD

**Issue by GhLinden** [nextgenhealthcare/connect#5895]
I am using Mirth Connect Administrator 4.1.0.  When I try to create a new destination by right clicking a current destination and choosing Duplicate Destination it creates the new destination but gives it a destination ID that is already in use (not the ID of the duplicated destination).  I believe the administrator should increment the new ID to largest ID + 1.  The way I am dealing with this is to add destinations, export, edit the ID and import.  Is there something I am missing or is there a better way to deal with this?
Thanks,

**Comment by pacmano1** [comment]
I assume you mean "Clone Destination".   I do not see that behavior.

**Comment by pladesma** [comment]
I've tested this in 4.4.1, and I also don't see this behavior. I'm closing this issue, but feel free to open a new issue if you can recreate this bug in 4.4.1.

Edited: Changed 4.5.0 to 4.4.1

**Comment by GhLinden** [comment]
Are there changes between 4.5.0 and 4.1.0 that would affect channels
already configured.   These were configured programmatically outside of the
administrator so is there something that might not have gotten updated in
the administrator that would make it use a previously configured number?

**Comment by pladesma** [comment]
I don't see any changes in particular since 4.1.0 that would affect channels in this way. 

I suppose there could be an issue with programmatically created channels if the channels are configured in some unexpected way. It could be helpful if you provide an example channel and/or explain how the channels are being programmatically configured.
