### ISSUE TITLE
Mirth service has high CPU usage 80%

### ISSUE THREAD

**Issue by ourlang** [nextgenhealthcare/connect#5900]
Middle connect version 4.4, after the Win10 system boots up, the CPU temporarily uses over 80%, only five channels are set incorrectly? Such a high CPU utilization rate causes other software and computers to be too laggy. What can we do to reduce the CPU to below 50%?

The relevant screenshots are as follows
![image](https://github.com/nextgenhealthcare/connect/assets/32355185/84f6c126-c6cd-4a27-9f5c-f2a2ba411467)

![image](https://github.com/nextgenhealthcare/connect/assets/32355185/0c1c47a0-5119-42cf-8e3a-de0d4be9d5e5)

![image](https://github.com/nextgenhealthcare/connect/assets/32355185/3e30c799-0e47-44a9-90bc-62ce785ad22c)

**Comment by ourlang** [comment]
Actual behavior
When the Mirth service is active the CPU consumption level reaches 100%.

Environment (please complete the following information):

OS: Windows 10
Java Distribution/Version
jdk version "1.8" 
Connect Version 4.4
Workaround(s)
Not applicable.

**Comment by kirbykn2** [comment]
What channel/process is using the CPU?  You need to do some troubleshooting.

**Comment by ourlang** [comment]
Even if I don't publish any channels, I still use over 70% CPU temporarily

**Comment by pacmano1** [comment]
It will use a lot of CPU on startup of the Mirth service, that is expected.

**Comment by ourlang** [comment]
![image](https://github.com/nextgenhealthcare/connect/assets/32355185/4b907a74-8a7c-4af2-97e7-e072cafe02d6)

**Comment by pacmano1** [comment]
Is that continous?  meaning "always" even if no channels are running?  Is there anything in the mirth.log file?

**Comment by ourlang** [comment]
After the successful startup of mirth, it still maintains a CPU usage of over 70%. May I ask if there is a way to set the CPU usage to lower it a bit

**Comment by pacmano1** [comment]
- Share java version.  
- What underlying database is being used for mirthdb?   
- Do you have the vmoptions set correctly for java 9 or newer.

**Comment by ourlang** [comment]
INFO  2023-08-21 15:51:50.810 [Shutdown Hook Thread] com.mirth.connect.server.Mirth: shutting down mirth due to normal request
INFO  2023-08-22 11:17:54.021 [Main Server Thread] com.mirth.connect.server.Mirth: Mirth Connect 4.4.0 (Built on July 18, 2023) server successfully started.
INFO  2023-08-22 11:17:54.027 [Main Server Thread] com.mirth.connect.server.Mirth: This product was developed by NextGen Healthcare (https://www.nextgen.com) and its contributors (c)2005-2023.
INFO  2023-08-22 11:17:54.027 [Main Server Thread] com.mirth.connect.server.Mirth: Running Java HotSpot(TM) 64-Bit Server VM 1.8.0_341 on Windows 10 (10.0, amd64), derby, with charset UTF-8.
INFO  2023-08-22 11:17:54.726 [Main Server Thread] com.mirth.connect.server.Mirth: Web server running at http://192.168.12.45:18080/ and https://192.168.12.45:18443/
INFO

**Comment by ourlang** [comment]
The content in the log

**Comment by ourlang** [comment]
jdk version 1.8  The default database used by mirthdb (file system database)
![image](https://github.com/nextgenhealthcare/connect/assets/32355185/32aaeb66-38f5-4098-951b-38c1e39a8e4f)

**Comment by ourlang** [comment]
Is it a problem with the JDK version？

**Comment by pacmano1** [comment]
Make sure your pruning settings are the default.  

But I would not expect CPU to be that high with no channel running.   

You could try a newer java version though.  Don't forget the readme in the additional required vmoptions if using java 9 or newer.

And using Derby (the file database) is very bad practice except for testing and development work.

**Comment by ourlang** [comment]
additional required vmoptions file ? for example？
Thank you very much. Let me try a higher version of JDK. Would it be better to use Openjdk or Oraclejdk?

**Comment by pacmano1** [comment]
Read the documentation.  You should be doing that anyway.    https://docs.nextgen.com/bundle/Mirth_User_Guide_4_4_0/page/connect/connect/topics/c_Using_Java_9_or_greater_mirth_connect_ug.html

I use Amazon Coretto OpenJDK since it has a nice installer.  Azul java is fine also.

**Comment by ourlang** [comment]
I'll give it a try according to your method

 Thank you very much for your thoughtful answer

**Comment by tonygermano** [comment]
When using Derby, that is the embedded database, so any CPU usage that would normally be attributed to the DB engine will instead be attributed to the mirth server process.
