### ISSUE TITLE
Generate corresponding log4j2 according to the channel

### ISSUE THREAD

**Issue by ourlang** [nextgenhealthcare/connect#5901]
All logs are in one file, which is not easy to troubleshoot. Is there any configuration where each channel or group corresponds to a log4j2 file?

If you have any configuration examples, please provide them. Thank you

**Comment by jonbartels** [comment]
https://github.com/odoodo/Mirth-MetaAppender

**Comment by pladesma** [comment]
We don't currently support this, but the link shared above appears to be a good solution.
