### ISSUE TITLE
{BUG} Error Downloading / Verifying Codebase

### ISSUE THREAD

**Issue by knappl-mmri** [nextgenhealthcare/connect#5929]
**Describe the bug**
Receive "Error downloading/verifying codebase" (unable to retrieve payload from HTTP request...). when attempting to launch a Mirth connection after re-opening launcher

**To Reproduce**
1. Open launcher, check box to close launcher window.  
2. Launch a Mirth connection.
3. Open the launcher 
4. attempt to launch another Mirth connection 
5. error, "Error downloading/verifying codebase" (unable to retrieve payload from HTTP request...). 

**Expected behavior**
Mirth connection should open without error

**Actual behavior**
"error downloading/verifying codebase" (unable to retrieve payload from HTTP request...). 

**Screenshots**
![image](https://github.com/nextgenhealthcare/connect/assets/50667112/2323f024-35f6-4ebd-8d3e-a49455dd07bf)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Distribution/Version  Java 8 (201)
 - Connect Version [e.g. 4.1.0]
 

**Workaround(s)**
Not that I know of

**Additional context**

**Comment by jonbartels** [comment]
The interesting part of your stack trace is the "unknown address" and "cached address" line.

I am doing some Googling but that sounds like maybe the cache is invalid or the address somehow changed between launches? See "Inet Address Caching" at https://docs.oracle.com/javase/8/docs/api/java/net/InetAddress.html

Can you copy and paste the text of the stack trace and post it here **using code formatting** please?

When the issue happens can you use a browser, `curl`, or `wget` to fetch `https://interface:8443/` ? Do other HTTP clients fail too?

You might try https://github.com/kayyagari/ballista as a workaround. It is an open-source alternative to the launcher. If this is a genuine DNS or networking issue the client won't matter.

**Comment by knappl-mmri** [comment]
Thank you for your time!  I was working with NextGen Success Community and this error was supposed to go there.  I don't know if this can be deleted, but it can certainly be closed. I couldn't access with a browser and realized there was a typo :(
Your comments were a big help!
