### ISSUE TITLE
How to upgrade mirth connect version 3.5.2 to version 4.4.2

### ISSUE THREAD

**Issue by EthanTang-Zq** [nextgenhealthcare/connect#6010]
I want to upgrade mirth connect version 3.5.2 to version 4.4.2. What should I pay attention to? My database is MySQL5.7.24. After I upgraded using mirthconnect-4.4.2.b326-windows-x64.exe, mirth connect cannot connect to the database. Are there any compatibility issues I need to pay attention to? No relevant instructions or documentation found.

Environment :

OS: Windows server 2019
openjdk 1.8.0.372（The jre that comes with mirth connect used after the upgrade）

**Comment by jonbartels** [comment]
Stop posting duplicated issues.

#6007 #6009 and #6010 are all the same problem. These are also NOT application bugs.

You should keep replying on #6007 to get help with your issue.

**Comment by pacmano1** [comment]
closing duplicate
