### ISSUE TITLE
[BUG] Mirth 4.0,1 VDI unexpectedly stops writing to mirth.log

### ISSUE THREAD

**Issue by phommata** [nextgenhealthcare/connect#6042]
**Describe the bug**
A clear and concise description of what the bug is. Is this consistently reproducible?
When I launch and use Mirth 4.0,1 VDI, I am not seeing any logs being written out to `logs/mirth.log`. When I run Mirth locally I can see the logs being written out. The server logs show up on the dashboard. Although, the `mirth.log` are more helpful and easier to use. Logs stopped writing 13 days ago. Relaunching Mirth does not remedy the issue.

**To Reproduce**
1. Launch Mirth 4.0.1 VDI
2. Check `mirth.log`
3. See no new logs written or update timestamp on log file

**Expected behavior**
I expected `mirth.log` file to be written to and updated when I use Mirth.

**Actual behavior**
No logging to `mirth.log`.

**Screenshots**
![image](https://github.com/nextgenhealthcare/connect/assets/7331396/74fcd451-4807-466a-ba0e-8d8f8beb82a0)

**Environment (please complete the following information):**
 - OS: Windows 10 Enterprise Version 21H2
 - Java Distribution/Version [OpenJDK 17.0.2]
 - Connect Version [4.0.1]

**Workaround(s)**
Use Dashboard's Server logs.

**Additional context**
None.

**Comment by jonbartels** [comment]
What user is Mirth running as?

What user has write permissions to the `logs` directory?

**Comment by phommata** [comment]
My VDI instance and Mirth are running as a Power User with elevated permissions than a regular user. My Windows group that I belong to has all permissions enabled.

**Comment by pacmano1** [comment]
This typically happens when the Mirth Connect directory is not writable by the current service "run as" user.   So, if you login as that service user and attempt to create a file in the logs directory, can you?

**Comment by pacmano1** [comment]
Delete that mirth.log file (the empty one), and stop mirth and restart it.  Check task manager to make sure the service actually stopped before restarting.   

(and a reminder to make sure you added the required java9+ parameters to the end of  mcserver.vmotions and mcserver.vmptions the installer does not do that.)

**Comment by phommata** [comment]
I did not change anything and noticed mirth.log writing again. Not sure why.

**Comment by pacmano1** [comment]
@jonbartels fault.
