### ISSUE TITLE
channel  message  text search slow

### ISSUE THREAD

**Issue by ourlang** [nextgenhealthcare/connect#6064]
Searching for a text match takes 30 minutes

Is there any optimization method or is there something wrong with the operation

<img width="463" alt="1705589430716" src="https://github.com/nextgenhealthcare/connect/assets/32355185/49b95897-39fb-415c-8b7e-3bc693799c87">

**Comment by pacmano1** [comment]
The way you are searching requires a full table scan.  Mirth will search everywhere (source and destinations).    So the search time will be impacted by the number of messages you have.

For faster searching, uses metedata columns (see the advanced button).   You can also limit dates.

Lastly, your question is not an "issue", it is a something you do not undertand about Mirth.  Please do not create issue unless it is confirmed bug.
