### ISSUE TITLE
Mirth service is not getting restarted

### ISSUE THREAD

**Issue by Shahabuddin222** [nextgenhealthcare/connect#6163]
Mirth service is not getting restarted if we use Recovery option which is present under Windows Services under Recovery tab.
There is any alternative thing to restart if the service is getting stopped for some issue
![Screenshot 2024-04-16 145607](https://github.com/nextgenhealthcare/connect/assets/167187884/605dc960-e5ec-4463-8239-9a64e78b96e1)

**Comment by Shahabuddin222** [comment]
Anyone here who can help me out

**Comment by pacmano1** [comment]
Why is the service getting stopped to begin with?

What does the mirth log file say when it stops unexpectedly?

Mirth almost never stops on its own, it is extremely reliable.

In fact it is so reliable, I've never had to rely on the operating system to restart it.

**Comment by ab-mg-23** [comment]
[Restart Actions](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/ns-winsvc-service_failure_actions_flag) only happen: 

> If this member is TRUE and the service has configured failure actions, the failure actions are queued if the service process terminates without reporting a status of SERVICE_STOPPED or if it enters the SERVICE_STOPPED state but the dwWin32ExitCode member of the [SERVICE_STATUS](https://learn.microsoft.com/en-us/windows/desktop/api/winsvc/ns-winsvc-service_status) structure is not ERROR_SUCCESS (0).

If something on the system is using the WinService API or sc.exe to stop the Mirth Service, that's WAD. If you need to find out what/whom is making the service stop that way, you can configure Windows Auditing on [Audit Handle Manipulation and Audit Other Object Access Events - Success](https://learn.microsoft.com/en-us/archive/msdn-technet-forums/aeeecc07-368f-4f68-b773-6af70eec2995). However, doing so will generate a large number of entries so you should only enable it for as long as you need to find the culprit.

**Comment by pacmano1** [comment]
Moving to discussions until this is a confirmed issue.
