### ISSUE TITLE
How to see "Processed Raw" in the source next to "Raw"

### ISSUE THREAD

**Issue by Graziano-Calella** [nextgenhealthcare/connect#6335]
In the channel source I get a message like this:

""fake message example""
`<env:Envelope xmlns:env="http://pippo.org/2007/02/soap-envelope">
    <env:Header/>
    <env:Body>
        <MSG_HL7>PEhMQSUQuMy44LjI3LjY+PC9PQlI+PE9CUi4zNi8+PC9PQlI+PC9ITDdNZXNzYWdlPg==</MSG_HL7>
    </env:Body>
</env:Envelope>`

In the preprocessor I have this code:

`var message_xml = new XML(message);
message = new java.lang.String(FileUtil.decode(message_xml.*::['Body']['MSG_HL7'].toString())).toString();

return message;`

The script as final output returns the decoded base64 message which contains a hl7 XML message.

At this point, if I set the inbound of the XML type source there are no errors, but I don't see the "Processed Raw" tab appear.
While if I set the inbound of the HL7 pipe v2.x type source, the source fails (and doesn't go forward in the destinations), but I finally see the "Processed Raw" tab with the transformation from the enveloped message that I received, to the one decoded in XML.

Furthermore, when the source fails, I also see a third tab, that of the "transformer" in addition to "raw" and "Processed Raw", with a completely wrong value, that is, the opening and closing tags of the xml are messed up.

What I would like is to see the "Processed Raw" in the source and that it doesn't fail obviously, so that I can work with the destinations later.
How can I do it?

I attach some images that may be helpful

![Screenshot (33)](https://github.com/user-attachments/assets/0e79dbe2-0781-4bf5-9a76-6b084688942e)

![Screenshot (34)](https://github.com/user-attachments/assets/f28a509f-91db-4cd5-9252-29c808ff76c2)

![Screenshot (32)](https://github.com/user-attachments/assets/6108564e-7352-49f0-ae8f-d83a6cd2ac95)

![Screenshot (35)](https://github.com/user-attachments/assets/19003191-b050-4913-bb28-1c941a0bda99)

**Comment by pacmano1** [comment]
Moving your post to the Q and A section.
