### ISSUE TITLE
Patch request unavailable

### ISSUE THREAD

**Issue by Sttug** [nextgenhealthcare/connect#8]
hi, I try enable appointment with fhir complement, all work fine, but when i try update date via patch request get error, look like option PATCH don't load in appointment. 

access control allow methods not show PATCH.

![c8f27da3-5373-4211-b12d-45cc3ad669d6](https://user-images.githubusercontent.com/21311823/55880061-f450a700-5b6d-11e9-855b-5b7ad5296576.jpg)

Error.

![7d359d9f-a9f9-4a8a-8c89-ea6ae32d2947 (1)](https://user-images.githubusercontent.com/21311823/55880062-f450a700-5b6d-11e9-8f46-32819054303d.jpg)

Patch Method enable in channel.

![7d4aebba-ff06-47c8-8818-86a991838ae1](https://user-images.githubusercontent.com/21311823/55880063-f4e93d80-5b6d-11e9-8b2f-fbd315991b4c.jpg)

whit GET, POST, PUT method work fine, but i need PATCH.

![b504361d-a72d-40c9-9078-1ca6bb14b2b0](https://user-images.githubusercontent.com/21311823/55880066-f4e93d80-5b6d-11e9-9bf9-f79c1cceca33.jpg)

Question is i do something wrong ?

**Comment by cturczynskyj** [comment]
This will be fixed in version 3.9.0, thanks for your report!
